In [1]:
import re
import pandas as pd
import time
import numpy as np
import matplotlib.pyplot as plt
import os
import seaborn as sns

### Reading in the Data

In [2]:
race = 'TOR450'

In [3]:
TOR450_dem = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_dem.xlsx')

In [4]:
TOR450_dem['Bib'][(TOR450_dem['Year'] == 2022) &
               (TOR450_dem['Retired'] == 'Bosses')].nunique()

0

In [5]:
TOR450_dem.groupby( ['Year','Status1'] )['Status1' ].count()

Year  Status1
2021  Finished at Courmayeur    1
Name: Status1, dtype: int64

In [6]:
lifebase_cut_offs_df = pd.read_excel(f'{race} Data/4. TOR450 Timetable Data/{race}_lifebase_cut_offs_df.xlsx')

# # # Convert integer seconds to timedelta
lifebase_cut_offs_df['Lifebase Duration'] = pd.to_timedelta(lifebase_cut_offs_df['Lifebase Duration_seconds'], unit='s')

# # # Convert integer seconds to timedelta
lifebase_cut_offs_df['Running Total Lifebase Duration'] = pd.to_timedelta(lifebase_cut_offs_df['Running Total Lifebase Duration_seconds'], unit='s')

lifebase_cut_offs_df

,Lifebase,Lifebase Distance (km),Lifebase Accumulated Distance Elevation (m),Lifebase Elevation Gain (m),Lifebase Accumulated Elevation (m),Lifebase Duration_seconds,Running Total Lifebase Duration_seconds,Lifebase Duration,Running Total Lifebase Duration
0,Cogne IN,159,159,10844,10844,230400,230400,2 days 16:00:00,2 days 16:00:00
1,Donnas IN,68,227,4948,15792,90000,320400,1 days 01:00:00,3 days 17:00:00
2,Gressoney IN,60,287,5647,21439,118800,439200,1 days 09:00:00,5 days 02:00:00
3,FINISH,156,443,10878,32317,244800,684000,2 days 20:00:00,7 days 22:00:00

In [7]:
checkpoints_bib_df = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_checkpoints_bib_df.xlsx')

In [10]:
# all_aid_station_bib_df = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_all_aid_station_bib_df.xlsx')

In [9]:
lifebase_bib_df = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_lifebase_bib_df.xlsx')

In [12]:
# making duration hours 
datasets = [checkpoints_bib_df, lifebase_bib_df,
#             all_aid_station_bib_df,
            TOR450_dem]
for df in datasets:
    df['Duration_hours'] = df['Duration_seconds']/ 3600

### Getting Average and Median time for lifebases

In [18]:
checkpoint_category_order = [ 'START',
                        'Cogne IN', 'Cogne OUT',
                        'Donnas IN', 'Donnas OUT',
                        'Gressoney IN', 'Gressoney OUT', 
                        'Rifugio Champillon', 
                             'FINISH']

lifebase_category_order = ['START',
            'Cogne IN', 'Cogne OUT', 
            'Donnas IN', 'Donnas OUT', 
            'Gressoney IN', 'Gressoney OUT', 
                           'FINISH' ]



Stage1 = [ 'START', 'Rifugio Maison Vieille', 'Rifugio Elisabetta',
 'Rifugio Deffeyes', 'Rifugio degli Angeli', 'Rifugio Bezzi',
 'Rifugio Benevolo', 'Rifugio Savoia', 'Rifugio Vittorio Emanuele II',
 'Rifugio Chabod', 'Rifugio Sella', 'Cogne IN']

Stage2 = [ 'Cogne OUT', 'Rifugio Grauson', 'Rifugio Dondena', 'Rifugio Miserin', 'Dortoir Crest',
 'Dortoir Retempio', 'Rifugio Bonze', 'Donnas IN']

Stage3 = [ 'Donnas OUT', 'Perloz','Sassa',  'Rifugio Coda', 'Rifugio della Barma',
 'Lago Chiaro', 'Col della Vecchia', 'Niel La Gruba',
 'Loo', 'Gressoney IN']

Stage4 =  ['Gressoney OUT', 'Rifugio Sitten', 'Rifugio Ferraro','Rifugio Guide di Frachey',
 'Rifugio Duca degli Abruzzi', 'Hotel Stambecco', 'Rifugio Perucca Vuillermoz',
 'Rifugio Prarayer', 'Rifugio Crête Sèche',
 'Rifugio Champillon', 'Ponteille Desot',
 'Hotel Italia', 'Rifugio Frassati',
 'Pas Entre Deux Sauts', 'Monte de la Saxe', 'Parco Bollino', 'FINISH'] 

Stage4_diversion =  [  'Oyace',  'Oyace OUT',
 'Bruson Arp', 'Col Brison',
 'Berio Damon', 'Ollomont IN',
 'Ollomont OUT']

DNF_areas =  [  'Champoluc', 'Valtourenche OUT', 'Bosses']

stages =[ Stage1, Stage2, Stage3, Stage4, Stage4_diversion, DNF_areas]
stages_str =[ 'Stage 1', 'Stage 2', 'Stage 3', 'Stage 4', 'Stage 4 Diversion', 'DNFed on TOR330 route' ]

lifebase_time_spent = ['Cogne OUT','Donnas OUT','Gressoney OUT']

In [24]:
def creating_time_stats(df, column, category_order):
    
    df_merge = df.merge(
        TOR450_dem[['PK', 'Finish Category']],
        on=['PK'],
        how='left')


    df_merge['Duration_seconds'][df_merge['Duration_seconds']  <= 0] = np.nan

    stats_df = df_merge.groupby(['Finish Category', column])['Duration_seconds'].describe().reset_index(drop = False)


    stats_df[[ 'mean', 'std', 'min', '25%',
           '50%', '75%', 'max']] = stats_df[[ 'mean', 'std', 'min', '25%',
           '50%', '75%', 'max']].round(0)

    # Set 'Finish Category' as a categorical column with the defined order
    stats_df[column] = pd.Categorical(
        stats_df[column],
        categories=category_order,
        ordered=True)
    
    stats_df = stats_df.sort_values(by=column, ascending = True)
    
    

    for finish_category in df_merge['Finish Category'].unique():
#         print(finish_category)
        stats_df.loc[
                (stats_df['Finish Category'] == finish_category), 'running_total_mean_seconds'
            ] =     stats_df.loc[
                (stats_df['Finish Category'] == finish_category), 'mean'
            ].cumsum()


        stats_df.loc[
                (stats_df['Finish Category'] == finish_category), 'running_total_median_seconds'
            ] =     stats_df.loc[
                (stats_df['Finish Category'] == finish_category), '50%'
            ].cumsum()


    stats_df = stats_df[['Finish Category', column,
            'count', 'mean', '50%', 'std', 'min', 'max', 
            'running_total_mean_seconds', 'running_total_median_seconds']]


    stats_df = stats_df.rename(columns={'count': f'Count_Finish_Category_{column}_seconds',
                                      'mean': f'Mean_Finish_Category_{column}_seconds',
                                      'std': f'STD_Finish_Category{column}t_seconds',
                                      '50%': f'Median_Finish_Category_{column}_seconds',
                                      'min': f'Min_Finish_Category_{column}_seconds', 
                                      'max': f'Max_Finish_Category_{column}_seconds'})
    stats_df = stats_df[stats_df[column] != 'Start']

    
    
    
    for stage,  stage_str in zip(stages, stages_str):
        stats_df.loc[stats_df[column].isin(stage), 'Stage'] = f'{stage_str}'
        
    for lifebase in lifebase_time_spent:
        lifebase_split = lifebase.split(' OUT')[0] 
        stats_df.loc[stats_df[column] == lifebase, 'Stage'] = f'Time Spent in {lifebase_split}'


    stats_df.to_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_{column}_duration_mean_median_stats_df.xlsx', index = False)

#     print(stats_df[stats_df['Finish Category'] == 'Sub-130'])
    return stats_df

In [19]:
lifebase_stats_df = creating_time_stats(df = lifebase_bib_df, 
                    column = 'Lifebase', 
                    category_order = lifebase_category_order)

lifebase_stats_df

C:\Users\Karina\AppData\Local\Temp\ipykernel_14576\725103266.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge['Duration_seconds'][df_merge['Duration_seconds']  <= 0] = np.nan

Sub-140
Sub-170
Sub-180
DNF
Sub-160
Sub-190
Sub-150
Sub-130
Sub-120

,Finish Category,Lifebase,Count_Finish_Category_Lifebase_seconds,Mean_Finish_Category_Lifebase_seconds,Median_Finish_Category_Lifebase_seconds,STD_Finish_CategoryLifebaset_seconds,Min_Finish_Category_Lifebase_seconds,Max_Finish_Category_Lifebase_seconds,running_total_mean_seconds,running_total_median_seconds,Stage
71,Sub-190,START,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stage 1
63,Sub-180,START,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stage 1
55,Sub-170,START,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stage 1
47,Sub-160,START,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stage 1
7,DNF,START,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stage 1
...,...,...,...,...,...,...,...,...,...,...,...
12,Sub-120,FINISH,2.0,154914.0,154914.0,8870.0,148642.0,161186.0,413595.0,413595.0,Stage 4
28,Sub-140,FINISH,10.0,184350.0,182730.0,4307.0,178531.0,191262.0,492385.0,488170.0,Stage 4
4,DNF,FINISH,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stage 4
60,Sub-180,FINISH,36.0,239235.0,235784.0,12197.0,224959.0,272349.0,632590.0,630705.0,Stage 4
44,Sub-160,FINISH,25.0,216946.0,218915.0,12875.0,189070.0,250862.0,564620.0,566672.0,Stage 4

In [33]:
# # # Convert integer seconds to timedelta
lifebase_stats_df['Median_Finish_Category_Lifebase'] = pd.to_timedelta(lifebase_stats_df['Median_Finish_Category_Lifebase_seconds'], unit='s')
lifebase_stats_df['Mean_Finish_Category_Lifebase'] = pd.to_timedelta(lifebase_stats_df['Mean_Finish_Category_Lifebase_seconds'], unit='s')


lifebase_stats_df[['Finish Category','Lifebase', 'Mean_Finish_Category_Lifebase', 'Median_Finish_Category_Lifebase']][lifebase_stats_df['Finish Category'] == 'Sub-190']

,Finish Category,Lifebase,Mean_Finish_Category_Lifebase,Median_Finish_Category_Lifebase
71,Sub-190,START,NaT,NaT
64,Sub-190,Cogne IN,2 days 04:07:31,2 days 04:00:24
65,Sub-190,Cogne OUT,0 days 03:23:37,0 days 03:20:22
66,Sub-190,Donnas IN,1 days 02:29:02,1 days 02:43:40
67,Sub-190,Donnas OUT,0 days 02:18:11,0 days 01:56:51
69,Sub-190,Gressoney IN,1 days 03:00:32,1 days 03:19:54
70,Sub-190,Gressoney OUT,0 days 02:30:47,0 days 02:13:32
68,Sub-190,FINISH,2 days 22:56:35,2 days 22:47:24

In [37]:
checkpoints_stats_df = creating_time_stats(df = checkpoints_bib_df, 
                    column = 'Checkpoint', 
                    category_order = checkpoint_category_order)



# # # Convert integer seconds to timedelta
checkpoints_stats_df['Median_Finish_Category_Checkpoint'] = pd.to_timedelta(checkpoints_stats_df['Median_Finish_Category_Checkpoint_seconds'], unit='s')
checkpoints_stats_df['Mean_Finish_Category_Checkpoint'] = pd.to_timedelta(checkpoints_stats_df['Mean_Finish_Category_Checkpoint_seconds'], unit='s')


checkpoints_stats_df[['Finish Category','Checkpoint','Stage', 'Mean_Finish_Category_Checkpoint','Median_Finish_Category_Checkpoint']][(checkpoints_stats_df['Finish Category'] == 'Sub-190') &
                                                                                                                                       (checkpoints_stats_df['Checkpoint'] != 'START')]

C:\Users\Karina\AppData\Local\Temp\ipykernel_14576\412525428.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge['Duration_seconds'][df_merge['Duration_seconds']  <= 0] = np.nan

,Finish Category,Checkpoint,Stage,Mean_Finish_Category_Checkpoint,Median_Finish_Category_Checkpoint
72,Sub-190,Cogne IN,Stage 1,2 days 04:07:31,2 days 04:00:24
73,Sub-190,Cogne OUT,Time Spent in Cogne,0 days 03:23:37,0 days 03:20:22
74,Sub-190,Donnas IN,Stage 2,1 days 02:29:02,1 days 02:43:40
75,Sub-190,Donnas OUT,Time Spent in Donnas,0 days 02:18:11,0 days 01:56:51
77,Sub-190,Gressoney IN,Stage 3,1 days 03:00:32,1 days 03:19:54
78,Sub-190,Gressoney OUT,Time Spent in Gressoney,0 days 02:30:47,0 days 02:13:32
79,Sub-190,Rifugio Champillon,Stage 4,1 days 23:48:35,1 days 23:41:03
76,Sub-190,FINISH,Stage 4,0 days 22:59:37,0 days 23:08:13

### Who ran too easy or hard at the start?

In [40]:
sub_TOR450_dem_bib_list = list(TOR450_dem['PK'][TOR450_dem['Finish Category'] == 'Sub-160'].unique())

new_bib_list = []
for bib in sub_TOR450_dem_bib_list:
    df = lifebase_bib_df[
                ((lifebase_bib_df['Duration_hours']> 42) &
                (lifebase_bib_df['Lifebase'] == 'Cogne IN') )
    &
                (lifebase_bib_df['PK']== bib)
               ]
    
    new_bib_list.append(df)
df= pd.concat(new_bib_list)
pk_unique = list(df['PK'].unique())

for pk in pk_unique:
    print(lifebase_bib_df[['PK','Lifebase', 'Timestamp', 'Duration_hours']][(lifebase_bib_df['PK'] == pk)  ], '\n', '*'*40,  '\n',)
    print(TOR450_dem[['PK', 'Finish Category', 'Duration_hours']][(TOR450_dem['PK'] == pk)  ], '\n','\n','\n','\n', '*'*40,  '\n',)

                   PK       Lifebase           Timestamp  Duration_hours
680  TOR450_2022_4031          START 2022-09-09 20:00:00             NaN
681  TOR450_2022_4031       Cogne IN 2022-09-11 14:51:44       42.862222
682  TOR450_2022_4031      Cogne OUT 2022-09-11 15:49:52        0.968889
683  TOR450_2022_4031      Donnas IN 2022-09-12 17:49:27       25.993056
684  TOR450_2022_4031     Donnas OUT 2022-09-12 19:04:29        1.250556
685  TOR450_2022_4031   Gressoney IN 2022-09-13 18:30:57       23.441111
686  TOR450_2022_4031  Gressoney OUT 2022-09-13 19:42:29        1.192222
687  TOR450_2022_4031         FINISH 2022-09-16 07:35:50       59.889167
 ****************************************

                  PK Finish Category  Duration_hours
11  TOR450_2022_4031         Sub-160      155.597222



 ****************************************

                   PK       Lifebase           Timestamp  Duration_hours
840  TOR450_2022_4053          START 2022-09-09 20:00:00             NaN
841  TOR450_2022_4053       Cogne IN 2022-09-11 14:27:45       42.462500
842  TOR450_2022_4053      Cogne OUT 2022-09-11 15:06:18        0.642500
843  TOR450_2022_4053      Donnas IN 2022-09-12 12:27:52       21.359444
844  TOR450_2022_4053     Donnas OUT 2022-09-12 13:44:45        1.281389
845  TOR450_2022_4053   Gressoney IN 2022-09-13 14:00:35       24.263889
846  TOR450_2022_4053  Gressoney OUT 2022-09-13 15:44:36        1.733611
847  TOR450_2022_4053         FINISH 2022-09-16 03:48:31       60.065278
 ****************************************

                  PK Finish Category  Duration_hours
77  TOR450_2022_4053         Sub-160      151.808611



 ****************************************

                   PK       Lifebase           Timestamp  Duration_hours
664  TOR450_2022_4029          START 2022-09-09 20:00:00             NaN
665  TOR450_2022_4029       Cogne IN 2022-09-11 15:57:59       43.966389
666  TOR450_2022_4029      Cogne OUT 2022-09-11 16:56:19        0.972222
667  TOR450_2022_4029      Donnas IN 2022-09-12 15:59:40       23.055833
668  TOR450_2022_4029     Donnas OUT 2022-09-12 17:56:14        1.942778
669  TOR450_2022_4029   Gressoney IN 2022-09-13 18:34:21       24.635278
670  TOR450_2022_4029  Gressoney OUT 2022-09-13 20:01:37        1.454444
671  TOR450_2022_4029         FINISH 2022-09-16 03:04:24       55.046389
 ****************************************

                   PK Finish Category  Duration_hours
115  TOR450_2022_4029         Sub-160      151.073333



 ****************************************

                    PK       Lifebase           Timestamp  Duration_hours
4064  TOR450_2024_4162          START 2024-09-06 20:00:00             NaN
4065  TOR450_2024_4162       Cogne IN 2024-09-08 17:22:09       45.369167
4066  TOR450_2024_4162      Cogne OUT 2024-09-08 20:33:08        3.183056
4067  TOR450_2024_4162      Donnas IN 2024-09-09 21:44:30       25.189444
4068  TOR450_2024_4162     Donnas OUT 2024-09-09 22:20:37        0.601944
4069  TOR450_2024_4162   Gressoney IN 2024-09-10 21:33:03       23.207222
4070  TOR450_2024_4162  Gressoney OUT 2024-09-11 00:32:15        2.986667
4071  TOR450_2024_4162         FINISH 2024-09-13 11:08:45       58.608333
 ****************************************

                   PK Finish Category  Duration_hours
144  TOR450_2024_4162         Sub-160      159.145833



 ****************************************

                    PK       Lifebase           Timestamp  Duration_hours
3888  TOR450_2024_4139          START 2024-09-06 20:00:00             NaN
3889  TOR450_2024_4139       Cogne IN 2024-09-08 14:48:03       42.800833
3890  TOR450_2024_4139      Cogne OUT 2024-09-08 15:30:53        0.713889
3891  TOR450_2024_4139      Donnas IN 2024-09-09 16:40:51       25.166111
3892  TOR450_2024_4139     Donnas OUT 2024-09-09 17:17:58        0.618611
3893  TOR450_2024_4139   Gressoney IN 2024-09-10 16:18:24       23.007222
3894  TOR450_2024_4139  Gressoney OUT 2024-09-10 17:32:04        1.227778
3895  TOR450_2024_4139         FINISH 2024-09-13 02:11:04       56.650000
 ****************************************

                   PK Finish Category  Duration_hours
156  TOR450_2024_4139         Sub-160      150.184444



 ****************************************

                    PK       Lifebase           Timestamp  Duration_hours
3480  TOR450_2024_4082          START 2024-09-06 20:00:00             NaN
3481  TOR450_2024_4082       Cogne IN 2024-09-08 16:30:46       44.512778
3482  TOR450_2024_4082      Cogne OUT 2024-09-08 17:47:32        1.279444
3483  TOR450_2024_4082      Donnas IN 2024-09-09 18:24:00       24.607778
3484  TOR450_2024_4082     Donnas OUT 2024-09-09 19:47:33        1.392500
3485  TOR450_2024_4082   Gressoney IN 2024-09-10 20:21:00       24.557500
3486  TOR450_2024_4082  Gressoney OUT 2024-09-10 22:20:26        1.990556
3487  TOR450_2024_4082         FINISH 2024-09-13 11:33:44       61.221667
 ****************************************

                   PK Finish Category  Duration_hours
180  TOR450_2024_4082         Sub-160      159.562222



 ****************************************

                    PK       Lifebase           Timestamp  Duration_hours
3784  TOR450_2024_4124          START 2024-09-06 20:00:00             NaN
3785  TOR450_2024_4124       Cogne IN 2024-09-08 14:31:30       42.525000
3786  TOR450_2024_4124      Cogne OUT 2024-09-08 15:41:12        1.161667
3787  TOR450_2024_4124      Donnas IN 2024-09-09 15:39:31       23.971944
3788  TOR450_2024_4124     Donnas OUT 2024-09-09 16:47:24        1.131389
3789  TOR450_2024_4124   Gressoney IN 2024-09-10 17:10:25       24.383611
3790  TOR450_2024_4124  Gressoney OUT 2024-09-10 18:12:59        1.042778
3791  TOR450_2024_4124         FINISH 2024-09-13 08:23:16       62.171389
 ****************************************

                   PK Finish Category  Duration_hours
226  TOR450_2024_4124         Sub-160      156.387778



 ****************************************

                    PK       Lifebase           Timestamp  Duration_hours
3256  TOR450_2024_4053          START 2024-09-06 20:00:00             NaN
3257  TOR450_2024_4053       Cogne IN 2024-09-08 21:38:39       49.644167
3258  TOR450_2024_4053      Cogne OUT 2024-09-08 22:14:08        0.591389
3259  TOR450_2024_4053      Donnas IN 2024-09-09 22:01:29       23.789167
3260  TOR450_2024_4053     Donnas OUT 2024-09-10 02:50:14        4.812500
3261  TOR450_2024_4053   Gressoney IN 2024-09-10 21:29:07       18.648056
3262  TOR450_2024_4053  Gressoney OUT 2024-09-11 03:24:48        5.928056
3263  TOR450_2024_4053         FINISH 2024-09-13 09:32:18       54.125000
 ****************************************

                   PK Finish Category  Duration_hours
229  TOR450_2024_4053         Sub-160      157.538333



 ****************************************

                    PK       Lifebase           Timestamp  Duration_hours
3368  TOR450_2024_4067          START 2024-09-06 20:00:00             NaN
3369  TOR450_2024_4067       Cogne IN 2024-09-08 16:30:49       44.513611
3370  TOR450_2024_4067      Cogne OUT 2024-09-08 17:47:42        1.281389
3371  TOR450_2024_4067      Donnas IN 2024-09-09 18:24:07       24.606944
3372  TOR450_2024_4067     Donnas OUT 2024-09-09 19:51:55        1.463333
3373  TOR450_2024_4067   Gressoney IN 2024-09-10 20:20:48       24.481389
3374  TOR450_2024_4067  Gressoney OUT 2024-09-10 22:20:54        2.001667
3375  TOR450_2024_4067         FINISH 2024-09-13 11:33:48       61.215000
 ****************************************

                   PK Finish Category  Duration_hours
248  TOR450_2024_4067         Sub-160      159.563333



 ****************************************

                    PK       Lifebase           Timestamp  Duration_hours
4160  TOR450_2024_4175          START 2024-09-06 20:00:00             NaN
4161  TOR450_2024_4175       Cogne IN 2024-09-08 17:26:29       45.441389
4162  TOR450_2024_4175      Cogne OUT 2024-09-08 18:25:25        0.982222
4163  TOR450_2024_4175      Donnas IN 2024-09-09 18:26:52       24.024167
4164  TOR450_2024_4175     Donnas OUT 2024-09-09 19:39:45        1.214722
4165  TOR450_2024_4175   Gressoney IN 2024-09-10 20:20:51       24.685000
4166  TOR450_2024_4175  Gressoney OUT 2024-09-10 22:20:39        1.996667
4167  TOR450_2024_4175         FINISH 2024-09-13 11:33:47       61.218889
 ****************************************

                   PK Finish Category  Duration_hours
250  TOR450_2024_4175         Sub-160      159.563056



 ****************************************

                    PK       Lifebase           Timestamp  Duration_hours
2944  TOR450_2024_4010          START 2024-09-06 20:00:00             NaN
2945  TOR450_2024_4010       Cogne IN 2024-09-08 14:28:45       42.479167
2946  TOR450_2024_4010      Cogne OUT 2024-09-08 16:53:31        2.412778
2947  TOR450_2024_4010      Donnas IN 2024-09-09 16:12:48       23.321389
2948  TOR450_2024_4010     Donnas OUT 2024-09-09 18:20:22        2.126111
2949  TOR450_2024_4010   Gressoney IN 2024-09-10 19:06:28       24.768333
2950  TOR450_2024_4010  Gressoney OUT 2024-09-10 22:07:51        3.023056
2951  TOR450_2024_4010         FINISH 2024-09-13 07:21:59       57.235556
 ****************************************

                   PK Finish Category  Duration_hours
266  TOR450_2024_4010         Sub-160      155.366389



 ****************************************

                    PK       Lifebase           Timestamp  Duration_hours
3896  TOR450_2024_4140          START 2024-09-06 20:00:00             NaN
3897  TOR450_2024_4140       Cogne IN 2024-09-08 16:26:52       44.447778
3898  TOR450_2024_4140      Cogne OUT 2024-09-08 18:00:19        1.557500
3899  TOR450_2024_4140      Donnas IN 2024-09-09 18:25:49       24.425000
3900  TOR450_2024_4140     Donnas OUT 2024-09-09 19:43:24        1.293056
3901  TOR450_2024_4140   Gressoney IN 2024-09-10 18:54:13       23.180278
3902  TOR450_2024_4140  Gressoney OUT 2024-09-10 20:17:32        1.388611
3903  TOR450_2024_4140         FINISH 2024-09-13 11:08:43       62.853056
 ****************************************

                   PK Finish Category  Duration_hours
277  TOR450_2024_4140         Sub-160      159.145278



 ****************************************

                    PK       Lifebase           Timestamp  Duration_hours
4224  TOR450_2024_4183          START 2024-09-06 20:00:00             NaN
4225  TOR450_2024_4183       Cogne IN 2024-09-08 17:59:11       45.986389
4226  TOR450_2024_4183      Cogne OUT 2024-09-08 19:27:21        1.469444
4227  TOR450_2024_4183      Donnas IN 2024-09-09 19:26:41       23.988889
4228  TOR450_2024_4183     Donnas OUT 2024-09-09 22:06:03        2.656111
4229  TOR450_2024_4183   Gressoney IN 2024-09-10 20:04:17       21.970556
4230  TOR450_2024_4183  Gressoney OUT 2024-09-10 23:10:24        3.101944
4231  TOR450_2024_4183         FINISH 2024-09-13 11:58:59       60.809722
 ****************************************

                   PK Finish Category  Duration_hours
281  TOR450_2024_4183         Sub-160      159.983056



 ****************************************

                  PK       Lifebase           Timestamp  Duration_hours
32  TOR450_2021_4006          START 2021-09-10 20:00:00             NaN
33  TOR450_2021_4006       Cogne IN 2021-09-12 14:12:11       42.203056
34  TOR450_2021_4006      Cogne OUT 2021-09-12 14:49:02        0.614167
35  TOR450_2021_4006      Donnas IN 2021-09-13 14:17:16       23.470556
36  TOR450_2021_4006     Donnas OUT 2021-09-13 14:40:35        0.388611
37  TOR450_2021_4006   Gressoney IN 2021-09-14 15:57:28       25.281389
38  TOR450_2021_4006  Gressoney OUT 2021-09-14 16:09:43        0.204167
39  TOR450_2021_4006         FINISH 2021-09-17 07:06:55       62.953333
 ****************************************

                   PK Finish Category  Duration_hours
509  TOR450_2021_4006         Sub-160      155.115278



 ****************************************

                   PK       Lifebase           Timestamp  Duration_hours
176  TOR450_2021_4027          START 2021-09-10 20:00:00             NaN
177  TOR450_2021_4027       Cogne IN 2021-09-12 16:39:13       44.653611
178  TOR450_2021_4027      Cogne OUT 2021-09-12 17:25:44        0.775278
179  TOR450_2021_4027      Donnas IN 2021-09-13 16:02:40       22.615556
180  TOR450_2021_4027     Donnas OUT 2021-09-13 17:18:28        1.263333
181  TOR450_2021_4027   Gressoney IN                 NaT             NaN
182  TOR450_2021_4027  Gressoney OUT 2021-09-14 19:17:35             NaN
183  TOR450_2021_4027         FINISH 2021-09-17 10:24:23       63.113333
 ****************************************

                   PK Finish Category  Duration_hours
510  TOR450_2021_4027         Sub-160      158.406389



 ****************************************

                  PK       Lifebase           Timestamp  Duration_hours
64  TOR450_2021_4011          START 2021-09-10 20:00:00             NaN
65  TOR450_2021_4011       Cogne IN 2021-09-12 16:44:18       44.738333
66  TOR450_2021_4011      Cogne OUT 2021-09-12 17:52:42        1.140000
67  TOR450_2021_4011      Donnas IN 2021-09-13 17:15:40       23.382778
68  TOR450_2021_4011     Donnas OUT 2021-09-13 21:40:12        4.408889
69  TOR450_2021_4011   Gressoney IN 2021-09-14 18:38:19       20.968611
70  TOR450_2021_4011  Gressoney OUT 2021-09-14 19:36:00        0.961389
71  TOR450_2021_4011         FINISH 2021-09-17 10:45:14       63.153889
 ****************************************

                   PK Finish Category  Duration_hours
518  TOR450_2021_4011         Sub-160      158.753889



 ****************************************

In [47]:
sub_TOR450_dem_bib_list = list(TOR450_dem['PK'][TOR450_dem['Finish Category'] == 'Sub-180'].unique())

new_bib_list = []
for bib in sub_TOR450_dem_bib_list:
    df = lifebase_bib_df[
                ((lifebase_bib_df['Duration_hours']< 50) &
                (lifebase_bib_df['Lifebase'] == 'Cogne IN') ) &
                (lifebase_bib_df['PK']== bib)]
    new_bib_list.append(df)
    
df= pd.concat(new_bib_list)

pk_unique = list(df['PK'].unique())

for pk in pk_unique:
    print(lifebase_bib_df[['PK',  'Lifebase', 'Duration_hours']][(lifebase_bib_df['PK'] == pk)  ], '\n', '\n',)
    print(TOR450_dem[['PK', 'Finish Category', 'Duration_hours']][(TOR450_dem['PK'] == pk)  ], '\n', '*'*40,  '\n',)

                   PK       Lifebase  Duration_hours
512  TOR450_2022_4010          START             NaN
513  TOR450_2022_4010       Cogne IN       46.647778
514  TOR450_2022_4010      Cogne OUT        1.808056
515  TOR450_2022_4010      Donnas IN       24.323056
516  TOR450_2022_4010     Donnas OUT        4.277222
517  TOR450_2022_4010   Gressoney IN       21.546667
518  TOR450_2022_4010  Gressoney OUT        4.308333
519  TOR450_2022_4010         FINISH       69.338889


                  PK Finish Category  Duration_hours
31  TOR450_2022_4010         Sub-180          172.25
 ****************************************

                    PK       Lifebase  Duration_hours
1352  TOR450_2022_4124          START             NaN
1353  TOR450_2022_4124       Cogne IN       47.401389
1354  TOR450_2022_4124      Cogne OUT        4.557500
1355  TOR450_2022_4124      Donnas IN       23.230556
1356  TOR450_2022_4124     Donnas OUT        6.508333
1357  TOR450_2022_4124   Gressoney IN       22.058611
1358  TOR450_2022_4124  Gressoney OUT        3.624167
1359  TOR450_2022_4124         FINISH       66.771667


                  PK Finish Category  Duration_hours
40  TOR450_2022_4124         Sub-180      174.152222
 ****************************************

                    PK       Lifebase  Duration_hours
1272  TOR450_2022_4114          START             NaN
1273  TOR450_2022_4114       Cogne IN       49.892222
1274  TOR450_2022_4114      Cogne OUT        1.035278
1275  TOR450_2022_4114      Donnas IN       25.491111
1276  TOR450_2022_4114     Donnas OUT        4.057500
1277  TOR450_2022_4114   Gressoney IN       26.591667
1278  TOR450_2022_4114  Gressoney OUT        2.750000
1279  TOR450_2022_4114         FINISH       70.113056


                  PK Finish Category  Duration_hours
71  TOR450_2022_4114         Sub-180      179.930833
 ****************************************

                    PK       Lifebase  Duration_hours
1224  TOR450_2022_4108          START             NaN
1225  TOR450_2022_4108       Cogne IN       48.715278
1226  TOR450_2022_4108      Cogne OUT        1.908333
1227  TOR450_2022_4108      Donnas IN       25.762778
1228  TOR450_2022_4108     Donnas OUT        3.236667
1229  TOR450_2022_4108   Gressoney IN       28.419444
1230  TOR450_2022_4108  Gressoney OUT        2.003333
1231  TOR450_2022_4108         FINISH       63.303889


                   PK Finish Category  Duration_hours
131  TOR450_2022_4108         Sub-180      173.349722
 ****************************************

                    PK       Lifebase  Duration_hours
3856  TOR450_2024_4134          START             NaN
3857  TOR450_2024_4134       Cogne IN       48.444722
3858  TOR450_2024_4134      Cogne OUT        3.356944
3859  TOR450_2024_4134      Donnas IN       26.811667
3860  TOR450_2024_4134     Donnas OUT        1.561111
3861  TOR450_2024_4134   Gressoney IN       26.498611
3862  TOR450_2024_4134  Gressoney OUT        3.805000
3863  TOR450_2024_4134         FINISH       63.050556


                   PK Finish Category  Duration_hours
153  TOR450_2024_4134         Sub-180      173.528611
 ****************************************

                    PK       Lifebase  Duration_hours
3160  TOR450_2024_4040          START             NaN
3161  TOR450_2024_4040       Cogne IN       45.570556
3162  TOR450_2024_4040      Cogne OUT        2.054722
3163  TOR450_2024_4040      Donnas IN       26.771389
3164  TOR450_2024_4040     Donnas OUT        3.011667
3165  TOR450_2024_4040   Gressoney IN       27.315556
3166  TOR450_2024_4040  Gressoney OUT        2.948611
3167  TOR450_2024_4040         FINISH       71.157500


                   PK Finish Category  Duration_hours
159  TOR450_2024_4040         Sub-180          178.83
 ****************************************

                    PK       Lifebase  Duration_hours
4072  TOR450_2024_4163          START             NaN
4073  TOR450_2024_4163       Cogne IN       48.725833
4074  TOR450_2024_4163      Cogne OUT        1.796667
4075  TOR450_2024_4163      Donnas IN       27.887500
4076  TOR450_2024_4163     Donnas OUT        1.778333
4077  TOR450_2024_4163   Gressoney IN       24.785833
4078  TOR450_2024_4163  Gressoney OUT        2.465556
4079  TOR450_2024_4163         FINISH       63.253889


                   PK Finish Category  Duration_hours
173  TOR450_2024_4163         Sub-180      170.693611
 ****************************************

                    PK       Lifebase  Duration_hours
3064  TOR450_2024_4028          START             NaN
3065  TOR450_2024_4028       Cogne IN       49.073056
3066  TOR450_2024_4028      Cogne OUT        3.604722
3067  TOR450_2024_4028      Donnas IN       23.630278
3068  TOR450_2024_4028     Donnas OUT        2.127778
3069  TOR450_2024_4028   Gressoney IN       27.984444
3070  TOR450_2024_4028  Gressoney OUT        3.674167
3071  TOR450_2024_4028         FINISH       63.753611


                   PK Finish Category  Duration_hours
195  TOR450_2024_4028         Sub-180      173.848056
 ****************************************

                    PK       Lifebase  Duration_hours
4176  TOR450_2024_4177          START             NaN
4177  TOR450_2024_4177       Cogne IN       48.442778
4178  TOR450_2024_4177      Cogne OUT        2.488611
4179  TOR450_2024_4177      Donnas IN       22.833611
4180  TOR450_2024_4177     Donnas OUT        5.278611
4181  TOR450_2024_4177   Gressoney IN       25.549444
4182  TOR450_2024_4177  Gressoney OUT        3.769444
4183  TOR450_2024_4177         FINISH       70.468333


                   PK Finish Category  Duration_hours
220  TOR450_2024_4177         Sub-180      178.830833
 ****************************************

                    PK       Lifebase  Duration_hours
3976  TOR450_2024_4150          START             NaN
3977  TOR450_2024_4150       Cogne IN       46.470000
3978  TOR450_2024_4150      Cogne OUT        2.850000
3979  TOR450_2024_4150      Donnas IN       24.412222
3980  TOR450_2024_4150     Donnas OUT        3.516667
3981  TOR450_2024_4150   Gressoney IN       26.247222
3982  TOR450_2024_4150  Gressoney OUT        4.448333
3983  TOR450_2024_4150         FINISH       70.897222


                   PK Finish Category  Duration_hours
227  TOR450_2024_4150         Sub-180      178.841667
 ****************************************

                    PK       Lifebase  Duration_hours
3552  TOR450_2024_4092          START             NaN
3553  TOR450_2024_4092       Cogne IN       44.918889
3554  TOR450_2024_4092      Cogne OUT        4.525000
3555  TOR450_2024_4092      Donnas IN       25.298611
3556  TOR450_2024_4092     Donnas OUT             NaN
3557  TOR450_2024_4092   Gressoney IN             NaN
3558  TOR450_2024_4092  Gressoney OUT        4.201667
3559  TOR450_2024_4092         FINISH       70.517778


                   PK Finish Category  Duration_hours
235  TOR450_2024_4092         Sub-180      178.832222
 ****************************************

                    PK       Lifebase  Duration_hours
4104  TOR450_2024_4167          START             NaN
4105  TOR450_2024_4167       Cogne IN       46.851944
4106  TOR450_2024_4167      Cogne OUT        4.008889
4107  TOR450_2024_4167      Donnas IN       22.520833
4108  TOR450_2024_4167     Donnas OUT        2.336389
4109  TOR450_2024_4167   Gressoney IN       29.223889
4110  TOR450_2024_4167  Gressoney OUT        5.331944
4111  TOR450_2024_4167         FINISH       68.211667


                   PK Finish Category  Duration_hours
289  TOR450_2024_4167         Sub-180      178.485556
 ****************************************

                    PK       Lifebase  Duration_hours
3120  TOR450_2024_4035          START             NaN
3121  TOR450_2024_4035       Cogne IN       46.640000
3122  TOR450_2024_4035      Cogne OUT        1.080278
3123  TOR450_2024_4035      Donnas IN       26.314444
3124  TOR450_2024_4035     Donnas OUT        2.206111
3125  TOR450_2024_4035   Gressoney IN       24.848333
3126  TOR450_2024_4035  Gressoney OUT        3.510833
3127  TOR450_2024_4035         FINISH       70.617500


                   PK Finish Category  Duration_hours
301  TOR450_2024_4035         Sub-180        175.2175
 ****************************************

                   PK       Lifebase  Duration_hours
152  TOR450_2021_4024          START             NaN
153  TOR450_2021_4024       Cogne IN       49.705833
154  TOR450_2021_4024      Cogne OUT        1.696111
155  TOR450_2021_4024      Donnas IN       28.358333
156  TOR450_2021_4024     Donnas OUT        3.200833
157  TOR450_2021_4024   Gressoney IN             NaN
158  TOR450_2021_4024  Gressoney OUT             NaN
159  TOR450_2021_4024         FINISH             NaN


                   PK Finish Category  Duration_hours
504  TOR450_2021_4024         Sub-180        177.6025
 ****************************************

                   PK       Lifebase  Duration_hours
120  TOR450_2021_4019          START             NaN
121  TOR450_2021_4019       Cogne IN       47.491389
122  TOR450_2021_4019      Cogne OUT        3.400000
123  TOR450_2021_4019      Donnas IN       23.796667
124  TOR450_2021_4019     Donnas OUT             NaN
125  TOR450_2021_4019   Gressoney IN             NaN
126  TOR450_2021_4019  Gressoney OUT             NaN
127  TOR450_2021_4019         FINISH             NaN


                   PK Finish Category  Duration_hours
532  TOR450_2021_4019         Sub-180      178.376667
 ****************************************

                  PK       Lifebase  Duration_hours
16  TOR450_2021_4004          START             NaN
17  TOR450_2021_4004       Cogne IN       49.135000
18  TOR450_2021_4004      Cogne OUT        4.459167
19  TOR450_2021_4004      Donnas IN       27.077778
20  TOR450_2021_4004     Donnas OUT        1.743889
21  TOR450_2021_4004   Gressoney IN       24.917778
22  TOR450_2021_4004  Gressoney OUT             NaN
23  TOR450_2021_4004         FINISH             NaN

                   PK Finish Category  Duration_hours
534  TOR450_2021_4004         Sub-180      174.772222
 ****************************************

In [ ]:
# # reading in Raw Data
# races = ['TOR450']
# years = [ 
# #     '2021',
# #         '2022',
# #          '2023', 
#     '2024'
#         ]

# TORX_df = {}

# for race in races:
#     for year in years:
#         df = pd.read_excel(f'{race} Data/1. 100x100trail/{race}_{year}.xlsx',
#                                  dtype={'Start Date': 'string',
#                                         'Year': 'string'})
#         print(f'{race}_{year} {df.shape}')
#         # Store the DataFrame in the dictionary with a key like 'TOR450_2021'
#         TORX_df[f'{race}_{year}'] = df
#     print('*'*50)
    
# TORX_df_concat = pd.concat(TORX_df)
# TOR450 = TORX_df_concat[TORX_df_concat['Year'] == year]

In [ ]:
# sub_TOR450_dem_bib_list = list(TOR450_dem['PK'][TOR450_dem['Finish Category'] == 'Sub-90'].unique())

# new_bib_list = []
# for bib in sub_TOR450_dem_bib_list:
#     df = lifebase_bib_df[
#                 ((lifebase_bib_df['Duration_hours']> 8) &
#                 (lifebase_bib_df['Lifebase'] == 'Valgrisenche OUT') ) &
#                 (lifebase_bib_df['PK']== bib)]
#     new_bib_list.append(df)
    
# df= pd.concat(new_bib_list)

# pk_unique = list(df['PK'].unique())

# for pk in pk_unique:
#     print(lifebase_bib_df[['PK', 'Wave', 'Lifebase', 'Duration_hours']][(lifebase_bib_df['PK'] == pk)  ], '\n', '\n',)
#     print(TOR450_dem[['PK', 'Finish Category', 'Duration_hours']][(TOR450_dem['PK'] == pk)  ], '\n', '*'*40,  '\n',)