In [45]:
import pandas as pd
import numpy as np
import re

In [46]:
race = 'TOR330'

In [47]:
TOR330_itra_2018_2019_including_DNF_df = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_itra_2018_2019_including_DNFs_df.xlsx' )
TOR330_dem = pd.read_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_dem.xlsx' )

In [48]:
TOR330_dem = TOR330_dem[ ['Year', 'Race', 'Name', 'Sex', 'Nationality', 'Category',
       'Status', 'Status1','Duration_seconds','Finish Category']]

In [49]:
TOR330_itra_2018_2019_including_DNF_df[['Race', 'Year', 'Name', 'ITRA_Nationality', 'Sex', 'Age', 'Performance',
       'Performance_Seconds', 'Status', 'Status1']]

,Race,Year,Name,ITRA_Nationality,Sex,Age,Performance,Performance_Seconds,Status,Status1
0,TOR330,2019,Bosatelli Oliviero,ITA,M,50,3 days 00:37:13,261433.0,Finished,Finished
1,TOR330,2019,Reynolds Galen,CAN,M,35,3 days 05:06:12,277572.0,Finished,Finished
2,TOR330,2019,Lantermino Danilo,ITA,M,38,3 days 07:09:46,284986.0,Finished,Finished
3,TOR330,2019,Erwee Tiaan,RSA,M,32,3 days 08:18:24,289104.0,Finished,Finished
4,TOR330,2019,Lukas Jens,GER,M,53,3 days 13:04:04,306244.0,Finished,Finished
...,...,...,...,...,...,...,...,...,...,...
1815,TOR330,2018,Zdon Bill,USA,M,33,NaT,NaN,DNF,DNF
1816,TOR330,2018,Zennaro Davide,ITA,M,57,NaT,NaN,DNF,DNF
1817,TOR330,2018,Zimei Andrea,ITA,M,38,NaT,NaN,DNF,DNF
1818,TOR330,2018,Zimmermann Denise,SUI,F,43,NaT,NaN,DNF,DNF
1819,TOR330,2018,Zugna Davide,ITA,M,42,NaT,NaN,DNF,DNF

In [50]:

# Create a new column 'Finish Category'
def categorize_duration(hours):
    if hours < 60:
        return 'Sub-60'
    elif hours <= 150:
        return f'{int(hours // 10) * 10}-{int(hours // 10) * 10+9}'  # Round to nearest 10 up to 150
    else:
        return 'Over-150'
    
# Define the desired order of categories
finish_category_order = [
    'Sub-60', '60-69',
    '70-79','80-89','90-99', '100-109', '110-119', '120-129',
    '130-139', '140-149',  'Over-150']
    
TOR330_itra_2018_2019_including_DNF_df  = TOR330_itra_2018_2019_including_DNF_df .rename(columns={"Performance": "Duration",
                                                    "Performance_Seconds": "Duration_seconds",
                                                    "ITRA_Nationality": "Nationality",
                                                   }) 
TOR330_itra_2018_2019_including_DNF_df ['Status'] = TOR330_itra_2018_2019_including_DNF_df ['Status'].str.replace('Finished', 'Finished at Courmayeur')
TOR330_itra_2018_2019_including_DNF_df ['Status1'] = TOR330_itra_2018_2019_including_DNF_df ['Status'].copy() 

TOR330_itra_2018_2019_including_DNF_df .loc[TOR330_itra_2018_2019_including_DNF_df ['Status1'] == 'Finished at Courmayeur', 'Status'] = 'True'
TOR330_itra_2018_2019_including_DNF_df .loc[TOR330_itra_2018_2019_including_DNF_df ['Status1'] == 'DNF', 'Status'] = 'False'

# Convert to timedelta and get total hours (handling NaT)
TOR330_itra_2018_2019_including_DNF_df ['Duration_hours'] = pd.to_timedelta(
    TOR330_itra_2018_2019_including_DNF_df ['Duration'], errors='coerce'
).dt.total_seconds() / 3600  # Convert seconds to hours



TOR330_itra_2018_2019_including_DNF_df ['Finish Category'] = TOR330_itra_2018_2019_including_DNF_df ['Duration_hours'].apply(categorize_duration)


# Set 'Finish Category' as a categorical column with the defined order
TOR330_itra_2018_2019_including_DNF_df ['Finish Category'] = pd.Categorical(
    TOR330_itra_2018_2019_including_DNF_df ['Finish Category'],
    categories = finish_category_order,
    ordered = True
)

In [51]:
def categorize_age(age):
    if age < 40: # under40
        return 'SEN'
    elif age < 50: #40-49
        return 'V1'
    elif age < 60: #50-59
        return 'V2'
    elif age < 70: #60-69
        return 'V3'
    elif age >= 70:
        return 'V4' # Over 70
    else:
        return '-'

TOR330_itra_2018_2019_including_DNF_df.loc[TOR330_itra_2018_2019_including_DNF_df['Status1'] == 'True', 'Status1']  = 'Finished at Courmayeur'

TOR330_itra_2018_2019_including_DNF_df.loc[TOR330_itra_2018_2019_including_DNF_df['Status1'] == 'False', 'Status1']  = 'DNFs'

In [52]:
TOR330_itra_2018_2019_including_DNF_df['Age'] = TOR330_itra_2018_2019_including_DNF_df['Age'].str.replace('-', '0')
TOR330_itra_2018_2019_including_DNF_df['Age'] = TOR330_itra_2018_2019_including_DNF_df['Age'].astype(int)

In [57]:
TOR330_itra_2018_2019_including_DNF_df ['Category'] = TOR330_itra_2018_2019_including_DNF_df['Age'].apply(categorize_age)

TOR330_itra_2018_2019_including_DNF_df  = TOR330_itra_2018_2019_including_DNF_df [[
    'Race','Year',  'Name',  'Sex', 'Nationality','Category',
       'Status', 'Status1',  'Duration_hours', 'Duration_seconds', 'Finish Category']]

TOR330_itra_2018_2019_including_DNF_df.head()

,Race,Year,Name,Sex,Nationality,Category,Status,Status1,Duration_hours,Duration_seconds,Finish Category
0,TOR330,2019,Bosatelli Oliviero,M,ITA,V2,True,Finished at Courmayeur,72.620278,261433.0,70-79
1,TOR330,2019,Reynolds Galen,M,CAN,SEN,True,Finished at Courmayeur,77.103333,277572.0,70-79
2,TOR330,2019,Lantermino Danilo,M,ITA,SEN,True,Finished at Courmayeur,79.162778,284986.0,70-79
3,TOR330,2019,Erwee Tiaan,M,RSA,SEN,True,Finished at Courmayeur,80.306667,289104.0,80-89
4,TOR330,2019,Lukas Jens,M,GER,V2,True,Finished at Courmayeur,85.067778,306244.0,80-89

In [61]:

# Mapping of 3-letter to 2-letter country codes
country_mapping = {
    ' ITA': 'IT', ' CAN': 'CA', ' RSA': 'ZA', ' GER': 'DE', ' ESP': 'ES', ' ROU': 'RO', ' FRA': 'FR', ' USA': 'US',
    ' GBR': 'GB', ' FIN': 'FI', ' CZE': 'CZ', ' CHN': 'CN', ' JPN': 'JP', ' CRO': 'HR', ' NOR': 'NO', ' BEL': 'BE',
    ' SUI': 'CH', ' COL': 'CO', ' AUS': 'AU', ' POR': 'PT', ' UKR': 'UA', ' HUN': 'HU', ' SLO': 'SI', ' SWE': 'SE',
    ' ISL': 'IS', ' BUL': 'BG', ' ARG': 'AR', ' MEX': 'MX', ' CRC': 'CR', ' NED': 'NL', ' IND': 'IN', ' NZL': 'NZ',
    ' DEN': 'DK', ' ECU': 'EC', ' BRA': 'BR', ' LTU': 'LT', ' TUR': 'TR', ' POL': 'PL', ' TPE': 'TW', ' SRB': 'RS',
    ' GRE': 'GR', ' AND': 'AD', ' SVK': 'SK', ' KOR': 'KR', ' RUS': 'RU', ' AUT': 'AT', ' MAS': 'MY', ' PHI': 'PH',
    ' SGP': 'SG', ' KEN': 'KE', ' HKG': 'HK', ' CHE': 'CH', ' MAC': 'MO', ' LBN': 'LB', ' THA': 'TH', ' INA': 'ID',
    ' MAD': 'MG', ' VIE': 'VN', ' IRL': 'IE', ' MDA': 'MD', ' CHI': 'CL', ' MON': 'MC', ' URU': 'UY', ' QAT': 'QA',
    ' PER': 'PE', ' MNE': 'ME', ' LUX': 'LU', ' ESA': 'SV', ' ISR': 'IL', ' BRU': 'BN', ' AFG': 'AF'
}

# Apply the mapping
TOR330_itra_2018_2019_including_DNF_df['Nationality'] = TOR330_itra_2018_2019_including_DNF_df['Nationality'].replace(country_mapping)

# Display updated DataFrame
print(TOR330_itra_2018_2019_including_DNF_df)

        Race  Year                Name Sex Nationality Category Status  \
0     TOR330  2019  Bosatelli Oliviero   M          IT       V2   True
1     TOR330  2019      Reynolds Galen   M          CA      SEN   True
2     TOR330  2019   Lantermino Danilo   M          IT      SEN   True
3     TOR330  2019         Erwee Tiaan   M          ZA      SEN   True
4     TOR330  2019          Lukas Jens   M          DE       V2   True
...      ...   ...                 ...  ..         ...      ...    ...
1815  TOR330  2018           Zdon Bill   M          US      SEN  False
1816  TOR330  2018      Zennaro Davide   M          IT       V2  False
1817  TOR330  2018        Zimei Andrea   M          IT      SEN  False
1818  TOR330  2018   Zimmermann Denise   F          CH       V1  False
1819  TOR330  2018        Zugna Davide   M          IT       V1  False

                     Status1  Duration_hours  Duration_seconds Finish Category
0     Finished at Courmayeur       72.620278          261433.0           70-79
1     Finished at Courmayeur       77.103333          277572.0           70-79
2     Finished at Courmayeur       79.162778          284986.0           70-79
3     Finished at Courmayeur       80.306667          289104.0           80-89
4     Finished at Courmayeur       85.067778          306244.0           80-89
...                      ...             ...               ...             ...
1815                     DNF             NaN               NaN        Over-150
1816                     DNF             NaN               NaN        Over-150
1817                     DNF             NaN               NaN        Over-150
1818                     DNF             NaN               NaN        Over-150
1819                     DNF             NaN               NaN        Over-150

[1820 rows x 11 columns]

C:\Users\Karina\AppData\Local\Temp\ipykernel_12148\1947035403.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TOR330_itra_2018_2019_including_DNF_df['Nationality'] = TOR330_itra_2018_2019_including_DNF_df['Nationality'].replace(country_mapping)

In [62]:
for nationality in TOR330_itra_2018_2019_including_DNF_df['Nationality'].unique():
    if len(nationality) !=2:
        print(nationality)
#         print(f'TOR330_itra_2018_2019_including_DNF_df.loc[TOR330_itra_2018_2019_including_DNF_df[\'Nationality\'] == \'{nationality}\', \'Nationality\'] == \'\'')

In [68]:
TOR330_dem['Year'] =TOR330_dem['Year'].astype(str)
TOR330_itra_2018_2019_including_DNF_df['Year'] =TOR330_itra_2018_2019_including_DNF_df['Year'].astype(str)

C:\Users\Karina\AppData\Local\Temp\ipykernel_12148\849963526.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TOR330_itra_2018_2019_including_DNF_df['Year'] =TOR330_itra_2018_2019_including_DNF_df['Year'].astype(str)

In [70]:
TOR330_itra_2018_2019_including_DNF_df['Year'].unique()

array(['2019', '2018'], dtype=object)

In [71]:
# Concatenate along columns (axis=1)
TOR330_dem_2018_2024 = pd.concat([TOR330_dem, TOR330_itra_2018_2019_including_DNF_df])

# Set 'Finish Category' as a categorical column with the defined order
TOR330_dem_2018_2024['Year'] = pd.Categorical(
    TOR330_dem_2018_2024['Year'],
    categories = ['2018','2019',  '2021', '2022', '2023', '2024'],
    ordered = True
)


TOR330_dem_2018_2024['Year'].unique()

['2021', '2022', '2023', '2024', '2019', '2018']
Categories (6, object): ['2018' < '2019' < '2021' < '2022' < '2023' < '2024']

In [72]:
n = 0

nationality_df = []
for name in list(TOR330_dem_2018_2024['Name'].unique()):
    name_df = TOR330_dem_2018_2024[TOR330_dem_2018_2024['Name'] == name]
    if len(list(name_df['Year'].unique())) == 1:
#         print(name_df['Name'].unique())
        n = n+1
#         print(n, name_df['Name'].unique(), name_df['Nationality'].unique())
        nationality_df.append(name_df)
    else:
        name_df.loc[name_df['Year'] == '2019', 'Nationality'] = np.nan
        name_df['Nationality'] = name_df['Nationality'].bfill()
        nationality_df.append(name_df)
        
TOR330_dem_2018_2024_1= pd.concat(nationality_df)

TOR330_dem_2018_2024_1[TOR330_dem_2018_2024_1['Name'] == 'Papi Luca'].reset_index(drop = True)

C:\Users\Karina\AppData\Local\Temp\ipykernel_12148\1754007779.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name_df['Nationality'] = name_df['Nationality'].bfill()

['Jonas Russi']
1 ['Jonas Russi'] ['CH']
['Restorp Petter']
2 ['Restorp Petter'] ['FR']
['Lucas Jerome']
3 ['Lucas Jerome'] ['FR']
['Bethaz Marco']
4 ['Bethaz Marco'] ['IT']
['Bolis Matteo']
5 ['Bolis Matteo'] ['IT']
['Corneliu Buliga']
6 ['Corneliu Buliga'] ['RO']
['Laving Jean Marc']
7 ['Laving Jean Marc'] ['FR']
['Beaven Alexander']
8 ['Beaven Alexander'] ['GB']
['Christin Benoit Julien']
9 ['Christin Benoit Julien'] ['FR']
['Dunkerbeck Thomas']
10 ['Dunkerbeck Thomas'] ['NL']
['Roncato Alessandro']
11 ['Roncato Alessandro'] ['IT']
['Caffier Arthur']
12 ['Caffier Arthur'] ['ES']
['Poriel Yannick']
13 ['Poriel Yannick'] ['FR']
['Duclos Guillaume']
14 ['Duclos Guillaume'] ['FR']
['Tobias Bogner']
15 ['Tobias Bogner'] ['AT']
['Champigny Julien']
16 ['Champigny Julien'] ['FR']
['Hewitt Michael']
17 ['Hewitt Michael'] ['US']
['Orradre Inigo']
18 ['Orradre Inigo'] ['ES']
['Vieira Nelson']
19 ['Vieira Nelson'] ['PT']
['Poskin Julien']
20 ['Poskin Julien'] ['BE']
['Hetmanski Adam']
21 ['Hetmanski Adam'] ['DE']
['Jose Luis Martinez Fernandez']
22 ['Jose Luis Martinez Fernandez'] ['ES']
['Fernandez Canego Angel']
23 ['Fernandez Canego Angel'] ['ES']
['Mihai Husleag']
24 ['Mihai Husleag'] ['RO']
['Baneras Batlle Sergi']
25 ['Baneras Batlle Sergi'] ['ES']
['Pera Vall Llosera Josep']
26 ['Pera Vall Llosera Josep'] ['ES']
['Cattaneo Andrea']
27 ['Cattaneo Andrea'] ['IT']
['Borbey Sergio']
28 ['Borbey Sergio'] ['IT']
['Pongerard Kevin']
29 ['Pongerard Kevin'] ['FR']
['Pastore Enrico']
30 ['Pastore Enrico'] ['IT']
['Enrione Davide']
31 ['Enrione Davide'] ['IT']
['Santos Nuno']
32 ['Santos Nuno'] ['PT']
['Gregory Marrama']
33 ['Gregory Marrama'] ['FR']
['Petropoulos Nikolaos']
34 ['Petropoulos Nikolaos'] ['GR']
['Williams Eric']
35 ['Williams Eric'] ['US']
['Mousseaux David']
36 ['Mousseaux David'] ['FR']
['Gustafsson Johan']
37 ['Gustafsson Johan'] ['SE']
['Ruiz Velez Domingo']
38 ['Ruiz Velez Domingo'] ['ES']
['Capponi Thomas']
39 ['Capponi Thomas'] ['IT']
['Vidal Salvi Jordi']
40 ['Vidal Salvi Jordi'] ['ES']
['Jacob Tristan']
41 ['Jacob Tristan'] ['FR']
['Santos Julio']
42 ['Santos Julio'] ['ES']
['Bertoni Massimo']
43 ['Bertoni Massimo'] ['IT']
['Veysseyre Gilles']
44 ['Veysseyre Gilles'] ['FR']
['Marina Kollassa']
45 ['Marina Kollassa'] ['DE']
['Saviozzi Francesco']
46 ['Saviozzi Francesco'] ['IT']
['Palma Raphael']
47 ['Palma Raphael'] ['FR']
['Callisardi Giancarlo']
48 ['Callisardi Giancarlo'] ['IT']
['Sebastien Pennazio']
49 ['Sebastien Pennazio'] ['FR']
['Guery Benjamin']
50 ['Guery Benjamin'] ['FR']
['Defecinski Radoslaw']
51 ['Defecinski Radoslaw'] ['PL']
['Favre Stephane']
52 ['Favre Stephane'] ['FR']
['Jonathan Soudy']
53 ['Jonathan Soudy'] ['FR']
['Broquet Xavier']
54 ['Broquet Xavier'] ['FR']
['Montani Alessandro']
55 ['Montani Alessandro'] ['IT']
['Nelson Paul']
56 ['Nelson Paul'] ['GB']
['Trommer Marco']
57 ['Trommer Marco'] ['DE']
['Jongens Willemijn']
58 ['Jongens Willemijn'] ['NL']
['Thiemard Julien']
59 ['Thiemard Julien'] ['CH']
['Peresedov Vladimir']
60 ['Peresedov Vladimir'] ['RU']
['Bertolini Michele']
61 ['Bertolini Michele'] ['IT']
['Tiberiu Useriu']
62 ['Tiberiu Useriu'] ['RO']
['Van Woensel Thomas']
63 ['Van Woensel Thomas'] ['BE']
['Fournier Christophe']
64 ['Fournier Christophe'] ['FR']
['Bougard Valery']
65 ['Bougard Valery'] ['BE']
['Gravot Victor']
66 ['Gravot Victor'] ['FR']
['Higueret Quentin']
67 ['Higueret Quentin'] ['FR']
['Higueret Stephane']
68 ['Higueret Stephane'] ['FR']
['Michaud Andre Paul']
69 ['Michaud Andre Paul'] ['US']
['Bianchini Francesco']
70 ['Bianchini Francesco'] ['IT']
['Aubineau Sebastien']
71 ['Aubineau Sebastien'] ['FR']
['Soma Alessandro']
72 ['Soma Alessandro'] ['IT']
['Imper Christoph']
73 ['Imper Christoph'] ['CH']
['Cattaneo Martino']
74 ['Cattaneo Martino'] ['IT']
['Dentella Federico']
75 ['Dentella Federico'] ['IT']
['Burgin Freddy']
76 ['Burgin Freddy'] ['CH']
['Zoppo Antonio Daniele']
77 ['Zoppo Antonio Daniele'] ['IT']
['Minore Stefano']
78 ['Minore Stefano'] ['IT']
['Mangili Ivo Paolo']
79 ['Mangili Ivo Paolo'] ['IT']
['Bokman Jakob']
80 ['Bokman Jakob'] ['SE']
['Lucas Frost Jonathan']
81 ['Lucas Frost Jonathan'] ['FR']
['Pitzalis Antonio']
82 ['Pitzalis Antonio'] ['IT']
['Rossetti Nicoletta']
83 ['Rossetti Nicoletta'] ['IT']
['Soares Miguel']
84 ['Soares Miguel'] ['PT']
['Curti Paolo']
85 ['Curti Paolo'] ['IT']
['Chambon Nicolas']
86 ['Chambon Nicolas'] ['IT']
['Mischler Simon']
87 ['Mischler Simon'] ['CH']
['Ost Vincent']
88 ['Ost Vincent'] ['BE']
['Montoya Enriquez Marc']
89 ['Montoya Enriquez Marc'] ['ES']
['Alfani Oscar']
90 ['Alfani Oscar'] ['ES']
['Villani Marcello']
91 ['Villani Marcello'] ['IT']
['Le Guern Vincent']
92 ['Le Guern Vincent'] ['FR']
['Alain Fink']
93 ['Alain Fink'] ['BE']
['Adam Eric']
94 ['Adam Eric'] ['AT']
['Vallverdu David']
95 ['Vallverdu David'] ['ES']
['Zanotti Andrea']
96 ['Zanotti Andrea'] ['IT']
['Iancu David']
97 ['Iancu David'] ['RO']
['Manse Lilian']
98 ['Manse Lilian'] ['FR']
['Carminati Marco']
99 ['Carminati Marco'] ['IT']
['Hansueli Motteli']
100 ['Hansueli Motteli'] ['CH']
['Crotti Federico']
101 ['Crotti Federico'] ['IT']
['Lombard Fabrizio']
102 ['Lombard Fabrizio'] ['IT']
['Stirling Timothy']
103 ['Stirling Timothy'] ['CH']
['Laney Tim']
104 ['Laney Tim'] ['GB']
['Lata Ievgen']
105 ['Lata Ievgen'] ['UA']
['Munck Bertrand']
106 ['Munck Bertrand'] ['FR']
['Nnoruka Samuel']
107 ['Nnoruka Samuel'] ['FR']
['Clark Stephen']
108 ['Clark Stephen'] ['CH']
['Malgarini Matteo']
109 ['Malgarini Matteo'] ['IT']
['Willis Sarah']
110 ['Willis Sarah'] ['NL']
['Catti Lorenzo']
111 ['Catti Lorenzo'] ['IT']
['Rios Pita Ezequiel']
112 ['Rios Pita Ezequiel'] ['BR']
['Guffon Alain']
113 ['Guffon Alain'] ['FR']
['Campuzano Izquierdo Francisco']
114 ['Campuzano Izquierdo Francisco'] ['ES']
['Lopinet Marc']
115 ['Lopinet Marc'] ['FR']
['Galassi Andrea']
116 ['Galassi Andrea'] ['IT']
['Beynel Florence']
117 ['Beynel Florence'] ['FR']
['Sanchez Del Pino Antonio']
118 ['Sanchez Del Pino Antonio'] ['ES']
['Aceituno Azaustre Antonio']
119 ['Aceituno Azaustre Antonio'] ['ES']
['Ducher Ludovic']
120 ['Ducher Ludovic'] ['ES']
['Lafay Elodie']
121 ['Lafay Elodie'] ['FR']
['Folliot Sebastien']
122 ['Folliot Sebastien'] ['FR']
['Forzani Adriano']
123 ['Forzani Adriano'] ['IT']
['Gueudre Guillaume']
124 ['Gueudre Guillaume'] ['FR']
['Garcia Busto Eduardo']
125 ['Garcia Busto Eduardo'] ['ES']
['Grondona Pietro']
126 ['Grondona Pietro'] ['IT']
['Roncagliolo Federico']
127 ['Roncagliolo Federico'] ['IT']
['Kinsbergen Robin']
128 ['Kinsbergen Robin'] ['NL']
['Barbieri Ranieri Brook']
129 ['Barbieri Ranieri Brook'] ['IT']
['Sanson Antony']
130 ['Sanson Antony'] ['FR']
['Szramowiat Marek']
131 ['Szramowiat Marek'] ['PL']
['Saint Joly Chloe']
132 ['Saint Joly Chloe'] ['FR']
['Jensen Kristian Vestergaard']
133 ['Jensen Kristian Vestergaard'] ['DK']
['Espie Laurent']
134 ['Espie Laurent'] ['FR']
['Yann Richard']
135 ['Yann Richard'] ['FR']
['Fortin Pierre Luc']
136 ['Fortin Pierre Luc'] ['CA']
['Miniggio Nicolas']
137 ['Miniggio Nicolas'] ['FR']
['Fages Perrine']
138 ['Fages Perrine'] ['SA']
['Warchol Alexandre']
139 ['Warchol Alexandre'] ['FR']
['Doffin Yann']
140 ['Doffin Yann'] ['FR']
['Boggess Jeff']
141 ['Boggess Jeff'] ['US']
['Roux Sebastien']
142 ['Roux Sebastien'] ['FR']
['Pupaza Ciprian']
143 ['Pupaza Ciprian'] ['IT']
['Bosio Walter']
144 ['Bosio Walter'] ['IT']
['De Biase Anna']
145 ['De Biase Anna'] ['IT']
['Cestino Saez Enrique']
146 ['Cestino Saez Enrique'] ['ES']
['Arbel Yannick']
147 ['Arbel Yannick'] ['CH']
['Morneau Steve']
148 ['Morneau Steve'] ['CA']
['Marcus Weber']
149 ['Marcus Weber'] ['DE']
['Liegeois David']
150 ['Liegeois David'] ['BE']
['Davison Ted']
151 ['Davison Ted'] ['US']
['Negri Mattia']
152 ['Negri Mattia'] ['IT']
['Domont Laurent']
153 ['Domont Laurent'] ['FR']
['Daguet Vincent']
154 ['Daguet Vincent'] ['FR']
['Beauval Alex']
155 ['Beauval Alex'] ['CH']
['Doblinger Reinhold']
156 ['Doblinger Reinhold'] ['AT']
['Gantie Cedric']
157 ['Gantie Cedric'] ['FR']
['Breysse Christian']
158 ['Breysse Christian'] ['FR']
['Tassone Enzo']
159 ['Tassone Enzo'] ['IT']
['Melchiorri Marco']
160 ['Melchiorri Marco'] ['IT']
['Berthoud Benoit']
161 ['Berthoud Benoit'] ['FR']
['Dominique Meynadier']
162 ['Dominique Meynadier'] ['FR']
['Pickett Brian']
163 ['Pickett Brian'] ['US']
['Laenen Maxim']
164 ['Laenen Maxim'] ['BE']
['Valcke Mathias']
165 ['Valcke Mathias'] ['BE']
['Boschetti Lisa']
166 ['Boschetti Lisa'] ['CH']
['Bernardoni Stefano']
167 ['Bernardoni Stefano'] ['CH']

['Soriano Guerrero Pedro']
168 ['Soriano Guerrero Pedro'] ['ES']
['Bouyer Fabien']
169 ['Bouyer Fabien'] ['FR']
['Banu Ovidiu']
170 ['Banu Ovidiu'] ['FR']
['Valverde Andres']
171 ['Valverde Andres'] ['ES']
['Vinaixa Ricard']
172 ['Vinaixa Ricard'] ['ES']
['Giannetti Stefano']
173 ['Giannetti Stefano'] ['IT']
['Corsini Valerio']
174 ['Corsini Valerio'] ['IT']
['Vincent Mengin']
175 ['Vincent Mengin'] ['FR']
['Veyres Dominique']
176 ['Veyres Dominique'] ['FR']
['Soulier Jerome']
177 ['Soulier Jerome'] ['FR']
['Peccavet Stephane']
178 ['Peccavet Stephane'] ['FR']
['Christophe Dietrich']
179 ['Christophe Dietrich'] ['FR']
['Galassi Cristina']
180 ['Galassi Cristina'] ['IT']
['Patrick Langelot']
181 ['Patrick Langelot'] ['FR']
['Lemaire Gwennael']
182 ['Lemaire Gwennael'] ['FR']
['Ingargiola Olivier']
183 ['Ingargiola Olivier'] ['FR']
['Thivolle Geraldine']
184 ['Thivolle Geraldine'] ['FR']
['Endstra Tom']
185 ['Endstra Tom'] ['NL']
['Ordas Enrique']
186 ['Ordas Enrique'] ['ES']
['Howard George']
187 ['Howard George'] ['GB']
['Mehl Lisa']
188 ['Mehl Lisa'] ['DE']
['Feinhaus Dima']
189 ['Feinhaus Dima'] ['US']
['Blondeau Marc']
190 ['Blondeau Marc'] ['FR']
['Leonelli Daniele']
191 ['Leonelli Daniele'] ['IT']
['Olcot Edward']
192 ['Olcot Edward'] ['GB']
['Danne Nicolas']
193 ['Danne Nicolas'] ['CA']
['Nicolas Romain']
194 ['Nicolas Romain'] ['FR']
['Bassi Lorenzo']
195 ['Bassi Lorenzo'] ['IT']
['Nicolas Tremaudeux']
196 ['Nicolas Tremaudeux'] ['FR']
['Rzeszotko Marzena']
197 ['Rzeszotko Marzena'] ['PL']
['Rzeszotko Leszek']
198 ['Rzeszotko Leszek'] ['PL']
['Arrighini Luca']
199 ['Arrighini Luca'] ['IT']
['Genovesi Federico']
200 ['Genovesi Federico'] ['IT']
['Jacquemod Mattia']
201 ['Jacquemod Mattia'] ['IT']
['Mosler Anthony']
202 ['Mosler Anthony'] ['FR']
['Picard Eric']
203 ['Picard Eric'] ['FR']
['Pouey Guillaume']
204 ['Pouey Guillaume'] ['FR']
['Jean Yves Waty']
205 ['Jean Yves Waty'] ['FR']
['Lambert Mathieu']
206 ['Lambert Mathieu'] ['CH']
['Zeni Gabriele']
207 ['Zeni Gabriele'] ['IT']
['Grangier Aline']
208 ['Grangier Aline'] ['CH']
['Alves Henrique']
209 ['Alves Henrique'] ['BR']
['Cirla Marco']
210 ['Cirla Marco'] ['IT']
['Chartier Christophe']
211 ['Chartier Christophe'] ['FR']
['De Krijger Peter']
212 ['De Krijger Peter'] ['NL']
['Shota Hanawa']
213 ['Shota Hanawa'] ['JP']
['Nakamura Rika']
214 ['Nakamura Rika'] ['US']
['Rizzi Lucio']
215 ['Rizzi Lucio'] ['IT']
['Van Heerden Tina']
216 ['Van Heerden Tina'] ['CH']
['Jouneau Bertrand']
217 ['Jouneau Bertrand'] ['FR']
['Malo Jean Yves']
218 ['Malo Jean Yves'] ['FR']
['Madrigal Ligia']
219 ['Madrigal Ligia'] ['CR']
['Trafford Andrew']
220 ['Trafford Andrew'] ['IE']
['Darnieaud Romain']
221 ['Darnieaud Romain'] ['FR']
['Garcia Cabello Francisco Jose']
222 ['Garcia Cabello Francisco Jose'] ['ES']
['Ntikiadis Ioannis']
223 ['Ntikiadis Ioannis'] ['GR']
['Castillo Carrascal Paco']
224 ['Castillo Carrascal Paco'] ['ES']
['Abbet Valentin']
225 ['Abbet Valentin'] ['CH']
['Abbet Jean Maurice']
226 ['Abbet Jean Maurice'] ['CH']
['Sandrine Duguay']
227 ['Sandrine Duguay'] ['FR']
['Codina Vallbona Francesc']
228 ['Codina Vallbona Francesc'] ['ES']
['Reati Alessandro']
229 ['Reati Alessandro'] ['IT']
['Picco Fabiano']
230 ['Picco Fabiano'] ['IT']
['Holmes Bill']
231 ['Holmes Bill'] ['US']
['Garelli Giorgio']
232 ['Garelli Giorgio'] ['IT']
['Watteyne Martin']
233 ['Watteyne Martin'] ['BE']
['Salvati Romolo']
234 ['Salvati Romolo'] ['IT']
['Polverelli Francesco']
235 ['Polverelli Francesco'] ['IT']
['Lassus Emmanuel']
236 ['Lassus Emmanuel'] ['FR']
['Webert Jacques']
237 ['Webert Jacques'] ['FR']
['Jegu Corentin']
238 ['Jegu Corentin'] ['FR']
['De Bortoli Andrea Maurilio']
239 ['De Bortoli Andrea Maurilio'] ['IT']
['Cavallari Cristian']
240 ['Cavallari Cristian'] ['IT']
['Fornasier Fausto']
241 ['Fornasier Fausto'] ['IT']
['Ribeiro Luis']
242 ['Ribeiro Luis'] ['PT']
['Nicolia Tiziana']
243 ['Nicolia Tiziana'] ['IT']
['Fabrice Gueriot']
244 ['Fabrice Gueriot'] ['FR']
['Zanzottera Guido']
245 ['Zanzottera Guido'] ['IT']
['Matthiasdottir Proppe Halldora']
246 ['Matthiasdottir Proppe Halldora'] ['IS']
['Lodigiani Milko']
247 ['Lodigiani Milko'] ['IT']
['Knowles English']
248 ['Knowles English'] ['US']
['Legrand Virginie']
249 ['Legrand Virginie'] ['PF']
['Eric Galea']
250 ['Eric Galea'] ['FR']
['Nuzzi Pier Francesco']
251 ['Nuzzi Pier Francesco'] ['IT']
['Benjumea Fernandez Francisco']
252 ['Benjumea Fernandez Francisco'] ['ES']
['Hidalgo Vasco Javier']
253 ['Hidalgo Vasco Javier'] ['ES']
['Carmona Marina Jose Fernando']
254 ['Carmona Marina Jose Fernando'] ['ES']
['Bianchetto Stefano']
255 ['Bianchetto Stefano'] ['IT']
['Ricaldone Elena']
256 ['Ricaldone Elena'] ['IT']
['Polotti Diego']
257 ['Polotti Diego'] ['IT']
['Fontana Giusti Giovanni']
258 ['Fontana Giusti Giovanni'] ['IT']
['Reymondaud Frederic']
259 ['Reymondaud Frederic'] ['FR']
['Andersson Flemming']
260 ['Andersson Flemming'] ['DK']
['Alexander Skrzypek']
261 ['Alexander Skrzypek'] ['DE']
['Gambardella Cesare']
262 ['Gambardella Cesare'] ['IT']
['Manoni Giorgio']
263 ['Manoni Giorgio'] ['IT']
['Georgiana Popa']
264 ['Georgiana Popa'] ['RO']
['Scouflaire Helene']
265 ['Scouflaire Helene'] ['FR']
['Pierrick Daniel']
266 ['Pierrick Daniel'] ['FR']
['Henrio Erick']
267 ['Henrio Erick'] ['FR']
['Zanco Roberto']
268 ['Zanco Roberto'] ['IT']
['Cavallo Giuliano']
269 ['Cavallo Giuliano'] ['IT']
['Puntel Fabrizio']
270 ['Puntel Fabrizio'] ['IT']
['Teixeira Armando']
271 ['Teixeira Armando'] ['PT']
['Pelosi Andrea']
272 ['Pelosi Andrea'] ['IT']
['Gazzaniga Andrea']
273 ['Gazzaniga Andrea'] ['IT']
['Griebach Denis']
274 ['Griebach Denis'] ['DE']
['Panic Vladimir']
275 ['Panic Vladimir'] ['RS']
['Coppa Mauro']
276 ['Coppa Mauro'] ['IT']
['Rime Didier']
277 ['Rime Didier'] ['CH']
['Packbier Roman']
278 ['Packbier Roman'] ['NL']
['Savary Gabriel']
279 ['Savary Gabriel'] ['CH']
['Vizzi Erik Nicola']
280 ['Vizzi Erik Nicola'] ['IT']
['Di Trana Marco']
281 ['Di Trana Marco'] ['ES']
['Haag Thomas']
282 ['Haag Thomas'] ['FR']
['Bonhomme Thierry']
283 ['Bonhomme Thierry'] ['FR']
['Secreto Louis']
284 ['Secreto Louis'] ['US']
['Schena Andrea']
285 ['Schena Andrea'] ['IT']
['Williams Kaz']
286 ['Williams Kaz'] ['FR']
['De La Cruz Carlos']
287 ['De La Cruz Carlos'] ['ES']
['Zanon Francesco']
288 ['Zanon Francesco'] ['IT']
['Alvez Barrero Fernando']
289 ['Alvez Barrero Fernando'] ['ES']
['Chaves Narciso']
290 ['Chaves Narciso'] ['PT']
['Hansen Thomas']
291 ['Hansen Thomas'] ['FR']
['Kalmeyer Betsy']
292 ['Kalmeyer Betsy'] ['US']
['Schmidt Michael']
293 ['Schmidt Michael'] ['DE']
['Belardini Gianluca']
294 ['Belardini Gianluca'] ['IT']
['De Vette Ruud']
295 ['De Vette Ruud'] ['NL']
['Rossini Nicola']
296 ['Rossini Nicola'] ['IT']
['Carreras Iacopo']
297 ['Carreras Iacopo'] ['IT']
['Petrella Sandro']
298 ['Petrella Sandro'] ['IT']
['Bonvicini Matteo Paolo']
299 ['Bonvicini Matteo Paolo'] ['IT']
['Lazzaroni Matteo']
300 ['Lazzaroni Matteo'] ['IT']
['Rivas Rivera Alejandro']
301 ['Rivas Rivera Alejandro'] ['ES']
['Rocelli Michele']
302 ['Rocelli Michele'] ['IT']
['Guillou Olivier']
303 ['Guillou Olivier'] ['FR']
['Santi Amantini Valentino']
304 ['Santi Amantini Valentino'] ['IT']
['Cheal Mark']
305 ['Cheal Mark'] ['GB']
['Prest Simon']
306 ['Prest Simon'] ['GB']
['Shevchuk Alena']
307 ['Shevchuk Alena'] ['RU']
['Banh Trong Phuoc']
308 ['Banh Trong Phuoc'] ['FR']
['Bourgeois Antony']
309 ['Bourgeois Antony'] ['FR']
['Arvidsen Jimmy']
310 ['Arvidsen Jimmy'] ['DK']
['Cavallini Giacomo']
311 ['Cavallini Giacomo'] ['IT']
['Isanta Gerard']
312 ['Isanta Gerard'] ['ES']
['Borsos Attila']
313 ['Borsos Attila'] ['HU']
['Ferri Giorgio']
314 ['Ferri Giorgio'] ['IT']
['Dalbard Aline']
315 ['Dalbard Aline'] ['IT']
['Graglia Michele']
316 ['Graglia Michele'] ['US']
['Minoletti Mauro']
317 ['Minoletti Mauro'] ['IT']
['Fugante Massimo']
318 ['Fugante Massimo'] ['IT']
['Caldinelli Luigi']
319 ['Caldinelli Luigi'] ['IT']
['Zavelani Rossi Maria Beatrice']
320 ['Zavelani Rossi Maria Beatrice'] ['IT']
['Suwannachairop Sukthawee']
321 ['Suwannachairop Sukthawee'] ['RS']
['Colleuille Jean']
322 ['Colleuille Jean'] ['FR']
['Welch Tim']
323 ['Welch Tim'] ['GB']
['Favre Roberto']
324 ['Favre Roberto'] ['IT']
['Rasmussen Kim']
325 ['Rasmussen Kim'] ['DK']
['Da Pozzo Bonggi Ricardo']
326 ['Da Pozzo Bonggi Ricardo'] ['FR']

['Ciarla Alberta']
327 ['Ciarla Alberta'] ['IT']
['Chudy Przemyslaw']
328 ['Chudy Przemyslaw'] ['IE']
['Billy Laurent']
329 ['Billy Laurent'] ['FR']
['Schubert Sebastian']
330 ['Schubert Sebastian'] ['DE']
['Schuhmann Marc']
331 ['Schuhmann Marc'] ['FR']
['Serra Garcia Tomas']
332 ['Serra Garcia Tomas'] ['ES']
['Johnson Mark']
333 ['Johnson Mark'] ['US']
['Drouet Thierry']
334 ['Drouet Thierry'] ['FR']
['Boeretto Marco']
335 ['Boeretto Marco'] ['IT']
['Ranieri Fabrizio']
336 ['Ranieri Fabrizio'] ['IT']
['Stringari Guido']
337 ['Stringari Guido'] ['IT']
['Scarlatella Francesco']
338 ['Scarlatella Francesco'] ['IT']
['Fiorentini Francesco']
339 ['Fiorentini Francesco'] ['IT']
['Spenle Jean Martin']
340 ['Spenle Jean Martin'] ['FR']
['Sampaio Joaquim']
341 ['Sampaio Joaquim'] ['PT']
['Mayerhofer Thomas']
342 ['Mayerhofer Thomas'] ['AT']
['Ligasacchi Fabio']
343 ['Ligasacchi Fabio'] ['IT']
['Juang Than']
344 ['Juang Than'] ['TH']
['Banus Pedreny Delia']
345 ['Banus Pedreny Delia'] ['ES']
['Estarellas Toni']
346 ['Estarellas Toni'] ['ES']
['Iannone Alessandro']
347 ['Iannone Alessandro'] ['IT']
['Gemelli Ezio Luigi']
348 ['Gemelli Ezio Luigi'] ['IT']
['Caroline Caumon']
349 ['Caroline Caumon'] ['FR']
['Alain Nogaret']
350 ['Alain Nogaret'] ['FR']
['Bosio 1 Georges']
351 ['Bosio 1 Georges'] ['FR']
['Christian Knapp']
352 ['Christian Knapp'] ['CH']
['D Alessandra Walter']
353 ['D Alessandra Walter'] ['IT']
['Muster Sebastien']
354 ['Muster Sebastien'] ['CH']
['Thomas Ernst']
355 ['Thomas Ernst'] ['CH']
['Michele Flage']
356 ['Michele Flage'] ['FR']
['Meyer Jean Francois']
357 ['Meyer Jean Francois'] ['FR']
['Pellieux Mickael']
358 ['Pellieux Mickael'] ['FR']
['Bosser Jean Luc']
359 ['Bosser Jean Luc'] ['FR']
['Nicolas Bernard']
360 ['Nicolas Bernard'] ['FR']
['Vercellotti Mario']
361 ['Vercellotti Mario'] ['IT']
['Louis Jacquet Olivier']
362 ['Louis Jacquet Olivier'] ['FR']
['Gerald Huet']
363 ['Gerald Huet'] ['FR']
['Dominique Di Vincenzo']
364 ['Dominique Di Vincenzo'] ['FR']
['Jourdan Mikael']
365 ['Jourdan Mikael'] ['FR']
['Meunier Benilde']
366 ['Meunier Benilde'] ['FR']
['Eric Desgeorge']
367 ['Eric Desgeorge'] ['FR']
['Errico Domenico']
368 ['Errico Domenico'] ['IT']
['Quero Guerrero Juan Luis']
369 ['Quero Guerrero Juan Luis'] ['ES']
['Jean Philippe Compan']
370 ['Jean Philippe Compan'] ['FR']
['Barbara Plovier']
371 ['Barbara Plovier'] ['BE']
['Calcagni Donato Antonio']
372 ['Calcagni Donato Antonio'] ['IT']
['Guillaume Adamczyk']
373 ['Guillaume Adamczyk'] ['BE']
['Gouveia E Silva Frederico']
374 ['Gouveia E Silva Frederico'] ['PT']
['Lavie Jean Marc']
375 ['Lavie Jean Marc'] ['FR']
['Le Det Eric']
376 ['Le Det Eric'] ['FR']
['Alain Boillot']
377 ['Alain Boillot'] ['FR']
['Vieira Flavio Duarte']
378 ['Vieira Flavio Duarte'] ['PT']
['Chapellu Michel']
379 ['Chapellu Michel'] ['IT']
['Benoit Clement']
380 ['Benoit Clement'] ['CH']
['Ralf Knodel']
381 ['Ralf Knodel'] ['DE']
['Jerome Marin']
382 ['Jerome Marin'] ['FR']
['Patrick Delikat']
383 ['Patrick Delikat'] ['FR']
['Paul De Man']
384 ['Paul De Man'] ['BE']
['Grenti Filippo']
385 ['Grenti Filippo'] ['IT']
['Mattiato Andrea']
386 ['Mattiato Andrea'] ['IT']
['Gabioud Candide']
387 ['Gabioud Candide'] ['CH']
['Larrotcha Juan Jose']
388 ['Larrotcha Juan Jose'] ['ES']
['Beranger Sandrine']
389 ['Beranger Sandrine'] ['FR']
['Bie Nicolas']
390 ['Bie Nicolas'] ['FR']
['Giraud Sebastien']
391 ['Giraud Sebastien'] ['FR']
['Bodet Maxime']
392 ['Bodet Maxime'] ['FR']
['Woodier Tim']
393 ['Woodier Tim'] ['GB']
['Frankowski Michal']
394 ['Frankowski Michal'] ['PL']
['Pelmoine Laurent']
395 ['Pelmoine Laurent'] ['FR']
['Pourlidas Thomas']
396 ['Pourlidas Thomas'] ['GR']
['Taylor Chris']
397 ['Taylor Chris'] ['GB']
['Tognoni Patrich']
398 ['Tognoni Patrich'] ['IT']
['Kurt Deleu']
399 ['Kurt Deleu'] ['BE']
['Dezarnaulds Julien']
400 ['Dezarnaulds Julien'] ['FR']
['Golay Geymond Florence']
401 ['Golay Geymond Florence'] ['CH']
['Craveiro Nicolas']
402 ['Craveiro Nicolas'] ['FR']
['Porubcan Pavol']
403 ['Porubcan Pavol'] ['SK']
['Vogel Mark']
404 ['Vogel Mark'] ['US']
['Berruel Xavier']
405 ['Berruel Xavier'] ['CA']
['Ramser Tanguy']
406 ['Ramser Tanguy'] ['CH']
['Robbins Pat']
407 ['Robbins Pat'] ['GB']
['Roncoroni Luca']
408 ['Roncoroni Luca'] ['NO']
['Delbarba Stefano']
409 ['Delbarba Stefano'] ['IT']
['Lorenzi Michele']
410 ['Lorenzi Michele'] ['IT']
['Duperray Remy']
411 ['Duperray Remy'] ['FR']
['Gouttevin Nicolas']
412 ['Gouttevin Nicolas'] ['FR']
['Reed Billy']
413 ['Reed Billy'] ['IE']
['Boudot Romain']
414 ['Boudot Romain'] ['FR']
['Macleod Lea']
415 ['Macleod Lea'] ['GB']
['Pasalodos Heras Luis Miguel']
416 ['Pasalodos Heras Luis Miguel'] ['ES']
['Mustica Teresa']
417 ['Mustica Teresa'] ['IT']
['Buhler Joachim']
418 ['Buhler Joachim'] ['CH']
['Yhuel Sebastien']
419 ['Yhuel Sebastien'] ['FR']
['Sauvage Romain']
420 ['Sauvage Romain'] ['FR']
['Santos Pose Jose Manuel']
421 ['Santos Pose Jose Manuel'] ['ES']
['Chen Peng Chung']
422 ['Chen Peng Chung'] ['TW']
['D Agostino Maurizio']
423 ['D Agostino Maurizio'] ['IT']
['Deliau Bastien']
424 ['Deliau Bastien'] ['FR']
['Bachman Tod']
425 ['Bachman Tod'] ['US']
['Convert Franck']
426 ['Convert Franck'] ['FR']
['Villa Simone']
427 ['Villa Simone'] ['IT']
['Gray James']
428 ['Gray James'] ['GB']
['Grillon Maxence']
429 ['Grillon Maxence'] ['FR']
['Collart Clement']
430 ['Collart Clement'] ['FR']
['Alfero Flavien']
431 ['Alfero Flavien'] ['FR']
['Gent Anthony']
432 ['Gent Anthony'] ['CH']
['Alfisi Enrico']
433 ['Alfisi Enrico'] ['IT']
['Rolfini Alessandro']
434 ['Rolfini Alessandro'] ['IT']
['Christensen Garret']
435 ['Christensen Garret'] ['US']
['Healy Claire']
436 ['Healy Claire'] ['AU']
['Delannoy Emmanuel']
437 ['Delannoy Emmanuel'] ['FR']
['Burke Tyler']
438 ['Burke Tyler'] ['US']
['Soderlund Emil']
439 ['Soderlund Emil'] ['FI']
['Frayssines David']
440 ['Frayssines David'] ['FR']
['Pirovano Andrea']
441 ['Pirovano Andrea'] ['IT']
['Navillod Rinaldo']
442 ['Navillod Rinaldo'] ['IT']
['Turin Nicholas']
443 ['Turin Nicholas'] ['CH']
['Kuehn Philip']
444 ['Kuehn Philip'] ['DE']
['Ferri Riccardo']
445 ['Ferri Riccardo'] ['IT']
['Bon Suzanna']
446 ['Bon Suzanna'] ['US']
['Giovannini Giacomo']
447 ['Giovannini Giacomo'] ['IT']
['Vervy Quentin']
448 ['Vervy Quentin'] ['BE']
['Thompson Mark Thompson']
449 ['Thompson Mark Thompson'] ['GB']
['Schooler Michael']
450 ['Schooler Michael'] ['US']
['Jouglar Sebastien']
451 ['Jouglar Sebastien'] ['FR']
['Carlier Julien']
452 ['Carlier Julien'] ['FR']
['Loridan Jeremy']
453 ['Loridan Jeremy'] ['FR']
['Regazzoni Stefano']
454 ['Regazzoni Stefano'] ['IT']
['Gavazzeni Silvano']
455 ['Gavazzeni Silvano'] ['IT']
['Arash Rafii']
456 ['Arash Rafii'] ['QA']
['Codina Antonio']
457 ['Codina Antonio'] ['GB']
['Pianesi Giuseppe']
458 ['Pianesi Giuseppe'] ['IT']
['Frisoni Emanuele']
459 ['Frisoni Emanuele'] ['IT']
['Gaboriau Clement']
460 ['Gaboriau Clement'] ['FR']
['Olivieri Eric']
461 ['Olivieri Eric'] ['FR']
['Nelson Shane']
462 ['Nelson Shane'] ['US']
['Antonin Claudio']
463 ['Antonin Claudio'] ['IT']
['Amey Xavier']
464 ['Amey Xavier'] ['FR']
['Porati Fabrizio']
465 ['Porati Fabrizio'] ['IT']
['Peris Ramon']
466 ['Peris Ramon'] ['ES']
['Pinel Christophe']
467 ['Pinel Christophe'] ['FR']
['Castiglione Marco']
468 ['Castiglione Marco'] ['IT']
['Carosio Flavio']
469 ['Carosio Flavio'] ['IT']
['Marchand Regis']
470 ['Marchand Regis'] ['FR']
['Fedele Giorgio']
471 ['Fedele Giorgio'] ['IT']
['Sadowski Tomasz']
472 ['Sadowski Tomasz'] ['PT']
['Hewitson Kirsty']
473 ['Hewitson Kirsty'] ['GB']
['Sebanek Martin']
474 ['Sebanek Martin'] ['CZ']
['D Angelo Fabio']
475 ['D Angelo Fabio'] ['IT']
['Barberis Negra Massimo']
476 ['Barberis Negra Massimo'] ['IT']
['Dessambre Nicolas']
477 ['Dessambre Nicolas'] ['BE']
['Guezou Erwan']
478 ['Guezou Erwan'] ['FR']
['Argelich Torra Enrique']
479 ['Argelich Torra Enrique'] ['ES']
['Garcia Hernandez Fernando']
480 ['Garcia Hernandez Fernando'] ['ES']
['Mengin Vincent']
481 ['Mengin Vincent'] ['FR']
['Delle Monache Federico']
482 ['Delle Monache Federico'] ['IT']
['Pellegrino Piero']
483 ['Pellegrino Piero'] ['IT']
['Barausse Mose']
484 ['Barausse Mose'] ['IT']
['Cazzaniga Paolo']
485 ['Cazzaniga Paolo'] ['IT']
['Sheridan Sarah']
486 ['Sheridan Sarah'] ['GB']
['Ottoni Porto Francisco']
487 ['Ottoni Porto Francisco'] ['BR']
['Hernandez Ruiz Javier']
488 ['Hernandez Ruiz Javier'] ['MX']
['Maier Frank']
489 ['Maier Frank'] ['DE']
['Shao Sebastien']
490 ['Shao Sebastien'] ['FR']
['Soler Jean Pierre']
491 ['Soler Jean Pierre'] ['FR']
['Rossi Fabio']
492 ['Rossi Fabio'] ['IT']
['Verguet Alain']
493 ['Verguet Alain'] ['FR']
['Vairoli Martin']
494 ['Vairoli Martin'] ['IT']
['Camperi Franco']
495 ['Camperi Franco'] ['IT']
['Ralcheva Aneta']
496 ['Ralcheva Aneta'] ['BG']
['Mennin Jonathan']
497 ['Mennin Jonathan'] ['FR']
['Zamboni Matteo']
498 ['Zamboni Matteo'] ['IT']
['Pistillo Sergio']
499 ['Pistillo Sergio'] ['IT']

['Scagliotti Orlandini Luca']
500 ['Scagliotti Orlandini Luca'] ['IT']
['Giacchetta Stephane']
501 ['Giacchetta Stephane'] ['BE']
['Perez Comendador David']
502 ['Perez Comendador David'] ['ES']
['Ruiz Santiago Lucas']
503 ['Ruiz Santiago Lucas'] ['ES']
['Szkaluba Barbara']
504 ['Szkaluba Barbara'] ['GB']
['Lodi Severino']
505 ['Lodi Severino'] ['IT']
['Pella Liliana Beatriz']
506 ['Pella Liliana Beatriz'] ['IT']
['Bouquet Sophie']
507 ['Bouquet Sophie'] ['FR']
['Sudars Martins']
508 ['Sudars Martins'] ['LV']
['Byrne Simon Peter']
509 ['Byrne Simon Peter'] ['AU']
['Haylett Philip']
510 ['Haylett Philip'] ['GB']
['Luboz Dante']
511 ['Luboz Dante'] ['IT']
['Grise Dominic']
512 ['Grise Dominic'] ['GB']
['Augustson Ketil']
513 ['Augustson Ketil'] ['NO']
['Da Costa Veloso Alexandre']
514 ['Da Costa Veloso Alexandre'] ['AD']
['Le Duigou Sebastien']
515 ['Le Duigou Sebastien'] ['CH']
['Conta Paolo']
516 ['Conta Paolo'] ['IT']
['Beaumont Olivier']
517 ['Beaumont Olivier'] ['FR']
['Schwalger Andreas']
518 ['Schwalger Andreas'] ['DE']
['Nakamura Saki']
519 ['Nakamura Saki'] ['GB']
['Despretz Thomas']
520 ['Despretz Thomas'] ['FR']
['Confalonieri Davide']
521 ['Confalonieri Davide'] ['IT']
['Majek Fabrice']
522 ['Majek Fabrice'] ['FR']
['Piani Alessandro']
523 ['Piani Alessandro'] ['IT']
['Chabloz Davide']
524 ['Chabloz Davide'] ['IT']
['Bonzanini Massimo']
525 ['Bonzanini Massimo'] ['IT']
['Barrot Loic']
526 ['Barrot Loic'] ['FR']
['Durao Paulo']
527 ['Durao Paulo'] ['PT']
['Ringeval Melanie']
528 ['Ringeval Melanie'] ['RE']
['Solivera Retchas Carles']
529 ['Solivera Retchas Carles'] ['ES']
['Colls Avila Oscar']
530 ['Colls Avila Oscar'] ['ES']
['Meric Stephanie']
531 ['Meric Stephanie'] ['FR']
['Magoni Paolo']
532 ['Magoni Paolo'] ['IT']
['Rigard Mickael']
533 ['Rigard Mickael'] ['FR']
['Fea Denis']
534 ['Fea Denis'] ['IT']
['Bergese Giacomo']
535 ['Bergese Giacomo'] ['IT']
['Grenno Raphael']
536 ['Grenno Raphael'] ['CH']
['Henson Michael']
537 ['Henson Michael'] ['US']
['Dossena Paolo']
538 ['Dossena Paolo'] ['IT']
['Castagnola Federico']
539 ['Castagnola Federico'] ['IT']
['Ducret Alex']
540 ['Ducret Alex'] ['IT']
['Tremolada Paolo']
541 ['Tremolada Paolo'] ['IT']
['Poirier Pierre']
542 ['Poirier Pierre'] ['FR']
['Gofflot Frederic']
543 ['Gofflot Frederic'] ['BE']
['Weisskopf Michael']
544 ['Weisskopf Michael'] ['DE']
['Cooney Neil']
545 ['Cooney Neil'] ['GB']
['Heranney David']
546 ['Heranney David'] ['FR']
['Villien Gilbert']
547 ['Villien Gilbert'] ['FR']
['Perico Matteo Giuseppe']
548 ['Perico Matteo Giuseppe'] ['IT']
['Heyns Christophe']
549 ['Heyns Christophe'] ['BE']
['Demeter Michal']
550 ['Demeter Michal'] ['SK']
['Taskin Sadik']
551 ['Taskin Sadik'] ['TR']
['Silver Carl']
552 ['Silver Carl'] ['GB']
['Ferrario Andrea']
553 ['Ferrario Andrea'] ['IT']
['Maestri Massimiliano']
554 ['Maestri Massimiliano'] ['IT']
['Gaffuri Paolo']
555 ['Gaffuri Paolo'] ['IT']
['Videk Ivan']
556 ['Videk Ivan'] ['DE']
['Tiefenthaler Andrea']
557 ['Tiefenthaler Andrea'] ['IT']
['Iren Deniz']
558 ['Iren Deniz'] ['NL']
['Aysolmaz Banu']
559 ['Aysolmaz Banu'] ['NL']
['Hacking Hugh']
560 ['Hacking Hugh'] ['ZA']
['Favre Paolo']
561 ['Favre Paolo'] ['IT']
['Breakell Matthew']
562 ['Breakell Matthew'] ['FR']
['Briere Francois']
563 ['Briere Francois'] ['FR']
['Andre Carlos']
564 ['Andre Carlos'] ['PT']
['Mota Joao']
565 ['Mota Joao'] ['PT']
['Pelisson Marc']
566 ['Pelisson Marc'] ['FR']
['Filisetti Antonio']
567 ['Filisetti Antonio'] ['IT']
['Hoarau Philippe']
568 ['Hoarau Philippe'] ['FR']
['Sambarino Carlo']
569 ['Sambarino Carlo'] ['IT']
['Piromalli Roberto']
570 ['Piromalli Roberto'] ['IT']
['Nosal Vladimir']
571 ['Nosal Vladimir'] ['SK']
['Etienne Gregoire']
572 ['Etienne Gregoire'] ['BE']
['Markert Dominik']
573 ['Markert Dominik'] ['DE']
['Mantione Stefano']
574 ['Mantione Stefano'] ['IT']
['Bouillot Eric']
575 ['Bouillot Eric'] ['FR']
['Mattiacci Pier Paolo']
576 ['Mattiacci Pier Paolo'] ['IT']
['Gerasimovic Marko']
577 ['Gerasimovic Marko'] ['RS']
['Hardes Christoph']
578 ['Hardes Christoph'] ['DE']
['Linkenbach Alexander']
579 ['Linkenbach Alexander'] ['IT']
['Roveyaz Marino']
580 ['Roveyaz Marino'] ['IT']
['Da Forno Dario']
581 ['Da Forno Dario'] ['IT']
['Gurioli Marco']
582 ['Gurioli Marco'] ['IT']
['Angeli Pierugo']
583 ['Angeli Pierugo'] ['IT']
['Venturini Corrado']
584 ['Venturini Corrado'] ['IT']
['Lete Pascal']
585 ['Lete Pascal'] ['BE']
['Bollito Mario']
586 ['Bollito Mario'] ['IT']
['Duin Jeroen']
587 ['Duin Jeroen'] ['NL']
['Furia Daniele']
588 ['Furia Daniele'] ['IT']
['Mondani Corinna']
589 ['Mondani Corinna'] ['IT']
['Kurashina Makoto']
590 ['Kurashina Makoto'] ['JP']
['Bourguignon Laurent']
591 ['Bourguignon Laurent'] ['BE']
['Bermudez Conrado Jr']
592 ['Bermudez Conrado Jr'] ['PH']
['Giribaldi Corrado']
593 ['Giribaldi Corrado'] ['IT']
['Bartoletti Angelo']
594 ['Bartoletti Angelo'] ['IT']
['Taglianetti Mirko']
595 ['Taglianetti Mirko'] ['IT']
['Sivelli Enrico']
596 ['Sivelli Enrico'] ['IT']
['Pancini Jonata']
597 ['Pancini Jonata'] ['IT']
['Scotto Busato Raffaella']
598 ['Scotto Busato Raffaella'] ['IT']
['Mcgovern Greg']
599 ['Mcgovern Greg'] ['IE']
['Bernorio Alessandro']
600 ['Bernorio Alessandro'] ['IT']
['Orizio Andrea']
601 ['Orizio Andrea'] ['IT']
['Bunjuar Supat']
602 ['Bunjuar Supat'] ['TH']
['Colombo Michele']
603 ['Colombo Michele'] ['IT']
['Talukdar Bipul']
604 ['Talukdar Bipul'] ['US']
['Crubilie Joel']
605 ['Crubilie Joel'] ['FR']
['Boerboom Almar']
606 ['Boerboom Almar'] ['FR']
['Rouault Olivier']
607 ['Rouault Olivier'] ['FR']
['Clerc Jerome']
608 ['Clerc Jerome'] ['FR']
['Schirmer Sabrina']
609 ['Schirmer Sabrina'] ['BR']
['Manzoni Marco']
610 ['Manzoni Marco'] ['IT']
['Giardi Maria Teresa']
611 ['Giardi Maria Teresa'] ['SM']
['Faivre Stephane']
612 ['Faivre Stephane'] ['FR']
['Kenkenberg Gabriele']
613 ['Kenkenberg Gabriele'] ['DE']
['Guillon Christophe']
614 ['Guillon Christophe'] ['FR']
['De Mingo Santiago Javi']
615 ['De Mingo Santiago Javi'] ['ES']
['Menard Cyrille']
616 ['Menard Cyrille'] ['FR']
['Blanchard Sebastien']
617 ['Blanchard Sebastien'] ['FR']
['Cortese Andrea']
618 ['Cortese Andrea'] ['IT']
['D Angelo Marco']
619 ['D Angelo Marco'] ['IT']
['Marcos Olivier']
620 ['Marcos Olivier'] ['FR']
['Piccioni Giuseppe']
621 ['Piccioni Giuseppe'] ['IT']
['Paschetto Renzo']
622 ['Paschetto Renzo'] ['IT']
['Marchand Michel']
623 ['Marchand Michel'] ['FR']
['Tonso Ivan']
624 ['Tonso Ivan'] ['FR']
['Rigodanza Lorenzo']
625 ['Rigodanza Lorenzo'] ['IT']
['Tomasz Miedzik']
626 ['Tomasz Miedzik'] ['PL']
['Costa Alberto']
627 ['Costa Alberto'] ['IT']
['Amar Delapierre Jocelyne']
628 ['Amar Delapierre Jocelyne'] ['FR']
['Ficek Roman']
629 ['Ficek Roman'] ['PL']
['Martin Toro Francesc']
630 ['Martin Toro Francesc'] ['ES']
['Collison Kim Collison']
631 ['Collison Kim Collison'] ['GB']
['Probst Florian']
632 ['Probst Florian'] ['DE']
['Bernard Nicolas']
633 ['Bernard Nicolas'] ['FR']
['Biard Antoine']
634 ['Biard Antoine'] ['FR']
['Nancoz Michael']
635 ['Nancoz Michael'] ['CH']
['Tieran Christophe']
636 ['Tieran Christophe'] ['FR']
['Bonn Rene']
637 ['Bonn Rene'] ['DE']
['Saulo Alberto']
638 ['Saulo Alberto'] ['IT']
['Marti Pau']
639 ['Marti Pau'] ['ES']
['Begnis Andrea']
640 ['Begnis Andrea'] ['IT']
['Vioud Jerome']
641 ['Vioud Jerome'] ['FR']
['Pedretti Sergio']
642 ['Pedretti Sergio'] ['IT']
['D Angelo Yuri']
643 ['D Angelo Yuri'] ['IT']
['Nessi Manuel']
644 ['Nessi Manuel'] ['IT']
['Rotondo Bartolomeo']
645 ['Rotondo Bartolomeo'] ['IT']
['Serratore Vincenzo']
646 ['Serratore Vincenzo'] ['IT']
['Fasoli Nicola']
647 ['Fasoli Nicola'] ['IT']
['De Massimi Lucio']
648 ['De Massimi Lucio'] ['IT']
['Wood Alan']
649 ['Wood Alan'] ['NL']
['Beltramelli Marco']
650 ['Beltramelli Marco'] ['IT']
['Rein Steve']
651 ['Rein Steve'] ['CH']
['Antonelli Davide']
652 ['Antonelli Davide'] ['IT']
['Pinamonti Alex']
653 ['Pinamonti Alex'] ['IT']
['Carrara Fabio']
654 ['Carrara Fabio'] ['IT']
['Menti Federica']
655 ['Menti Federica'] ['IT']
['Brugnara Fabio']
656 ['Brugnara Fabio'] ['IT']
['Sadie Chris']
657 ['Sadie Chris'] ['ZA']
['Giustino Giuseppe']
658 ['Giustino Giuseppe'] ['IT']
['Moison Morgan']
659 ['Moison Morgan'] ['CH']
['Severino Giovanni']
660 ['Severino Giovanni'] ['IT']
['Goubard Xavier']
661 ['Goubard Xavier'] ['FR']
['Karbalaii Mahya']
662 ['Karbalaii Mahya'] ['IR']
['Valagussa Valerio']
663 ['Valagussa Valerio'] ['IT']
['Rosso Marco']
664 ['Rosso Marco'] ['IT']
['Pattison Gary']
665 ['Pattison Gary'] ['GB']
['Dainese Federico']
666 ['Dainese Federico'] ['IT']
['Delfau Julien']
667 ['Delfau Julien'] ['FR']
['Silva Mario']
668 ['Silva Mario'] ['IT']
['Bagna Mirko Mario']
669 ['Bagna Mirko Mario'] ['IT']
['Bui Thoai']
670 ['Bui Thoai'] ['FR']
['Greer Sylvia']
671 ['Greer Sylvia'] ['US']

['Gau Jiahorng']
672 ['Gau Jiahorng'] ['TW']
['Robino Renzo']
673 ['Robino Renzo'] ['IT']
['Casadei Andrea']
674 ['Casadei Andrea'] ['IT']
['Heil Thomas']
675 ['Heil Thomas'] ['AT']
['Allocco Simone']
676 ['Allocco Simone'] ['IT']
['Hernandez Garcia Jose Rafael']
677 ['Hernandez Garcia Jose Rafael'] ['ES']
['Borne Aurelien']
678 ['Borne Aurelien'] ['FR']
['Bisazza Tiziano']
679 ['Bisazza Tiziano'] ['IT']
['Huang Ken']
680 ['Huang Ken'] ['US']
['Cousin Enrique']
681 ['Cousin Enrique'] ['FR']
['Sergi Simone']
682 ['Sergi Simone'] ['IT']
['Crippa Andrea']
683 ['Crippa Andrea'] ['IT']
['Stasia Manuel']
684 ['Stasia Manuel'] ['IT']
['Meehan Sean']
685 ['Meehan Sean'] ['IE']
['Bieller Didier']
686 ['Bieller Didier'] ['IT']
['Michels Erik']
687 ['Michels Erik'] ['BE']
['Ghio Laurent']
688 ['Ghio Laurent'] ['FR']
['Scuccato Massimo']
689 ['Scuccato Massimo'] ['IT']
['Butti Emilio']
690 ['Butti Emilio'] ['IT']
['Preda Luciano']
691 ['Preda Luciano'] ['IT']
['De Cani Norberto']
692 ['De Cani Norberto'] ['IT']
['Micheletto Paolo']
693 ['Micheletto Paolo'] ['IT']
['Vaschetto Alberto']
694 ['Vaschetto Alberto'] ['IT']
['Galvache Oliver Carlos']
695 ['Galvache Oliver Carlos'] ['ES']
['Crucitti Pasqualino']
696 ['Crucitti Pasqualino'] ['IT']
['Bernard Jean Marie']
697 ['Bernard Jean Marie'] ['FR']
['Xu Jinsong']
698 ['Xu Jinsong'] ['CN']
['Cossavella Matteo']
699 ['Cossavella Matteo'] ['IT']
['Estevas Guilmain Manuel']
700 ['Estevas Guilmain Manuel'] ['ES']
['Van Eylen Peter']
701 ['Van Eylen Peter'] ['BE']
['Lelu Olivier']
702 ['Lelu Olivier'] ['FR']
['Roualdes Olivier']
703 ['Roualdes Olivier'] ['FR']
['Platon Herve']
704 ['Platon Herve'] ['FR']
['Kech Michael']
705 ['Kech Michael'] ['BE']
['Lobos Veronica']
706 ['Lobos Veronica'] ['CL']
['Heid Jens']
707 ['Heid Jens'] ['DE']
['Pedron Fabio']
708 ['Pedron Fabio'] ['IT']
['Perseval Sebastien']
709 ['Perseval Sebastien'] ['FR']
['Gvozden Vladimir']
710 ['Gvozden Vladimir'] ['RS']
['Joao Nadjala']
711 ['Joao Nadjala'] ['BR']
['Leone Massimo']
712 ['Leone Massimo'] ['IT']
['Gaignet Frederic']
713 ['Gaignet Frederic'] ['FR']
['Bourget Mickael']
714 ['Bourget Mickael'] ['FR']
['Bonanini Alessio']
715 ['Bonanini Alessio'] ['IT']
['Drozdiak Nick']
716 ['Drozdiak Nick'] ['US']
['Polese Matteo']
717 ['Polese Matteo'] ['IT']
['Riserva Riserva Grant']
718 ['Riserva Riserva Grant'] ['NZ']
['Ku Maggie']
719 ['Ku Maggie'] ['TW']
['Lorenzi Alberto']
720 ['Lorenzi Alberto'] ['IT']
['Scudieri Adriano']
721 ['Scudieri Adriano'] ['IT']
['Meek Jon']
722 ['Meek Jon'] ['GB']
['Ban Akemi']
723 ['Ban Akemi'] ['JP']
['Sprungli Caspar']
724 ['Sprungli Caspar'] ['AR']
['Milici Santino']
725 ['Milici Santino'] ['IT']
['Tesser Mike']
726 ['Tesser Mike'] ['NL']
['Gueguen Christophe']
727 ['Gueguen Christophe'] ['FR']
['Bolduc Claudine']
728 ['Bolduc Claudine'] ['CA']
['Poiroux Stephane']
729 ['Poiroux Stephane'] ['FR']
['Michon Yves']
730 ['Michon Yves'] ['FR']
['Conterno Monica']
731 ['Conterno Monica'] ['IT']
['Vidal Claude']
732 ['Vidal Claude'] ['FR']
['Nacci Mauro']
733 ['Nacci Mauro'] ['IT']
['Amerio Camilla']
734 ['Amerio Camilla'] ['IT']
['Della Pace Dario']
735 ['Della Pace Dario'] ['IT']
['Calabrese Domenico']
736 ['Calabrese Domenico'] ['IT']
['Merk Markus']
737 ['Merk Markus'] ['DE']
['Calabro Salvatore']
738 ['Calabro Salvatore'] ['IT']
['Tsujimoto Arihito']
739 ['Tsujimoto Arihito'] ['JP']
['Leroy Philippe']
740 ['Leroy Philippe'] ['FR']
['Butler Rebecca']
741 ['Butler Rebecca'] ['AU']
['Schneider Claude']
742 ['Schneider Claude'] ['FR']
['Le Gal Matthieu']
743 ['Le Gal Matthieu'] ['FR']
['Bassanelli Veronica']
744 ['Bassanelli Veronica'] ['IT']
['Lemaire Nicolas']
745 ['Lemaire Nicolas'] ['FR']
['Piasentin Riccardo']
746 ['Piasentin Riccardo'] ['IT']
['Nasserpuga Miguel Jose']
747 ['Nasserpuga Miguel Jose'] ['ES']
['Rotge David']
748 ['Rotge David'] ['FR']
['Fauvarque Thierry']
749 ['Fauvarque Thierry'] ['FR']
['Fauvarque Gaetan']
750 ['Fauvarque Gaetan'] ['FR']
['Tebaldi Massimiliano']
751 ['Tebaldi Massimiliano'] ['IT']
['Rouk Olle']
752 ['Rouk Olle'] ['EE']
['Aimo Michela']
753 ['Aimo Michela'] ['IT']
['Castagneri Fabrizio']
754 ['Castagneri Fabrizio'] ['IT']
['Gusmerotti Luca']
755 ['Gusmerotti Luca'] ['IT']
['Brancaleone Barbara']
756 ['Brancaleone Barbara'] ['IT']
['Margerte Philippe']
757 ['Margerte Philippe'] ['FR']
['Svartangen Heidi']
758 ['Svartangen Heidi'] ['NO']
['Peleg Dan']
759 ['Peleg Dan'] ['IL']
['Scolas Etienne']
760 ['Scolas Etienne'] ['BE']
['Savinel Guillaume']
761 ['Savinel Guillaume'] ['FR']
['Le Signor Patrice']
762 ['Le Signor Patrice'] ['FR']
['Treguier Yoann']
763 ['Treguier Yoann'] ['FR']
['Ruiz Laetitia']
764 ['Ruiz Laetitia'] ['FR']
['Coucourde Daniele']
765 ['Coucourde Daniele'] ['IT']
['Bastiani Berengere']
766 ['Bastiani Berengere'] ['FR']
['Garnett Ian']
767 ['Garnett Ian'] ['GB']
['Townsend Mark']
768 ['Townsend Mark'] ['GB']
['Goodchild Jaey']
769 ['Goodchild Jaey'] ['AU']
['Ginisty Thierry']
770 ['Ginisty Thierry'] ['FR']
['Barmasse Mario']
771 ['Barmasse Mario'] ['IT']
['Reynard Christophe']
772 ['Reynard Christophe'] ['FR']
['Law Wai']
773 ['Law Wai'] ['US']
['Franz Bassanesi Gabriel']
774 ['Franz Bassanesi Gabriel'] ['IT']
['Lazic Marina']
775 ['Lazic Marina'] ['RS']
['Seneci Maurizio']
776 ['Seneci Maurizio'] ['IT']
['Casati Valter']
777 ['Casati Valter'] ['IT']
['Sottero Roberto']
778 ['Sottero Roberto'] ['IT']
['Galea Eric']
779 ['Galea Eric'] ['FR']
['Romanin Vicki (Vittoria)']
780 ['Romanin Vicki (Vittoria)'] ['CA']
['Cornetti Barbara']
781 ['Cornetti Barbara'] ['IT']
['Bangwiroonrag Wannachai']
782 ['Bangwiroonrag Wannachai'] ['TH']
['Guagliumi Fabio']
783 ['Guagliumi Fabio'] ['IT']
['Parisio Patrizio']
784 ['Parisio Patrizio'] ['IT']
['Skoniecki Michal']
785 ['Skoniecki Michal'] ['PL']
['Sebillet Franck']
786 ['Sebillet Franck'] ['FR']
['Ferrario Giuliana']
787 ['Ferrario Giuliana'] ['IT']
['Medici Paolo']
788 ['Medici Paolo'] ['IT']
['Diemoz Ferruccio']
789 ['Diemoz Ferruccio'] ['IT']
['Bosio Claudine']
790 ['Bosio Claudine'] ['FR']
['Werneck Fred']
791 ['Werneck Fred'] ['CH']
['Bonnef Denis']
792 ['Bonnef Denis'] ['FR']
['Bonel Fabrizio']
793 ['Bonel Fabrizio'] ['IT']
['Burderi Edoardo']
794 ['Burderi Edoardo'] ['IT']
['Marquette Emmanuel']
795 ['Marquette Emmanuel'] ['FR']
['Giersberg Burkhard']
796 ['Giersberg Burkhard'] ['DE']
['Savi Andrea']
797 ['Savi Andrea'] ['IT']
['Gastaldi Massimo']
798 ['Gastaldi Massimo'] ['IT']
['Armange Xavier']
799 ['Armange Xavier'] ['FR']
['Bihag Cheryl']
800 ['Bihag Cheryl'] ['PH']
['Nakit Somkid']
801 ['Nakit Somkid'] ['TH']
['Bai Michel']
802 ['Bai Michel'] ['FR']
['Hartmann Johannes']
803 ['Hartmann Johannes'] ['DE']
['Moison Christian']
804 ['Moison Christian'] ['CH']
['Waterworth Graeme']
805 ['Waterworth Graeme'] ['GB']
['Corvisiero Michaela']
806 ['Corvisiero Michaela'] ['IT']
['Camara Jean Louis']
807 ['Camara Jean Louis'] ['FR']
['Hinman Martin']
808 ['Hinman Martin'] ['GB']
['Borgis Luigi Guerino']
809 ['Borgis Luigi Guerino'] ['IT']
['Cantarelli Nicola']
810 ['Cantarelli Nicola'] ['IT']
['Agosti Alessandro']
811 ['Agosti Alessandro'] ['IT']
['Lyu Zemin']
812 ['Lyu Zemin'] ['SG']
['Machet Dominique']
813 ['Machet Dominique'] ['FR']
['Patrocle Stefano']
814 ['Patrocle Stefano'] ['IT']
['Penserini Maurizio']
815 ['Penserini Maurizio'] ['IT']
['Maffeis Maria Renata']
816 ['Maffeis Maria Renata'] ['IT']
['Aramendi Mikel']
817 ['Aramendi Mikel'] ['ES']
['Wang Yi']
818 ['Wang Yi'] ['CA']
['Utsumi Katsuaki']
819 ['Utsumi Katsuaki'] ['JP']
['Barth Thierry']
820 ['Barth Thierry'] ['FR']
['Theoharidou Natasha']
821 ['Theoharidou Natasha'] ['GR']
['Bonacina Marco Giovanni']
822 ['Bonacina Marco Giovanni'] ['IT']
['Dalbard Remo']
823 ['Dalbard Remo'] ['IT']
['Nari Davide']
824 ['Nari Davide'] ['IT']
['Challancin Patrick']
825 ['Challancin Patrick'] ['IT']
['Sartori Luca']
826 ['Sartori Luca'] ['IT']
['Uberto Francesco']
827 ['Uberto Francesco'] ['IT']
['Vallemont Herve']
828 ['Vallemont Herve'] ['FR']
['Marco Berni']
829 ['Marco Berni'] ['IT']
['Rioboo Escalante Jon Mirena']
830 ['Rioboo Escalante Jon Mirena'] ['ES']
['Gutierrez Kellam Lourdes']
831 ['Gutierrez Kellam Lourdes'] ['CA']
['Caihuelas Quiles Ramon']
832 ['Caihuelas Quiles Ramon'] ['ES']
['Taupiac Jean Pierre']
833 ['Taupiac Jean Pierre'] ['FR']
['Haas Nadia']
834 ['Haas Nadia'] ['US']
['Shisheng Lin']
835 ['Shisheng Lin'] ['FR']
['Klancnik Tomislav']
836 ['Klancnik Tomislav'] ['SI']
['Klancnik Anja']
837 ['Klancnik Anja'] ['SI']
['Zlabys Vaidas']
838 ['Zlabys Vaidas'] ['LT']
['Perez Velarde Juan Francisco']
839 ['Perez Velarde Juan Francisco'] ['ES']
['Mattijssen Jose Wilhelmina Theodora Maria']
840 ['Mattijssen Jose Wilhelmina Theodora Maria'] ['IT']
['Sanchez Bustara Alberto']
841 ['Sanchez Bustara Alberto'] ['ES']
['Dinu Turcanu']
842 ['Dinu Turcanu'] ['RO']

['Estefano Luis']
843 ['Estefano Luis'] ['ES']
['Graff Katie']
844 ['Graff Katie'] ['US']
['Colombo Mauro']
845 ['Colombo Mauro'] ['IT']
['Venturelli Fausto']
846 ['Venturelli Fausto'] ['IT']
['Rollo Daniele Stefano']
847 ['Rollo Daniele Stefano'] ['IT']
['D Eugenio Dario']
848 ['D Eugenio Dario'] ['IT']
['Poiroux Cecile']
849 ['Poiroux Cecile'] ['FR']
['Presutti Saba Emanuele']
850 ['Presutti Saba Emanuele'] ['IT']
['Weber Tim']
851 ['Weber Tim'] ['US']
['Bolpagni Herivan']
852 ['Bolpagni Herivan'] ['IT']
['Pando Garcia Jorge']
853 ['Pando Garcia Jorge'] ['ES']
['Mangaretto Marco']
854 ['Mangaretto Marco'] ['IT']
['Patacchini Marco']
855 ['Patacchini Marco'] ['IT']
['Stivanello Mariano']
856 ['Stivanello Mariano'] ['IT']
['Wong Ho Chung']
857 ['Wong Ho Chung'] ['HK']
['Stuart Emma']
858 ['Stuart Emma'] ['GB']
['Kauffmann Antoine']
859 ['Kauffmann Antoine'] ['FR']
['Doi Takashi']
860 ['Doi Takashi'] ['JP']
['Stverak Tomas']
861 ['Stverak Tomas'] ['CZ']
['Galve Javier']
862 ['Galve Javier'] ['ES']
['Rostagno Alessandro']
863 ['Rostagno Alessandro'] ['IT']
['Berthon Mickael']
864 ['Berthon Mickael'] ['FR']
['Xie Wenfei']
865 ['Xie Wenfei'] ['CN']
['De Clerck Jan']
866 ['De Clerck Jan'] ['BE']
['Kurtyak Valery']
867 ['Kurtyak Valery'] ['IT']
['Bonzi Loris']
868 ['Bonzi Loris'] ['IT']
['Camperi Roberto']
869 ['Camperi Roberto'] ['IT']
['Ishio Kazutaka']
870 ['Ishio Kazutaka'] ['JP']
['Morgan Carol']
871 ['Morgan Carol'] ['GB']
['Chianese Alexandre']
872 ['Chianese Alexandre'] ['FR']
['Meyer Benjamin']
873 ['Meyer Benjamin'] ['CH']
['Vuillen Loris']
874 ['Vuillen Loris'] ['IT']
['Hulka Lukas']
875 ['Hulka Lukas'] ['CZ']
['Florentin Gooris']
876 ['Florentin Gooris'] ['BE']
['Meignan Pierre']
877 ['Meignan Pierre'] ['FR']
['Smith Orran']
878 ['Smith Orran'] ['IM']
['Pellissier Matteo']
879 ['Pellissier Matteo'] ['IT']
['Sic Cajbon Kelinton Ottoniel']
880 ['Sic Cajbon Kelinton Ottoniel'] ['GT']
['Storc Joseph']
881 ['Storc Joseph'] ['US']
['Boclinville Gauthier']
882 ['Boclinville Gauthier'] ['BE']
['Gleizes Etienne']
883 ['Gleizes Etienne'] ['FR']
['Luha Kristjan']
884 ['Luha Kristjan'] ['EE']
['Anselmini Luca']
885 ['Anselmini Luca'] ['IT']
['Vigliocco Mariela']
886 ['Vigliocco Mariela'] ['AR']
['Yamamoto Kenichi']
887 ['Yamamoto Kenichi'] ['JP']
['Mora Federico']
888 ['Mora Federico'] ['IT']
['Zemoz Andrea']
889 ['Zemoz Andrea'] ['IT']
['Atzeni Giacomo']
890 ['Atzeni Giacomo'] ['IT']
['Riabova Oksana']
891 ['Riabova Oksana'] ['IT']
['Nobuhito Kubo']
892 ['Nobuhito Kubo'] ['JP']
['Varga Miroslav']
893 ['Varga Miroslav'] ['SK']
['Bouillard Benoit']
894 ['Bouillard Benoit'] ['FR']
['Grucker Laurent']
895 ['Grucker Laurent'] ['FR']
['Stewart Ian']
896 ['Stewart Ian'] ['GB']
['Bastiaens Wim']
897 ['Bastiaens Wim'] ['BE']
['Emo Frederic']
898 ['Emo Frederic'] ['FR']
['Delafontaine Thomas']
899 ['Delafontaine Thomas'] ['FR']
['Andres Sebastien']
900 ['Andres Sebastien'] ['FR']
['Vanmarcke Maxime']
901 ['Vanmarcke Maxime'] ['FR']
['Goldberg Kevin']
902 ['Goldberg Kevin'] ['US']
['Tys Maxime']
903 ['Tys Maxime'] ['BE']
['Tagliabue Andrea Maria']
904 ['Tagliabue Andrea Maria'] ['IT']
['Nava Thomas']
905 ['Nava Thomas'] ['IT']
['Buchowicz Krzysztof']
906 ['Buchowicz Krzysztof'] ['PL']
['Pederzoli Alessandro']
907 ['Pederzoli Alessandro'] ['IT']
['Rolando Erik']
908 ['Rolando Erik'] ['IT']
['Bo Alkis']
909 ['Bo Alkis'] ['GR']
['Rabaglio Fabrizio']
910 ['Rabaglio Fabrizio'] ['IT']
['Plamondon Mathieu']
911 ['Plamondon Mathieu'] ['CH']
['Munoz Echevarria Manuel']
912 ['Munoz Echevarria Manuel'] ['ES']
['Flavelle Erika']
913 ['Flavelle Erika'] ['CA']
['Miquel Philippe']
914 ['Miquel Philippe'] ['FR']
['Tang Sun Kam']
915 ['Tang Sun Kam'] ['HK']
['Tuninetti Emanuele']
916 ['Tuninetti Emanuele'] ['IT']
['Moretti Andrea']
917 ['Moretti Andrea'] ['IT']
['Grieger Katrin']
918 ['Grieger Katrin'] ['DE']
['Jouffrey Olivier']
919 ['Jouffrey Olivier'] ['FR']
['Yvin Erwan']
920 ['Yvin Erwan'] ['FR']
['Kabylbekov Bakhyt']
921 ['Kabylbekov Bakhyt'] ['KZ']
['Thiriet Fabien']
922 ['Thiriet Fabien'] ['FR']
['Martin Escribano Maximo']
923 ['Martin Escribano Maximo'] ['ES']
['Domitrovix Nikola']
924 ['Domitrovix Nikola'] ['HR']
['Korakas Dimitrios']
925 ['Korakas Dimitrios'] ['GR']
['Leonidis Anastasios']
926 ['Leonidis Anastasios'] ['GR']
['Faucon Tony']
927 ['Faucon Tony'] ['FR']
['Berna Marie']
928 ['Berna Marie'] ['FR']
['Drews Barbara']
929 ['Drews Barbara'] ['CH']
['Drilling Carsten']
930 ['Drilling Carsten'] ['CH']
['Gouthier Enrica']
931 ['Gouthier Enrica'] ['IT']
['Carelli Cristian']
932 ['Carelli Cristian'] ['IT']
['Holsgrove Tim']
933 ['Holsgrove Tim'] ['GB']
['Cannesson Alexis']
934 ['Cannesson Alexis'] ['FR']
['Baldi Guarinoni Francesco']
935 ['Baldi Guarinoni Francesco'] ['IT']
['Bryant Shane']
936 ['Bryant Shane'] ['US']
['Gaillet David']
937 ['Gaillet David'] ['FR']
['Fujii Tatsuya']
938 ['Fujii Tatsuya'] ['JP']
['Morvan Yan']
939 ['Morvan Yan'] ['FR']
['Alexandru Florin']
940 ['Alexandru Florin'] ['RO']
['Torro Carceles Ramon']
941 ['Torro Carceles Ramon'] ['ES']
['Fages Tafanelli Eric']
942 ['Fages Tafanelli Eric'] ['FR']
['Dunn Andy']
943 ['Dunn Andy'] ['GB']
['Murphy Alex']
944 ['Murphy Alex'] ['GB']
['Ciapa Philippe']
945 ['Ciapa Philippe'] ['FR']
['Luboz Thomas']
946 ['Luboz Thomas'] ['FR']
['Wright Adam']
947 ['Wright Adam'] ['DE']
['Joly Alessandra']
948 ['Joly Alessandra'] ['IT']
['Chauvin Fontaine Christophe']
949 ['Chauvin Fontaine Christophe'] ['FR']
['Masoero Luca']
950 ['Masoero Luca'] ['IT']
['Semiotas Daugirdas']
951 ['Semiotas Daugirdas'] ['LT']
['Khalyapin Alexander']
952 ['Khalyapin Alexander'] ['EE']
['Hunout Vincent']
953 ['Hunout Vincent'] ['FR']
['Bianchini Flaviano']
954 ['Bianchini Flaviano'] ['IT']
['Kurdija Zoran']
955 ['Kurdija Zoran'] ['HR']
['Kong Nicolas']
956 ['Kong Nicolas'] ['FR']
['Sciutto Italo']
957 ['Sciutto Italo'] ['IT']
['Hunziker Ivan']
958 ['Hunziker Ivan'] ['CH']
['Vesseau Damien']
959 ['Vesseau Damien'] ['FR']
['Kervarec Simon']
960 ['Kervarec Simon'] ['FR']
['Ascone Frederic']
961 ['Ascone Frederic'] ['FR']
['Tricas Lazzaro Jorge']
962 ['Tricas Lazzaro Jorge'] ['ES']
['Sorarrain Eneko']
963 ['Sorarrain Eneko'] ['ES']
['Douillet David']
964 ['Douillet David'] ['FR']
['De Stael Clement']
965 ['De Stael Clement'] ['FR']
['Lacombe Sebastien']
966 ['Lacombe Sebastien'] ['CA']
['Bernardino Fernando']
967 ['Bernardino Fernando'] ['GB']
['Denis Bernard']
968 ['Denis Bernard'] ['BE']
['Prince Mike']
969 ['Prince Mike'] ['GB']
['Quirk Thomas']
970 ['Quirk Thomas'] ['CH']
['Ermolenko Alexey']
971 ['Ermolenko Alexey'] ['GB']
['Mcintosh Travis']
972 ['Mcintosh Travis'] ['US']
['Gnojek Danny']
973 ['Gnojek Danny'] ['US']
['Dorchies Fabien']
974 ['Dorchies Fabien'] ['FR']
['Rossin Cecile']
975 ['Rossin Cecile'] ['FR']
['Dormond Olivier']
976 ['Dormond Olivier'] ['CH']
['Rousselet Arnaud']
977 ['Rousselet Arnaud'] ['FR']
['Yanez Beas Daniel']
978 ['Yanez Beas Daniel'] ['ES']
['Cheesman James']
979 ['Cheesman James'] ['ES']
['Sanz Lazaro Roberto']
980 ['Sanz Lazaro Roberto'] ['ES']
['Laimer Elisabeth']
981 ['Laimer Elisabeth'] ['IT']
['Chapelle Florian']
982 ['Chapelle Florian'] ['FR']
['Carcenac Gautier']
983 ['Carcenac Gautier'] ['FR']
['Travers Jean Michel']
984 ['Travers Jean Michel'] ['DE']
['Hoenner Dominique']
985 ['Hoenner Dominique'] ['FR']
['Arienti Roberto']
986 ['Arienti Roberto'] ['IT']
['Pilsky Tomas']
987 ['Pilsky Tomas'] ['CZ']
['Flohr Jean Marc']
988 ['Flohr Jean Marc'] ['FR']
['Ponti Massimiliano']
989 ['Ponti Massimiliano'] ['IT']
['Reid Melissa']
990 ['Reid Melissa'] ['US']
['Mendez Lopez Jesus']
991 ['Mendez Lopez Jesus'] ['ES']
['Steblin Alexej']
992 ['Steblin Alexej'] ['DE']
['Ripamonti Marta']
993 ['Ripamonti Marta'] ['IT']
['Bellini Eduardo']
994 ['Bellini Eduardo'] ['ES']
['Joly Mattia']
995 ['Joly Mattia'] ['IT']
['Banoun Ninette']
996 ['Banoun Ninette'] ['NO']
['Aloisi Marco']
997 ['Aloisi Marco'] ['IT']
['Podraza Tadeusz']
998 ['Podraza Tadeusz'] ['PL']
['Sbrini Giuseppe']
999 ['Sbrini Giuseppe'] ['IT']
['Pasquali Mauro']
1000 ['Pasquali Mauro'] ['IT']
['Warmlander Alexis']
1001 ['Warmlander Alexis'] ['SE']
['Giovanetti Giancarlo']
1002 ['Giovanetti Giancarlo'] ['IT']
['Hannes Tautscher']
1003 ['Hannes Tautscher'] ['AT']
['Pelizzoli Giosue']
1004 ['Pelizzoli Giosue'] ['IT']
['Mazzei Gianni']
1005 ['Mazzei Gianni'] ['IT']
['Regelson Dan']
1006 ['Regelson Dan'] ['US']
['Muller Annabel']
1007 ['Muller Annabel'] ['DE']
['Morandi Gianni']
1008 ['Morandi Gianni'] ['IT']
['Lagrange Matthieu']
1009 ['Lagrange Matthieu'] ['FR']
['Bekaert Tim']
1010 ['Bekaert Tim'] ['BE']
['Gray Lloyd']
1011 ['Gray Lloyd'] ['GB']
['Jones David']
1012 ['Jones David'] ['GB']
['Brambilla Luca']
1013 ['Brambilla Luca'] ['IT']
['Tackmann Patrice']
1014 ['Tackmann Patrice'] ['FR']

['Obuch Jan']
1015 ['Obuch Jan'] ['SK']
['Gremeaux Denis']
1016 ['Gremeaux Denis'] ['FR']
['Gruterich Daniel']
1017 ['Gruterich Daniel'] ['DE']
['Zhong Liu']
1018 ['Zhong Liu'] ['SG']
['Tainturier Pierre Henry']
1019 ['Tainturier Pierre Henry'] ['FR']
['Simon Pascal']
1020 ['Simon Pascal'] ['FR']
['D Agostini Nico']
1021 ['D Agostini Nico'] ['IT']
['Kougioumtzis Georgios']
1022 ['Kougioumtzis Georgios'] ['GR']
['Kot Rafal']
1023 ['Kot Rafal'] ['PL']
['Pozzo Gabriele']
1024 ['Pozzo Gabriele'] ['IT']
['Orsini Mauro']
1025 ['Orsini Mauro'] ['IT']
['Flamia Stefano']
1026 ['Flamia Stefano'] ['IT']
['Digue Gwenael']
1027 ['Digue Gwenael'] ['FR']
['Cattelan Fabio']
1028 ['Cattelan Fabio'] ['IT']
['Georgopoulou Victoria']
1029 ['Georgopoulou Victoria'] ['GR']
['Uchida Norimasa']
1030 ['Uchida Norimasa'] ['JP']
['Fernandez Sylvain']
1031 ['Fernandez Sylvain'] ['FR']
['Castellain Edouard']
1032 ['Castellain Edouard'] ['FR']
['Oliver Donna']
1033 ['Oliver Donna'] ['AU']
['Hoffman Eloff']
1034 ['Hoffman Eloff'] ['ZA']
['Evangelisti Michele']
1035 ['Evangelisti Michele'] ['IT']
['Levy Sarah']
1036 ['Levy Sarah'] ['FR']
['Sato Kensuke']
1037 ['Sato Kensuke'] ['JP']
['Chinalpan Andrew Jr']
1038 ['Chinalpan Andrew Jr'] ['PH']
['Iturbe Haritz']
1039 ['Iturbe Haritz'] ['ES']
['Thillens Emma']
1040 ['Thillens Emma'] ['MQ']
['Vecco Cristina']
1041 ['Vecco Cristina'] ['IT']
['Trublin Sebastien']
1042 ['Trublin Sebastien'] ['FR']
['Caballero Bravo Isidor']
1043 ['Caballero Bravo Isidor'] ['ES']
['Driver Percy']
1044 ['Driver Percy'] ['MU']
['Di Costanzo Guido']
1045 ['Di Costanzo Guido'] ['IT']
['Gandini Maurizio']
1046 ['Gandini Maurizio'] ['IT']
['Saieva Maximiliano']
1047 ['Saieva Maximiliano'] ['IT']
['Byiers Bruce']
1048 ['Byiers Bruce'] ['BE']
['Wei Kailun']
1049 ['Wei Kailun'] ['CN']
['Bonnot Aymerick']
1050 ['Bonnot Aymerick'] ['FR']
['Mosconi Remi']
1051 ['Mosconi Remi'] ['FR']
['Menegon Alan']
1052 ['Menegon Alan'] ['IT']
['Fleisher Aaron']
1053 ['Fleisher Aaron'] ['US']
['Scatolini Paolo']
1054 ['Scatolini Paolo'] ['IT']
['Locatelli Massimo']
1055 ['Locatelli Massimo'] ['IT']
['Vacca Corrado']
1056 ['Vacca Corrado'] ['IT']
['Hayes Patrick']
1057 ['Hayes Patrick'] ['US']
['Franchet Yann']
1058 ['Franchet Yann'] ['FR']
['Braad Rasmus']
1059 ['Braad Rasmus'] ['DK']
['Cupples Richard']
1060 ['Cupples Richard'] ['CH']
['Eulogio Riccardo']
1061 ['Eulogio Riccardo'] ['IT']
['Okeeffe Mairead']
1062 ['Okeeffe Mairead'] ['IE']
['Bertolotti Gianluca']
1063 ['Bertolotti Gianluca'] ['IT']
['Espinar Garcia Francisco J.']
1064 ['Espinar Garcia Francisco J.'] ['ES']
['Morris Andrew']
1065 ['Morris Andrew'] ['GB']
['Onca Luis']
1066 ['Onca Luis'] ['PT']
['Peterson Gabe']
1067 ['Peterson Gabe'] ['US']
['Vetterli Thomas']
1068 ['Vetterli Thomas'] ['CH']
['Kolbeinsson Sigurdur Oli']
1069 ['Kolbeinsson Sigurdur Oli'] ['IS']
['Belanger Mathieu']
1070 ['Belanger Mathieu'] ['CA']
['Ventura Castells Joan']
1071 ['Ventura Castells Joan'] ['ES']
['Lahmini Karim']
1072 ['Lahmini Karim'] ['FI']
['Boutte Michel']
1073 ['Boutte Michel'] ['FR']
['Cui Zhigang']
1074 ['Cui Zhigang'] ['CN']
['Agostini Giancarla']
1075 ['Agostini Giancarla'] ['IT']
['Peterson Daniel']
1076 ['Peterson Daniel'] ['US']
['Ho Shang Wei']
1077 ['Ho Shang Wei'] ['TW']
['Huang Chi Hsien']
1078 ['Huang Chi Hsien'] ['TW']
['Chang Fengyuan']
1079 ['Chang Fengyuan'] ['TW']
['Strejac Ciprian']
1080 ['Strejac Ciprian'] ['BE']
['Yamanaka Toshiro']
1081 ['Yamanaka Toshiro'] ['JP']
['Sakamoto Akira']
1082 ['Sakamoto Akira'] ['JP']
['Nagai Hirotaka']
1083 ['Nagai Hirotaka'] ['JP']
['Ren Xiankui']
1084 ['Ren Xiankui'] ['CN']
['Rouzaud Denis']
1085 ['Rouzaud Denis'] ['CH']
['Fognani Mauro']
1086 ['Fognani Mauro'] ['IT']
['Sekkat Salim']
1087 ['Sekkat Salim'] ['MA']
['Faltsis Vasilis']
1088 ['Faltsis Vasilis'] ['GR']
['Codenotti Ivo']
1089 ['Codenotti Ivo'] ['IT']
['Blanco Pablo']
1090 ['Blanco Pablo'] ['CH']
['Dufour Franck']
1091 ['Dufour Franck'] ['FR']
['Jegerlehner Beat']
1092 ['Jegerlehner Beat'] ['US']
['Yanez Beas Carlos']
1093 ['Yanez Beas Carlos'] ['ES']
['Jacob Nicolas']
1094 ['Jacob Nicolas'] ['FR']
['Van Zyl Mc']
1095 ['Van Zyl Mc'] ['ZA']
['Menegatti Silvia']
1096 ['Menegatti Silvia'] ['IT']
['Nicoli Umberto']
1097 ['Nicoli Umberto'] ['IT']
['Vanini Romano']
1098 ['Vanini Romano'] ['IT']
['Zanella Michele']
1099 ['Zanella Michele'] ['IT']
['Boulouk Bachi Patrice']
1100 ['Boulouk Bachi Patrice'] ['FR']
['Cloarec Damien']
1101 ['Cloarec Damien'] ['RE']
['Renna Antonio']
1102 ['Renna Antonio'] ['IT']
['Chen Chih Yung']
1103 ['Chen Chih Yung'] ['TW']
['Posez Guillaume']
1104 ['Posez Guillaume'] ['FR']
['D Antonio Maurizio Giordano Bruno']
1105 ['D Antonio Maurizio Giordano Bruno'] ['FR']
['Schweyer Remi']
1106 ['Schweyer Remi'] ['FR']
['Fragniere Nicolas']
1107 ['Fragniere Nicolas'] ['CH']
['Vezzaro Paolo']
1108 ['Vezzaro Paolo'] ['IT']
['Biarese Raffaella']
1109 ['Biarese Raffaella'] ['IT']
['Come Lucio']
1110 ['Come Lucio'] ['IT']
['Paccagnella Francesco']
1111 ['Paccagnella Francesco'] ['IT']
['Longhi Marco']
1112 ['Longhi Marco'] ['IT']
['Crouteix Edouard']
1113 ['Crouteix Edouard'] ['FR']
['Fontana Rodriguez Pablo']
1114 ['Fontana Rodriguez Pablo'] ['ES']
['Lopez Toledano Victor']
1115 ['Lopez Toledano Victor'] ['ES']
['Lo Ting Sau']
1116 ['Lo Ting Sau'] ['HK']
['Bagnod Patrick']
1117 ['Bagnod Patrick'] ['IT']
['Ni Chenggang']
1118 ['Ni Chenggang'] ['CN']
['Gruttad Auria Calogero Alessandro']
1119 ['Gruttad Auria Calogero Alessandro'] ['IT']
['El Idrissi Mustafa']
1120 ['El Idrissi Mustafa'] ['BE']
['Kuhn Nicolas']
1121 ['Kuhn Nicolas'] ['FR']
['Jaeglin Emmanuelle']
1122 ['Jaeglin Emmanuelle'] ['FR']
['Petridis Derossi Gabriel']
1123 ['Petridis Derossi Gabriel'] ['CA']
['Buttignol Marco']
1124 ['Buttignol Marco'] ['IT']
['Mansouri Nacer']
1125 ['Mansouri Nacer'] ['FR']
['Toquart Aurelie']
1126 ['Toquart Aurelie'] ['FR']
['Colombo Paolo']
1127 ['Colombo Paolo'] ['IT']
['Pedretti Fabio']
1128 ['Pedretti Fabio'] ['IT']
['Roullier Stephane']
1129 ['Roullier Stephane'] ['FR']
['Stafford Nicholas']
1130 ['Stafford Nicholas'] ['US']
['Rota Jean']
1131 ['Rota Jean'] ['CH']
['Ots Margus']
1132 ['Ots Margus'] ['EE']
['Teet Leppanen']
1133 ['Teet Leppanen'] ['EE']
['Doyle Matthew']
1134 ['Doyle Matthew'] ['NL']
['Jimenez Manuel']
1135 ['Jimenez Manuel'] ['ES']
['Dell Anese Federico']
1136 ['Dell Anese Federico'] ['IT']
['Moroso Jean Francois']
1137 ['Moroso Jean Francois'] ['BE']
['Madrid Miguel']
1138 ['Madrid Miguel'] ['ES']
['Romagnoni Matteo']
1139 ['Romagnoni Matteo'] ['IT']
['Joye Damien']
1140 ['Joye Damien'] ['CH']
['Mittiga Stefania']
1141 ['Mittiga Stefania'] ['IT']
['Viezzi Manuel']
1142 ['Viezzi Manuel'] ['IT']
['Ngala Tobbias']
1143 ['Ngala Tobbias'] ['GB']
['Heine Pat']
1144 ['Heine Pat'] ['US']
['Moulinier Franck']
1145 ['Moulinier Franck'] ['FR']
['Schneekloth Martin']
1146 ['Schneekloth Martin'] ['US']
['Ruck Giles']
1147 ['Ruck Giles'] ['FR']
['Rocco Alessandro']
1148 ['Rocco Alessandro'] ['IT']
['Citarella Emiliano']
1149 ['Citarella Emiliano'] ['IT']
['Magistri Ilaria']
1150 ['Magistri Ilaria'] ['IT']
['Chen Yang']
1151 ['Chen Yang'] ['CN']
['Sato Soki']
1152 ['Sato Soki'] ['JP']
['Tobajas Calvo Jorge']
1153 ['Tobajas Calvo Jorge'] ['ES']
['Koodziej Mariusz']
1154 ['Koodziej Mariusz'] ['PL']
['Abe Takashi']
1155 ['Abe Takashi'] ['JP']
['Tornare Thierry']
1156 ['Tornare Thierry'] ['CH']
['Calvo Rodriguez Beatriz']
1157 ['Calvo Rodriguez Beatriz'] ['ES']
['Samuelsson Christian']
1158 ['Samuelsson Christian'] ['ES']
['Llorente Tamayo Rafael']
1159 ['Llorente Tamayo Rafael'] ['ES']
['Klappacher Rupert']
1160 ['Klappacher Rupert'] ['AT']
['Schiavolin Alessandro']
1161 ['Schiavolin Alessandro'] ['IT']
['Popa Oana Alina']
1162 ['Popa Oana Alina'] ['IT']
['Nagahama Yasue']
1163 ['Nagahama Yasue'] ['JP']
['Kiffel Serge']
1164 ['Kiffel Serge'] ['FR']
['Schott Gerard']
1165 ['Schott Gerard'] ['FR']
['Gondolff Jerome']
1166 ['Gondolff Jerome'] ['FR']
['Jonina Karina Jonina']
1167 ['Jonina Karina Jonina'] ['IE']
['Boglio Davide']
1168 ['Boglio Davide'] ['IT']
['Fioroni Gina']
1169 ['Fioroni Gina'] ['US']
['Ramillon Nicolas']
1170 ['Ramillon Nicolas'] ['FR']
['Bochud Emmanuel']
1171 ['Bochud Emmanuel'] ['CA']
['Brandolini Pierluigi']
1172 ['Brandolini Pierluigi'] ['IT']
['Maeda Kazutoshi']
1173 ['Maeda Kazutoshi'] ['JP']
['Ming Lang']
1174 ['Ming Lang'] ['CN']
['Pansera Fabio']
1175 ['Pansera Fabio'] ['IT']
['Alarie Jessica']
1176 ['Alarie Jessica'] ['CA']
['D Angelo Deva']
1177 ['D Angelo Deva'] ['IT']
['Cai Yu']
1178 ['Cai Yu'] ['CN']
['Ren Maozhuang']
1179 ['Ren Maozhuang'] ['CN']
['Lara Garcia Sergio']
1180 ['Lara Garcia Sergio'] ['ES']
['Melotto Andrea']
1181 ['Melotto Andrea'] ['IT']
['Risi Andrea']
1182 ['Risi Andrea'] ['US']
['Agnoletti Maurizio']
1183 ['Agnoletti Maurizio'] ['IT']
['Hernandez Avendano Asuncion']
1184 ['Hernandez Avendano Asuncion'] ['MX']
['Martina Teodoro']
1185 ['Martina Teodoro'] ['IT']
['Liu Fengling']
1186 ['Liu Fengling'] ['US']
['Vergura Carmela']
1187 ['Vergura Carmela'] ['IT']
['Caniglia Camillo']
1188 ['Caniglia Camillo'] ['IT']
['Tucci Claudio']
1189 ['Tucci Claudio'] ['IT']
['Suarez Luis']
1190 ['Suarez Luis'] ['ES']
['Huchler Elias']
1191 ['Huchler Elias'] ['GB']
['Ziller Christian']
1192 ['Ziller Christian'] ['FR']
['Markovic Dragoslav']
1193 ['Markovic Dragoslav'] ['RS']
['Spremo Aljosa']
1194 ['Spremo Aljosa'] ['RS']
['Quek Kok Kwang']
1195 ['Quek Kok Kwang'] ['SG']
['Ortiz Robert']
1196 ['Ortiz Robert'] ['FR']
['Jocic Bojan']
1197 ['Jocic Bojan'] ['RS']
['Gai Yuanpei']
1198 ['Gai Yuanpei'] ['CN']
['Dupont Ludovic']
1199 ['Dupont Ludovic'] ['FR']
['Manitto Andrea Vittorio']
1200 ['Manitto Andrea Vittorio'] ['IT']
['Benetti Paolo']
1201 ['Benetti Paolo'] ['IT']
['Piccioli Stefano']
1202 ['Piccioli Stefano'] ['IT']
['Cane Maureen']
1203 ['Cane Maureen'] ['US']
['Champion Ludovic']
1204 ['Champion Ludovic'] ['FR']
['Navarro Pablo']

1205 ['Navarro Pablo'] ['EC']
['Paoletti Giovanni']
1206 ['Paoletti Giovanni'] ['IT']
['Huppe Mathieu']
1207 ['Huppe Mathieu'] ['CA']
['Compagnoni Stefano']
1208 ['Compagnoni Stefano'] ['IT']
['Prampolini Antonio']
1209 ['Prampolini Antonio'] ['IT']
['Bodone Matteo']
1210 ['Bodone Matteo'] ['IT']
['Munarin Nicolo']
1211 ['Munarin Nicolo'] ['IT']
['Migliore Bruno']
1212 ['Migliore Bruno'] ['IT']
['Brian Agustin']
1213 ['Brian Agustin'] ['AR']
['Petrarulo Manuela']
1214 ['Petrarulo Manuela'] ['IT']
['Griffaton Pierre']
1215 ['Griffaton Pierre'] ['FR']
['Pupier Samuel']
1216 ['Pupier Samuel'] ['FR']
['Thoma Claudia']
1217 ['Thoma Claudia'] ['IT']
['Pellicciotta Filippo']
1218 ['Pellicciotta Filippo'] ['IT']
['Beier Ricardo']
1219 ['Beier Ricardo'] ['MX']
['Labisse Sebastien']
1220 ['Labisse Sebastien'] ['FR']
['Baggioli Sabina']
1221 ['Baggioli Sabina'] ['IT']
['Amati Rudi Mario']
1222 ['Amati Rudi Mario'] ['IT']
['Wysocki Loic']
1223 ['Wysocki Loic'] ['FR']
['Giacomini Gianluca']
1224 ['Giacomini Gianluca'] ['IT']
['Motta Erica']
1225 ['Motta Erica'] ['IT']
['Heng Bou']
1226 ['Heng Bou'] ['FR']
['Gostan Bojana']
1227 ['Gostan Bojana'] ['SI']
['Slobodzian Fabien']
1228 ['Slobodzian Fabien'] ['FR']
['Viizzo Mara']
1229 ['Viizzo Mara'] ['IT']
['Tsui Stella']
1230 ['Tsui Stella'] ['SG']
['Mondin Placido']
1231 ['Mondin Placido'] ['IT']
['Tibaldi Erik']
1232 ['Tibaldi Erik'] ['IT']
['Chorier Julien']
1233 ['Chorier Julien'] ['FR']
['Antonov Bozhidar']
1234 ['Antonov Bozhidar'] ['BG']
['Boifava Alessandra']
1235 ['Boifava Alessandra'] ['IT']
['Harris Rory']
1236 ['Harris Rory'] ['GB']
['Minami Keisuke']
1237 ['Minami Keisuke'] ['JP']
['Schjolberg Hallvard']
1238 ['Schjolberg Hallvard'] ['NO']
['Maida Roberto']
1239 ['Maida Roberto'] ['CH']
['Charrier Nicolas']
1240 ['Charrier Nicolas'] ['FR']
['Roberts Simon']
1241 ['Roberts Simon'] ['GB']
['Muhm David']
1242 ['Muhm David'] ['AT']
['Desto Riccardo']
1243 ['Desto Riccardo'] ['IT']
['Zacco Denise']
1244 ['Zacco Denise'] ['IT']
['Chiodi Umberto']
1245 ['Chiodi Umberto'] ['IT']
['Degraeve Jeremie']
1246 ['Degraeve Jeremie'] ['BE']
['Orsucci Massimiliano']
1247 ['Orsucci Massimiliano'] ['IT']
['Blanton Sean']
1248 ['Blanton Sean'] ['US']
['Leavesley James']
1249 ['Leavesley James'] ['GB']
['Picasso Nicola']
1250 ['Picasso Nicola'] ['ES']
['Lamothe Robin']
1251 ['Lamothe Robin'] ['FR']
['Diquattro Romain']
1252 ['Diquattro Romain'] ['FR']
['Verdaguer Font Joan Manel']
1253 ['Verdaguer Font Joan Manel'] ['ES']
['Vernet Thomas']
1254 ['Vernet Thomas'] ['FR']
['Kolaric Ivana']
1255 ['Kolaric Ivana'] ['AE']
['Dolci Luca']
1256 ['Dolci Luca'] ['IT']
['Sawyer Tom']
1257 ['Sawyer Tom'] ['GB']
['Peteri Saara']
1258 ['Peteri Saara'] ['FI']
['Belli Manuel']
1259 ['Belli Manuel'] ['IT']
['Espelleta Casinos Gustavo']
1260 ['Espelleta Casinos Gustavo'] ['ES']
['Ferraris Gianpaolo Maria']
1261 ['Ferraris Gianpaolo Maria'] ['IT']
['Valsecchi Andrea']
1262 ['Valsecchi Andrea'] ['IT']
['Lacoudanne Bertrand']
1263 ['Lacoudanne Bertrand'] ['FR']
['Dechnik Pierre']
1264 ['Dechnik Pierre'] ['FR']
['Boggian Massimiliano']
1265 ['Boggian Massimiliano'] ['IT']
['Deac Cristian']
1266 ['Deac Cristian'] ['RO']
['Tabutin Jonathan']
1267 ['Tabutin Jonathan'] ['FR']
['Leventhal Shiri']
1268 ['Leventhal Shiri'] ['IL']
['Ni Yusheng']
1269 ['Ni Yusheng'] ['CN']
['Germain Cyrille']
1270 ['Germain Cyrille'] ['FR']
['Panarello Federico']
1271 ['Panarello Federico'] ['IT']
['Renard Alexandrine']
1272 ['Renard Alexandrine'] ['BE']
['Beres Dylan']
1273 ['Beres Dylan'] ['US']
['De Carvalho Paul']
1274 ['De Carvalho Paul'] ['FR']
['Villanueva Abrahan']
1275 ['Villanueva Abrahan'] ['CO']
['Schalkx Radmer']
1276 ['Schalkx Radmer'] ['NL']
['Rigoux Pascal']
1277 ['Rigoux Pascal'] ['FR']
['Schacht Wim']
1278 ['Schacht Wim'] ['BE']
['Ramella Paia Massimo']
1279 ['Ramella Paia Massimo'] ['IT']
['Groleau Romain']
1280 ['Groleau Romain'] ['SG']
['Sanchoyerto Martinez Aitor']
1281 ['Sanchoyerto Martinez Aitor'] ['ES']
['Mazzocchi Paolo']
1282 ['Mazzocchi Paolo'] ['IT']
['Pott Julien']
1283 ['Pott Julien'] ['CH']
['Calvet Laurent']
1284 ['Calvet Laurent'] ['FR']
['Massaro Davide']
1285 ['Massaro Davide'] ['IT']
['Wiewauters Dries']
1286 ['Wiewauters Dries'] ['BE']
['Handloser Walter']
1287 ['Handloser Walter'] ['US']
['Chartie Vincent']
1288 ['Chartie Vincent'] ['FR']
['Saunier Julien']
1289 ['Saunier Julien'] ['RE']
['Li Alan']
1290 ['Li Alan'] ['HK']
['Nigri Alessandro']
1291 ['Nigri Alessandro'] ['IT']
['Cantilo Sofi']
1292 ['Cantilo Sofi'] ['AR']
['Amagata Miwa']
1293 ['Amagata Miwa'] ['JP']
['Polonioli Stefano']
1294 ['Polonioli Stefano'] ['IT']
['Pochon Matthieu']
1295 ['Pochon Matthieu'] ['FR']
['Mason Mike']
1296 ['Mason Mike'] ['US']
['Hercegfi Timo']
1297 ['Hercegfi Timo'] ['DE']
['Petrolito Laura']
1298 ['Petrolito Laura'] ['IT']
['Huille Alexandre']
1299 ['Huille Alexandre'] ['FR']
['Zhao Long']
1300 ['Zhao Long'] ['CN']
['Chiodo Emanuele']
1301 ['Chiodo Emanuele'] ['IT']
['Franceschi Lorenzo']
1302 ['Franceschi Lorenzo'] ['IT']
['Nolan Luke']
1303 ['Nolan Luke'] ['AE']
['Raynov Hristo']
1304 ['Raynov Hristo'] ['BG']
['Van Eldom Lionel']
1305 ['Van Eldom Lionel'] ['BE']
['Brenner Mylene']
1306 ['Brenner Mylene'] ['FR']
['Rossi Federico']
1307 ['Rossi Federico'] ['IT']
['Palma Riccardo']
1308 ['Palma Riccardo'] ['IT']
['Fossati Federico']
1309 ['Fossati Federico'] ['IT']
['Rossetti Ilaria']
1310 ['Rossetti Ilaria'] ['IT']
['Ziemba Damian']
1311 ['Ziemba Damian'] ['PL']
['Sobrino Pascal']
1312 ['Sobrino Pascal'] ['FR']
['Sanchez Garcia Miguel Angel']
1313 ['Sanchez Garcia Miguel Angel'] ['ES']
['Covey Kate']
1314 ['Covey Kate'] ['US']
['Quintana Macho Eloy']
1315 ['Quintana Macho Eloy'] ['ES']
['Baggio Enzo']
1316 ['Baggio Enzo'] ['IT']
['Fujita Jun']
1317 ['Fujita Jun'] ['AE']
['Barraud Laurent']
1318 ['Barraud Laurent'] ['FR']
['Roumpas Thomas']
1319 ['Roumpas Thomas'] ['GR']
['Sun Zhe']
1320 ['Sun Zhe'] ['CN']
['Piampiano Moreno']
1321 ['Piampiano Moreno'] ['IT']
['Ji Hang']
1322 ['Ji Hang'] ['FR']
['Li Chunmei']
1323 ['Li Chunmei'] ['CN']
['Daco Raphael']
1324 ['Daco Raphael'] ['BE']
['Garcia Mesa Jose Manuel']
1325 ['Garcia Mesa Jose Manuel'] ['ES']
['Stolarz Grzegorz']
1326 ['Stolarz Grzegorz'] ['PL']
['Genreith Vincent']
1327 ['Genreith Vincent'] ['BE']
['Sturiale Massimo']
1328 ['Sturiale Massimo'] ['IT']
['Tang Ying']
1329 ['Tang Ying'] ['FR']
['Chiari Guido']
1330 ['Chiari Guido'] ['IT']
['Incisa Enrico']
1331 ['Incisa Enrico'] ['IT']
['Scigalski Marcin']
1332 ['Scigalski Marcin'] ['PL']
['Boscariol Cristiano']
1333 ['Boscariol Cristiano'] ['IT']
['Molteni Valerio']
1334 ['Molteni Valerio'] ['IT']
['Arnold Andy']
1335 ['Arnold Andy'] ['GB']
['Baragiotta Stefano']
1336 ['Baragiotta Stefano'] ['IT']
['Mussa Claudia']
1337 ['Mussa Claudia'] ['IT']
['Thiebaut Christophe']
1338 ['Thiebaut Christophe'] ['FR']
['Shimokawa Aki']
1339 ['Shimokawa Aki'] ['JP']
['Petersen Heine']
1340 ['Petersen Heine'] ['NO']
['Padovani Andrea']
1341 ['Padovani Andrea'] ['IT']
['Gobillot Richard']
1342 ['Gobillot Richard'] ['FR']
['Jung Marco']
1343 ['Jung Marco'] ['DE']
['Arnason Borkur']
1344 ['Arnason Borkur'] ['IS']
['Cappelletti Riccardo']
1345 ['Cappelletti Riccardo'] ['IT']
['Moreton Chris']
1346 ['Moreton Chris'] ['GB']
['Pang Kin Sun']
1347 ['Pang Kin Sun'] ['HK']
['Data Vittoria']
1348 ['Data Vittoria'] ['IT']
['Colombo Stefano']
1349 ['Colombo Stefano'] ['IT']
['Wraith Lizzie']
1350 ['Wraith Lizzie'] ['GB']
['Poole Jason']
1351 ['Poole Jason'] ['US']
['Konttinen Juha Pekka']
1352 ['Konttinen Juha Pekka'] ['FI']
['Planelles Munoz Alfonso']
1353 ['Planelles Munoz Alfonso'] ['ES']
['Sorensen Christian']
1354 ['Sorensen Christian'] ['US']
['Hilmarsdottir Hafdis Gurun']
1355 ['Hilmarsdottir Hafdis Gurun'] ['IS']
['Amoroso Giovanni']
1356 ['Amoroso Giovanni'] ['IT']
['Jansen Lionell']
1357 ['Jansen Lionell'] ['BE']
['Negoro Yukihiko']
1358 ['Negoro Yukihiko'] ['US']
['Rautio Antti']
1359 ['Rautio Antti'] ['FI']
['Mcclymont Chris']
1360 ['Mcclymont Chris'] ['GB']
['Poskin Thierry']
1361 ['Poskin Thierry'] ['BE']
['Cardani Gianni']
1362 ['Cardani Gianni'] ['IT']
['Amalbert Julien']
1363 ['Amalbert Julien'] ['FR']
['Granelli Francesca']
1364 ['Granelli Francesca'] ['IT']

['Todesco Alberto']
1365 ['Todesco Alberto'] ['IT']
['Staples Louise']
1366 ['Staples Louise'] ['GB']
['Tanne Paul']
1367 ['Tanne Paul'] ['FR']
['Senatore Gioacchino']
1368 ['Senatore Gioacchino'] ['IT']
['Jarnefelt Elina']
1369 ['Jarnefelt Elina'] ['FI']
['Legresley Daniel']
1370 ['Legresley Daniel'] ['CA']
['Diao Shu']
1371 ['Diao Shu'] ['CN']
['Delaplace Pierre']
1372 ['Delaplace Pierre'] ['BE']
['Ventura Giuseppe']
1373 ['Ventura Giuseppe'] ['IT']
['Tang Yuen Ying']
1374 ['Tang Yuen Ying'] ['HK']
['Fondra Duilio']
1375 ['Fondra Duilio'] ['IT']
['Ricca Anna']
1376 ['Ricca Anna'] ['IT']
['Francone Simona']
1377 ['Francone Simona'] ['IT']
['Nappa Diego']
1378 ['Nappa Diego'] ['IT']
['Leonard Lucja']
1379 ['Leonard Lucja'] ['GB']
['De Longvilliers Bertrand']
1380 ['De Longvilliers Bertrand'] ['FR']
['Bryant Patty']
1381 ['Bryant Patty'] ['US']
['Gauthier Thomas']
1382 ['Gauthier Thomas'] ['FR']
['Cerminara Matteo']
1383 ['Cerminara Matteo'] ['IT']
['Gadet Damien']
1384 ['Gadet Damien'] ['FR']
['Xu Kedong']
1385 ['Xu Kedong'] ['CN']
['Fiore Paolo']
1386 ['Fiore Paolo'] ['IT']
['Rauzy Maxime']
1387 ['Rauzy Maxime'] ['FR']
['Cristo Franco']
1388 ['Cristo Franco'] ['IT']
['Molteni Francesco']
1389 ['Molteni Francesco'] ['IT']
['Danzi Stefano']
1390 ['Danzi Stefano'] ['IT']
['Rissland Olivia']
1391 ['Rissland Olivia'] ['US']
['Kyosev Dimitar']
1392 ['Kyosev Dimitar'] ['BG']
['Forrest Steve']
1393 ['Forrest Steve'] ['CA']
['Galli Alberto']
1394 ['Galli Alberto'] ['IT']
['Crump Neil']
1395 ['Crump Neil'] ['GB']
['Tadiello Federico']
1396 ['Tadiello Federico'] ['IT']
['Oloeriu Sergiu']
1397 ['Oloeriu Sergiu'] ['IT']
['Chen Ying']
1398 ['Chen Ying'] ['CN']
['Remezkov Dmitrii']
1399 ['Remezkov Dmitrii'] ['FR']
['Gao Fei']
1400 ['Gao Fei'] ['CN']
['Pandini Massimiliano']
1401 ['Pandini Massimiliano'] ['IT']
['Moia Fausto Luciano']
1402 ['Moia Fausto Luciano'] ['IT']
['Iguchi Chikako']
1403 ['Iguchi Chikako'] ['JP']
['Merle Franck']
1404 ['Merle Franck'] ['FR']
['Acerbi Maria Luisa']
1405 ['Acerbi Maria Luisa'] ['IT']
['Guerriero Diego']
1406 ['Guerriero Diego'] ['IT']
['Gonzalez Claudia']
1407 ['Gonzalez Claudia'] ['AR']
['Lee Man Kit']
1408 ['Lee Man Kit'] ['HK']
['Martinez Diez Gerard']
1409 ['Martinez Diez Gerard'] ['AD']
['Pavletic Luca']
1410 ['Pavletic Luca'] ['IT']
['Hayakawa Kumiko']
1411 ['Hayakawa Kumiko'] ['JP']
['Colet Ivan']
1412 ['Colet Ivan'] ['BE']
['Jolin Mark']
1413 ['Jolin Mark'] ['US']
['Ecoiffier Sabrina']
1414 ['Ecoiffier Sabrina'] ['NC']
['Sakurada Ko']
1415 ['Sakurada Ko'] ['JP']
['Malaspina Massimo']
1416 ['Malaspina Massimo'] ['IT']
['Pietrantonio Camilla']
1417 ['Pietrantonio Camilla'] ['IT']
['Ogasawara Hiroshi']
1418 ['Ogasawara Hiroshi'] ['JP']
['Recanzone Armando']
1419 ['Recanzone Armando'] ['IT']
['Yamamoto Masatake']
1420 ['Yamamoto Masatake'] ['JP']
['Fumagalli Luigi']
1421 ['Fumagalli Luigi'] ['IT']
['Yoshimoto Koichiro']
1422 ['Yoshimoto Koichiro'] ['JP']
['Giunzioni Davide']
1423 ['Giunzioni Davide'] ['CH']
['Ampe Drie']
1424 ['Ampe Drie'] ['BE']
['Koike Toma']
1425 ['Koike Toma'] ['JP']
['Muscatelli Pasquale']
1426 ['Muscatelli Pasquale'] ['IT']
['Delanney Alban']
1427 ['Delanney Alban'] ['FR']
['Fischer Oliver']
1428 ['Fischer Oliver'] ['CA']
['Richet Philippe']
1429 ['Richet Philippe'] ['FR']
['Drosos Evangelos']
1430 ['Drosos Evangelos'] ['IE']
['David William']
1431 ['David William'] ['FR']
['Cai Rengui']
1432 ['Cai Rengui'] ['CN']
['Kerhuel Martin']
1433 ['Kerhuel Martin'] ['FR']
['Wahlund Maria']
1434 ['Wahlund Maria'] ['SE']
['Saar Martin']
1435 ['Saar Martin'] ['DE']
['Hashimoto Miki']
1436 ['Hashimoto Miki'] ['JP']
['Cennini Samuele']
1437 ['Cennini Samuele'] ['IT']
['Regulez Kepa']
1438 ['Regulez Kepa'] ['ES']
['Smith Jonathan']
1439 ['Smith Jonathan'] ['AU']
['Antonelli Luca']
1440 ['Antonelli Luca'] ['IT']
['Berna Raymond']
1441 ['Berna Raymond'] ['FR']
['Gale Paul']
1442 ['Gale Paul'] ['GB']
['Azema Christophe']
1443 ['Azema Christophe'] ['FR']
['Oda Narumi']
1444 ['Oda Narumi'] ['JP']
['Petitjacques Danilo Giuseppe']
1445 ['Petitjacques Danilo Giuseppe'] ['IT']
['Commend Angelique']
1446 ['Commend Angelique'] ['CH']
['Saitoh Miki']
1447 ['Saitoh Miki'] ['JP']
['Guernieri Stefano']
1448 ['Guernieri Stefano'] ['IT']
['Cailleau Marie Aline']
1449 ['Cailleau Marie Aline'] ['NC']
['Hung Hunghsin']
1450 ['Hung Hunghsin'] ['TW']
['Garcia Damian Emiliano Francisco']
1451 ['Garcia Damian Emiliano Francisco'] ['AR']
['Jensen Torben C G']
1452 ['Jensen Torben C G'] ['DK']
['Di Vincenzo Hugo']
1453 ['Di Vincenzo Hugo'] ['FR']
['Graziosi Daniele']
1454 ['Graziosi Daniele'] ['IT']
['Noda Jose']
1455 ['Noda Jose'] ['VE']
['Favre Jean Claude']
1456 ['Favre Jean Claude'] ['IT']
['Jack Emma']
1457 ['Jack Emma'] ['FR']
['Compan Jean Philippe']
1458 ['Compan Jean Philippe'] ['FR']
['S G Pinto Helder']
1459 ['S G Pinto Helder'] ['PT']
['Rubenstein Gabriel']
1460 ['Rubenstein Gabriel'] ['US']
['Vigano Federico']
1461 ['Vigano Federico'] ['IT']
['Ardonfransman Jolande']
1462 ['Ardonfransman Jolande'] ['NL']
['Hj Abd Rahman Hj Abu Bakar']
1463 ['Hj Abd Rahman Hj Abu Bakar'] ['BN']
['Ong Toto']
1464 ['Ong Toto'] ['MY']
['Sirois Samuel']
1465 ['Sirois Samuel'] ['CA']
['Yong Kok Lam']
1466 ['Yong Kok Lam'] ['MY']
['Skjoedeberg Gotfred Witthoeft']
1467 ['Skjoedeberg Gotfred Witthoeft'] ['DK']
['D Alberto Nicola']
1468 ['D Alberto Nicola'] ['IT']
['Thrasyvoulos Markogiannopoulos']
1469 ['Thrasyvoulos Markogiannopoulos'] ['GR']
['Melon Jean Pierre']
1470 ['Melon Jean Pierre'] ['FR']
['Cyrill Treptow']
1471 ['Cyrill Treptow'] ['CH']
['Piselli Stephane']
1472 ['Piselli Stephane'] ['FR']
['Bouillon Jean Pascal']
1473 ['Bouillon Jean Pascal'] ['BE']
['Thiollet Francois']
1474 ['Thiollet Francois'] ['FR']
['Lorentzen ystein']
1475 ['Lorentzen ystein'] ['NO']
['Soto Aleman Ricardo']
1476 ['Soto Aleman Ricardo'] ['MX']
['Bellanger Timothee']
1477 ['Bellanger Timothee'] ['FR']
['Mc.Donagh Terencepatrick']
1478 ['Mc.Donagh Terencepatrick'] ['BO']
['Stefan Bragi Bjarnason']
1479 ['Stefan Bragi Bjarnason'] ['IS']
['Dotti Francesco Piero Dotti']
1480 ['Dotti Francesco Piero Dotti'] ['IT']
['Castangia Paolo']
1481 ['Castangia Paolo'] ['CH']
['Pitetti Fabio']
1482 ['Pitetti Fabio'] ['IT']
['Magnus Buhl']
1483 ['Magnus Buhl'] ['DE']
['O Brien David']
1484 ['O Brien David'] ['GB']
['Cazzulani Filippo']
1485 ['Cazzulani Filippo'] ['IT']
['Jimenez Roqhuett Marcelo']
1486 ['Jimenez Roqhuett Marcelo'] ['CR']
['Bosetti Luca']
1487 ['Bosetti Luca'] ['IT']
['Guisard Dafne']
1488 ['Guisard Dafne'] ['US']
['Gerber Jack']
1489 ['Gerber Jack'] ['US']
['Masanobu Inoue']
1490 ['Masanobu Inoue'] ['JP']
['Fortuna Silvano']
1491 ['Fortuna Silvano'] ['IT']
['Campion Mark']
1492 ['Campion Mark'] ['GB']
['Prosperi Luca']
1493 ['Prosperi Luca'] ['BR']
['Umezawa Miyoko']
1494 ['Umezawa Miyoko'] ['JP']
['Fabrice Barjolin']
1495 ['Fabrice Barjolin'] ['FR']
['Smith Gillian']
1496 ['Smith Gillian'] ['CA']
['Sanchez Cervi Jose M']
1497 ['Sanchez Cervi Jose M'] ['ES']
['Torre Silvere']
1498 ['Torre Silvere'] ['FR']
['Tai Hsiu Fang']
1499 ['Tai Hsiu Fang'] ['TW']
['Vlatkovic Tatiana']
1500 ['Vlatkovic Tatiana'] ['CH']
['Garcia Delgado Israel']
1501 ['Garcia Delgado Israel'] ['ES']
['Stephen Herman']
1502 ['Stephen Herman'] ['FR']
['Vitale Giovanni']
1503 ['Vitale Giovanni'] ['IT']
['Vuillermin Stefano']
1504 ['Vuillermin Stefano'] ['IT']
['Nakamura Kenji']
1505 ['Nakamura Kenji'] ['JP']
['Delafond Sandra']
1506 ['Delafond Sandra'] ['FR']
['Orehovec Ranko']
1507 ['Orehovec Ranko'] ['HR']
['D Haene Francois']
1508 ['D Haene Francois'] ['FR']
['Marmissolle Benat']
1509 ['Marmissolle Benat'] ['FR']
['Calais Louis']
1510 ['Calais Louis'] ['FR']
['Bailo Jesus']
1511 ['Bailo Jesus'] ['ES']
['Violett Zach']
1512 ['Violett Zach'] ['US']
['Piquerez Fabien']
1513 ['Piquerez Fabien'] ['FR']
['Tobias Krumm']
1514 ['Tobias Krumm'] ['DE']
['Gonczarenko Jarek']
1515 ['Gonczarenko Jarek'] ['PL']
['Springhetti Christian']
1516 ['Springhetti Christian'] ['IT']
['Hourdebaigts Maxime']
1517 ['Hourdebaigts Maxime'] ['FR']
['Morales Gerard']
1518 ['Morales Gerard'] ['ES']
['Taylor Natalie']
1519 ['Taylor Natalie'] ['GB']
['Volpi Matteo']
1520 ['Volpi Matteo'] ['IT']
['Melchio Mattia Giuseppe']
1521 ['Melchio Mattia Giuseppe'] ['IT']
['Domenighetti Nicola']
1522 ['Domenighetti Nicola'] ['CH']
['Compagnon Julien']
1523 ['Compagnon Julien'] ['CH']
['Clark Andrew']
1524 ['Clark Andrew'] ['NZ']
['Le Nocher Nicolas']
1525 ['Le Nocher Nicolas'] ['FR']
['Fitzgerald John']
1526 ['Fitzgerald John'] ['US']
['Caster Brian']
1527 ['Caster Brian'] ['JP']
['Juliussen Rasmus']
1528 ['Juliussen Rasmus'] ['DK']
['Mancisidor Arruti Igon']
1529 ['Mancisidor Arruti Igon'] ['ES']
['Lejeune Emilien']
1530 ['Lejeune Emilien'] ['FR']
['Poirot Johan']
1531 ['Poirot Johan'] ['FR']
['Allen Kaitlin']
1532 ['Allen Kaitlin'] ['US']
['Zani Lorenzo']
1533 ['Zani Lorenzo'] ['IT']
['Girard Ludovic']
1534 ['Girard Ludovic'] ['FR']
['Lorenzi Thomas']
1535 ['Lorenzi Thomas'] ['IT']
['Djiakouris Andreas']
1536 ['Djiakouris Andreas'] ['CY']
['Breuer Pierre']
1537 ['Breuer Pierre'] ['IT']
['Devalle Fabio']
1538 ['Devalle Fabio'] ['IT']
['Ferrari Fabio']
1539 ['Ferrari Fabio'] ['IT']
['Raimondo Franck']
1540 ['Raimondo Franck'] ['FR']
['Groenewegen Mike']
1541 ['Groenewegen Mike'] ['US']
['Mortimer Peter']
1542 ['Mortimer Peter'] ['US']
['Denele Matthieu']
1543 ['Denele Matthieu'] ['FR']
['Miel Antoine']
1544 ['Miel Antoine'] ['FR']
['Bouche Benoit']
1545 ['Bouche Benoit'] ['FR']
['Zheng Lumin']
1546 ['Zheng Lumin'] ['CN']
['Tocquec Aurelien']
1547 ['Tocquec Aurelien'] ['FR']
['Manganello Michael']
1548 ['Manganello Michael'] ['US']
['Nacho Zurita Gimeno']
1549 ['Nacho Zurita Gimeno'] ['ES']
['Gaillac Alexis']
1550 ['Gaillac Alexis'] ['FR']
['Chase Mark']
1551 ['Chase Mark'] ['FR']
['Uz Tolga']
1552 ['Uz Tolga'] ['TR']
['Yanis Mairy']
1553 ['Yanis Mairy'] ['FR']
['Zakrzewski Pawe']
1554 ['Zakrzewski Pawe'] ['PL']
['Mandel Etienne']
1555 ['Mandel Etienne'] ['FR']
['Bagnod Dario']
1556 ['Bagnod Dario'] ['IT']
['Van Der Jagt Luuk']
1557 ['Van Der Jagt Luuk'] ['NL']
['Legrand Marc']
1558 ['Legrand Marc'] ['FR']
['Baier Stefan']
1559 ['Baier Stefan'] ['AT']
['Logothetis Spyridon']
1560 ['Logothetis Spyridon'] ['GR']
['Martins Pedro']
1561 ['Martins Pedro'] ['PT']
['Berthe Stephane']
1562 ['Berthe Stephane'] ['FR']
['Dallago Loris']
1563 ['Dallago Loris'] ['IT']
['Nguyen Trung']
1564 ['Nguyen Trung'] ['VN']
['Loutfi Hassan']
1565 ['Loutfi Hassan'] ['IT']
['Meneghel Stephane']
1566 ['Meneghel Stephane'] ['FR']
['Riley James']
1567 ['Riley James'] ['GB']
['derud Thomas']
1568 ['derud Thomas'] ['NO']
['Fernandez Juan']
1569 ['Fernandez Juan'] ['ES']
['Vitale Alessandro']
1570 ['Vitale Alessandro'] ['IT']

['Sellberg Magnus']
1571 ['Sellberg Magnus'] ['SE']
['Zhang Zhuoming']
1572 ['Zhang Zhuoming'] ['CN']
['Turek Michal']
1573 ['Turek Michal'] ['CZ']
['Sylte Maria']
1574 ['Sylte Maria'] ['US']
['Fernandes Pedro']
1575 ['Fernandes Pedro'] ['PT']
['Benedetti Maurizio']
1576 ['Benedetti Maurizio'] ['IT']
['Dechavanne Stephane']
1577 ['Dechavanne Stephane'] ['FR']
['Pecout David']
1578 ['Pecout David'] ['FR']
['Glarey Pietro Philipe']
1579 ['Glarey Pietro Philipe'] ['IT']
['Poncet Julien']
1580 ['Poncet Julien'] ['FR']
['Ferraro Francesca']
1581 ['Ferraro Francesca'] ['IT']
['Menini Oscar']
1582 ['Menini Oscar'] ['IT']
['Berruer Eric']
1583 ['Berruer Eric'] ['FR']
['Alland Fabrice']
1584 ['Alland Fabrice'] ['FR']
['Zenoni Paolo']
1585 ['Zenoni Paolo'] ['IT']
['Ford Joanna']
1586 ['Ford Joanna'] ['CA']
['Garota Maurizio']
1587 ['Garota Maurizio'] ['IT']
['Fernemar Thomas']
1588 ['Fernemar Thomas'] ['SE']
['Parolin Alberto']
1589 ['Parolin Alberto'] ['IT']
['Dregan Pawel']
1590 ['Dregan Pawel'] ['DE']
['Pesce Ivan']
1591 ['Pesce Ivan'] ['IT']
['Garreau Antony']
1592 ['Garreau Antony'] ['FR']
['Tian Shanfu']
1593 ['Tian Shanfu'] ['CA']
['Bakas Ilias']
1594 ['Bakas Ilias'] ['GR']
['Oliveira Machado Correia Pereira Joao']
1595 ['Oliveira Machado Correia Pereira Joao'] ['PT']
['Cardoso Pedro']
1596 ['Cardoso Pedro'] ['PT']
['Bersoult Lucas']
1597 ['Bersoult Lucas'] ['FR']
['Moulis Pascal']
1598 ['Moulis Pascal'] ['FR']
['Sossai Simone']
1599 ['Sossai Simone'] ['IT']
['Ding Zhijian']
1600 ['Ding Zhijian'] ['CN']
['Bertino Chiara']
1601 ['Bertino Chiara'] ['IT']
['Thevoz Florian']
1602 ['Thevoz Florian'] ['CH']
['Berger Daniel']
1603 ['Berger Daniel'] ['CH']
['Hubbard Linda']
1604 ['Hubbard Linda'] ['FR']
['Guinement Damien']
1605 ['Guinement Damien'] ['ES']
['Kondo Nobuhiro']
1606 ['Kondo Nobuhiro'] ['JP']
['Thuegaz Gerard']
1607 ['Thuegaz Gerard'] ['CH']
['Cordeiro Arthur']
1608 ['Cordeiro Arthur'] ['BR']
['Tousch Christine']
1609 ['Tousch Christine'] ['FR']
['Marti Puig Andres']
1610 ['Marti Puig Andres'] ['ES']
['Wild Mario']
1611 ['Wild Mario'] ['TH']
['Caccamo Fabio']
1612 ['Caccamo Fabio'] ['IT']
['Owen Tim']
1613 ['Owen Tim'] ['GB']
['Snellman Janne']
1614 ['Snellman Janne'] ['FI']
['Hutchinson G Brian']
1615 ['Hutchinson G Brian'] ['IE']
['Rising Lisa']
1616 ['Rising Lisa'] ['US']
['Mostefaoui Soffyane']
1617 ['Mostefaoui Soffyane'] ['FR']
['Cibibin Caterina']
1618 ['Cibibin Caterina'] ['IT']
['Alpi Massimiliano']
1619 ['Alpi Massimiliano'] ['IT']
['D Antuono Roberto']
1620 ['D Antuono Roberto'] ['IT']
['Rouquie Celine']
1621 ['Rouquie Celine'] ['PE']
['Stevens Anthony']
1622 ['Stevens Anthony'] ['GB']
['Kratz Emily Kratz']
1623 ['Kratz Emily Kratz'] ['US']
['Barbini Raffaele']
1624 ['Barbini Raffaele'] ['IT']
['Maino Mattia']
1625 ['Maino Mattia'] ['IT']
['Ballinari Alain']
1626 ['Ballinari Alain'] ['IT']
['Lupis Alberto']
1627 ['Lupis Alberto'] ['IT']
['Bertelli Mauro']
1628 ['Bertelli Mauro'] ['IT']
['Miroshnychenko Viktor']
1629 ['Miroshnychenko Viktor'] ['UA']
['Ohl Sebastien']
1630 ['Ohl Sebastien'] ['FR']
['Alberelli Andrea']
1631 ['Alberelli Andrea'] ['IT']
['De Araujo Porto Rafael']
1632 ['De Araujo Porto Rafael'] ['BR']
['De La Roche De Bransat Eric']
1633 ['De La Roche De Bransat Eric'] ['FR']
['Colussi Mathieu']
1634 ['Colussi Mathieu'] ['FR']
['Orlow Kuba']
1635 ['Orlow Kuba'] ['PL']
['Cena Carlo']
1636 ['Cena Carlo'] ['IT']
['Clerc Manon']
1637 ['Clerc Manon'] ['FR']
['Desaymonet Nicolo']
1638 ['Desaymonet Nicolo'] ['IT']
['Rouquette David']
1639 ['Rouquette David'] ['FR']
['Pellicioli Luca']
1640 ['Pellicioli Luca'] ['IT']
['Colin Julien']
1641 ['Colin Julien'] ['FR']
['Jodogne Raphael']
1642 ['Jodogne Raphael'] ['BE']
['Stenico Simone']
1643 ['Stenico Simone'] ['IT']
['Alcoholado Francisco J. Aguilar']
1644 ['Alcoholado Francisco J. Aguilar'] ['ES']
['Silva Vittorio']
1645 ['Silva Vittorio'] ['IT']
['Coggi Andrea']
1646 ['Coggi Andrea'] ['IT']
['Joassart Martin']
1647 ['Joassart Martin'] ['BE']
['Ade Gregory']
1648 ['Ade Gregory'] ['FR']
['Dombek Magdalena']
1649 ['Dombek Magdalena'] ['DE']
['Guerard Simon']
1650 ['Guerard Simon'] ['CA']
['Din Maihazan Nurafendy']
1651 ['Din Maihazan Nurafendy'] ['MY']
['Fuzzi Andrea']
1652 ['Fuzzi Andrea'] ['IT']
['Girardi Riccardo']
1653 ['Girardi Riccardo'] ['IT']
['Casarotto Riccardo']
1654 ['Casarotto Riccardo'] ['IT']
['Yamazaki Masayoshi']
1655 ['Yamazaki Masayoshi'] ['JP']
['Kawauchi Yosuke']
1656 ['Kawauchi Yosuke'] ['JP']
['Maceroni Pietro']
1657 ['Maceroni Pietro'] ['IT']
['Knezevich Lindsay']
1658 ['Knezevich Lindsay'] ['CA']
['Santiago Alejandro']
1659 ['Santiago Alejandro'] ['MX']
['Brier Cyril']
1660 ['Brier Cyril'] ['FR']
['Lacour Bruno']
1661 ['Lacour Bruno'] ['FR']
['Georis Sebastien']
1662 ['Georis Sebastien'] ['BE']
['Vilhauer Jared']
1663 ['Vilhauer Jared'] ['US']
['Aglinskas Tomas']
1664 ['Aglinskas Tomas'] ['LT']
['Solennita Giulio']
1665 ['Solennita Giulio'] ['IT']
['Picasso Alberto']
1666 ['Picasso Alberto'] ['IT']
['Jallet Valerie']
1667 ['Jallet Valerie'] ['FR']
['Marques Dos Santos Carlos Alberto']
1668 ['Marques Dos Santos Carlos Alberto'] ['IT']
['Pelle Patrick']
1669 ['Pelle Patrick'] ['IT']
['He Shuai']
1670 ['He Shuai'] ['CN']
['Banks Kevin']
1671 ['Banks Kevin'] ['GB']
['Cabona Diego']
1672 ['Cabona Diego'] ['IT']
['Manson Paul']
1673 ['Manson Paul'] ['GB']
['Molina Maria Gabriela']
1674 ['Molina Maria Gabriela'] ['GT']
['Planas Robert']
1675 ['Planas Robert'] ['ES']
['Tuan Ismail Tuan Hafandi']
1676 ['Tuan Ismail Tuan Hafandi'] ['MY']
['Blinn Rachel']
1677 ['Blinn Rachel'] ['US']
['Roberts Christopher']
1678 ['Roberts Christopher'] ['GB']
['Volpini Federico']
1679 ['Volpini Federico'] ['IT']
['Troglia Enea Stefano']
1680 ['Troglia Enea Stefano'] ['IT']
['Pizzutti Riccardo']
1681 ['Pizzutti Riccardo'] ['IT']
['Hunt Gary']
1682 ['Hunt Gary'] ['GB']
['Nuno Filipe']
1683 ['Nuno Filipe'] ['PT']
['Ribalta Jordi']
1684 ['Ribalta Jordi'] ['ES']
['Paallysaho Juha']
1685 ['Paallysaho Juha'] ['DK']
['Casella Giuseppina']
1686 ['Casella Giuseppina'] ['IT']
['Lau Say Niong']
1687 ['Lau Say Niong'] ['MY']
['Puig Frederic']
1688 ['Puig Frederic'] ['FR']
['Mcdonough Tim']
1689 ['Mcdonough Tim'] ['CA']
['Herault Vincent']
1690 ['Herault Vincent'] ['FR']
['Song Seungyong']
1691 ['Song Seungyong'] ['KR']
['Baracco Alberto']
1692 ['Baracco Alberto'] ['IT']
['Rorig Hans Martin']
1693 ['Rorig Hans Martin'] ['DE']
['Paesante Raffaele']
1694 ['Paesante Raffaele'] ['IT']
['Compan Olmo Jose Manuel']
1695 ['Compan Olmo Jose Manuel'] ['ES']
['Martino Julia']
1696 ['Martino Julia'] ['AR']
['Reade Kirsty']
1697 ['Reade Kirsty'] ['GB']
['Zhang Huiping']
1698 ['Zhang Huiping'] ['CN']
['Simpson Stephanie']
1699 ['Simpson Stephanie'] ['CA']
['Andreoni Alberto']
1700 ['Andreoni Alberto'] ['IT']
['Boccato Stefano']
1701 ['Boccato Stefano'] ['IT']
['Uchida Hideyuki']
1702 ['Uchida Hideyuki'] ['JP']
['Park Sukhee']
1703 ['Park Sukhee'] ['KR']
['Kim Seungtae']
1704 ['Kim Seungtae'] ['KR']
['Kirilyuk Kirill']
1705 ['Kirilyuk Kirill'] ['AQ']
['Pujana Ibon']
1706 ['Pujana Ibon'] ['ES']
['Mori Paolo']
1707 ['Mori Paolo'] ['IT']
['Szukaa Damian']
1708 ['Szukaa Damian'] ['PL']
['Dumond Sylviane']
1709 ['Dumond Sylviane'] ['FR']
['Trauchessec Alain']
1710 ['Trauchessec Alain'] ['FR']
['Medard Philippe']
1711 ['Medard Philippe'] ['FR']
['Rohmer Laurent']
1712 ['Rohmer Laurent'] ['FR']
['Yanagi Yuichi']
1713 ['Yanagi Yuichi'] ['JP']
['Boi Guido']
1714 ['Boi Guido'] ['IT']
['Arthur Morris']
1715 ['Arthur Morris'] ['US']
['Dove Wayne']
1716 ['Dove Wayne'] ['FR']
['Jonkers Menno']
1717 ['Jonkers Menno'] ['NL']
['Guemas Jean Marie']
1718 ['Guemas Jean Marie'] ['FR']
['Velilla Abad Gloria']
1719 ['Velilla Abad Gloria'] ['ES']
['Velasco Barros Chelo']
1720 ['Velasco Barros Chelo'] ['ES']
['Garcia Cobos Jorge']
1721 ['Garcia Cobos Jorge'] ['ES']
['Lau Deric']
1722 ['Lau Deric'] ['SG']
['Pichler Sebastian']
1723 ['Pichler Sebastian'] ['AT']
['Svobodova Michaela']
1724 ['Svobodova Michaela'] ['CZ']
['Pecheur Charles']
1725 ['Pecheur Charles'] ['FR']
['Wiart Yves']
1726 ['Wiart Yves'] ['BE']
['Aguilar Bravo Juan Diego']
1727 ['Aguilar Bravo Juan Diego'] ['ES']
['Mazaev Andrei']
1728 ['Mazaev Andrei'] ['AQ']
['Vacca Alessandro']
1729 ['Vacca Alessandro'] ['IT']
['Cabriolu Cristiano']
1730 ['Cabriolu Cristiano'] ['IT']
['Ahonen Mikko']
1731 ['Ahonen Mikko'] ['FI']
['Rota Giovanni']
1732 ['Rota Giovanni'] ['IT']
['Afonso Franco Fernando']
1733 ['Afonso Franco Fernando'] ['ES']
['Ovidiu Dimbean']
1734 ['Ovidiu Dimbean'] ['RO']
['Takei Masayuki']
1735 ['Takei Masayuki'] ['JP']
['Calixto Anemari Daczkowski']
1736 ['Calixto Anemari Daczkowski'] ['BR']
['Lacroix Bertrand']
1737 ['Lacroix Bertrand'] ['FR']
['Ueno Koji']
1738 ['Ueno Koji'] ['JP']
['Moore Jeffrey']
1739 ['Moore Jeffrey'] ['US']
['Capra Marco']
1740 ['Capra Marco'] ['IT']
['Bertocchi Lorenzo']

1741 ['Bertocchi Lorenzo'] ['IT']
['Bahtijarevic Nikola']
1742 ['Bahtijarevic Nikola'] ['RS']
['Figuccia Federico']
1743 ['Figuccia Federico'] ['IT']
['Verde Massimiliano Gaetano']
1744 ['Verde Massimiliano Gaetano'] ['IT']
['Berto Matteo']
1745 ['Berto Matteo'] ['IT']
['Mcbride William']
1746 ['Mcbride William'] ['US']
['Madaschi Giuseppe']
1747 ['Madaschi Giuseppe'] ['IT']
['Garnier Alain']
1748 ['Garnier Alain'] ['FR']
['Gomiero Alessandro']
1749 ['Gomiero Alessandro'] ['IT']
['Grimaldi Fabrizio']
1750 ['Grimaldi Fabrizio'] ['IT']
['Carmo Luis']
1751 ['Carmo Luis'] ['PT']
['Harreither Christoph']
1752 ['Harreither Christoph'] ['AT']
['Carvalho Luis']
1753 ['Carvalho Luis'] ['PT']
['Forge Frederic']
1754 ['Forge Frederic'] ['CA']
['Piloquet Erwan']
1755 ['Piloquet Erwan'] ['FR']
['Melet Alain']
1756 ['Melet Alain'] ['FR']
['Vignoli Adriano']
1757 ['Vignoli Adriano'] ['IT']
['Zambelli Agostina']
1758 ['Zambelli Agostina'] ['IT']
['Alimonos Costa']
1759 ['Alimonos Costa'] ['US']
['Gonella Fabio Luigi']
1760 ['Gonella Fabio Luigi'] ['IT']
['Mulot Sebastien']
1761 ['Mulot Sebastien'] ['FR']
['Cardoso Antonio']
1762 ['Cardoso Antonio'] ['PT']
['Graca Nelson']
1763 ['Graca Nelson'] ['PT']
['Raigoso Ignacio']
1764 ['Raigoso Ignacio'] ['AR']
['Chan Kwok Yui']
1765 ['Chan Kwok Yui'] ['HK']
['Freret Jean Louis']
1766 ['Freret Jean Louis'] ['FR']
['Iglesias Lobato Victor']
1767 ['Iglesias Lobato Victor'] ['ES']
['Candra Sianti']
1768 ['Candra Sianti'] ['ID']
['Sandroni Cristiano']
1769 ['Sandroni Cristiano'] ['IT']
['Socci Stefano']
1770 ['Socci Stefano'] ['IT']
['Lecocq Sebastien']
1771 ['Lecocq Sebastien'] ['FR']
['Val Loic']
1772 ['Val Loic'] ['FR']
['Bolf Michal']
1773 ['Bolf Michal'] ['SK']
['Le Bras Gregory']
1774 ['Le Bras Gregory'] ['FR']
['Jiang Liangjun']
1775 ['Jiang Liangjun'] ['CN']
['Qin Gang']
1776 ['Qin Gang'] ['US']
['Khoo David Chong Beng']
1777 ['Khoo David Chong Beng'] ['MY']
['Van Der Gracht Ferdinand']
1778 ['Van Der Gracht Ferdinand'] ['BE']
['Zorzi Carlo']
1779 ['Zorzi Carlo'] ['IT']
['Tirelli Mattia']
1780 ['Tirelli Mattia'] ['IT']
['Tieghi Gianluca']
1781 ['Tieghi Gianluca'] ['IT']
['Duncan Toby']
1782 ['Duncan Toby'] ['GB']
['Tassone Lorenzo']
1783 ['Tassone Lorenzo'] ['IT']
['Karalias John']
1784 ['Karalias John'] ['GR']
['Joselon Olivier']
1785 ['Joselon Olivier'] ['FR']
['Cassis Stefano']
1786 ['Cassis Stefano'] ['IT']
['Faure Olivier']
1787 ['Faure Olivier'] ['FR']
['Berger Laurent']
1788 ['Berger Laurent'] ['FR']
['Ciarfaglia Giuseppe Roberto']
1789 ['Ciarfaglia Giuseppe Roberto'] ['IT']
['Grasland Jean Pierre']
1790 ['Grasland Jean Pierre'] ['FR']
['Hakime Bezza']
1791 ['Hakime Bezza'] ['CA']
['Cozzi Marco Giampietro']
1792 ['Cozzi Marco Giampietro'] ['IT']
['Orlandi Edoardo']
1793 ['Orlandi Edoardo'] ['IT']
['Okabe Akiko']
1794 ['Okabe Akiko'] ['JP']
['Kayser Jean']
1795 ['Kayser Jean'] ['BE']
['Rausin Brice']
1796 ['Rausin Brice'] ['BE']
['Melotti Alessio']
1797 ['Melotti Alessio'] ['IT']
['Pareti Alberto']
1798 ['Pareti Alberto'] ['IT']
['Lucchini Riccardo']
1799 ['Lucchini Riccardo'] ['IT']
['Caramia Pietro']
1800 ['Caramia Pietro'] ['IT']
['Jun Xu']
1801 ['Jun Xu'] ['CN']
['Doninelli Daniele']
1802 ['Doninelli Daniele'] ['IT']
['Mazzoleni Gianluca']
1803 ['Mazzoleni Gianluca'] ['IT']
['Jambert Mickael']
1804 ['Jambert Mickael'] ['FR']
['Ueda Masahiro']
1805 ['Ueda Masahiro'] ['JP']
['Furunes Erling']
1806 ['Furunes Erling'] ['NO']
['Castagna Massimo']
1807 ['Castagna Massimo'] ['IT']
['Ohmura Soichi']
1808 ['Ohmura Soichi'] ['JP']
['Panteri Vasileia']
1809 ['Panteri Vasileia'] ['GR']
['Rana Francesco']
1810 ['Rana Francesco'] ['IT']
['Wong Chin Ee']
1811 ['Wong Chin Ee'] ['MY']
['Catapano Enrico']
1812 ['Catapano Enrico'] ['IT']
['Jung Filhwa']
1813 ['Jung Filhwa'] ['KR']
['Giusti Marco']
1814 ['Giusti Marco'] ['IT']
['Aquila Davide']
1815 ['Aquila Davide'] ['IT']
['Pennacchi Osvaldo']
1816 ['Pennacchi Osvaldo'] ['IT']
['Skrzypek Alexander']
1817 ['Skrzypek Alexander'] ['DE']
['Baggio Eros']
1818 ['Baggio Eros'] ['IT']
['Sgro Ceravolo Silvio']
1819 ['Sgro Ceravolo Silvio'] ['IT']
['Barthet Vincent']
1820 ['Barthet Vincent'] ['FR']
['Caraffa Mirco']
1821 ['Caraffa Mirco'] ['IT']
['Barbieri Diego']
1822 ['Barbieri Diego'] ['IT']
['Ho Yuen Loong']
1823 ['Ho Yuen Loong'] ['MY']
['Oh Jin Heng']
1824 ['Oh Jin Heng'] ['MY']
['Lim Siok Har']
1825 ['Lim Siok Har'] ['MY']
['Ku Seng Lip']
1826 ['Ku Seng Lip'] ['MY']
['Lee Beng Siong']
1827 ['Lee Beng Siong'] ['MY']
['Ng Lem Chee']
1828 ['Ng Lem Chee'] ['SG']
['Thenot Philippe']
1829 ['Thenot Philippe'] ['US']
['Rocca Marco']
1830 ['Rocca Marco'] ['IT']
['Kuusi Sami']
1831 ['Kuusi Sami'] ['FI']
['Daffini Angela']
1832 ['Daffini Angela'] ['IT']
['Stromko Michal']
1833 ['Stromko Michal'] ['SK']
['Fillette Sylvain']
1834 ['Fillette Sylvain'] ['FR']
['Airoldi Daniele']
1835 ['Airoldi Daniele'] ['IT']
['Gambare Marco']
1836 ['Gambare Marco'] ['IT']
['Park Gillsoo']
1837 ['Park Gillsoo'] ['KR']
['Kandemir B Stk']
1838 ['Kandemir B Stk'] ['TR']
['Laissus Nicolas']
1839 ['Laissus Nicolas'] ['FR']
['Travaillot Laurent']
1840 ['Travaillot Laurent'] ['FR']
['Liu Shangpeng']
1841 ['Liu Shangpeng'] ['IT']
['Kusumoto Shuichiro']
1842 ['Kusumoto Shuichiro'] ['JP']
['Guido Silvia']
1843 ['Guido Silvia'] ['IT']
['Brikas Theo']
1844 ['Brikas Theo'] ['CH']
['Beretta Marco']
1845 ['Beretta Marco'] ['IT']
['Meisch Disco']
1846 ['Meisch Disco'] ['US']
['Paris Thierry']
1847 ['Paris Thierry'] ['FR']
['Tak Hyoung Suk']
1848 ['Tak Hyoung Suk'] ['KR']
['Mcgee Eric']
1849 ['Mcgee Eric'] ['CA']
['Bomboi Ivano']
1850 ['Bomboi Ivano'] ['IT']
['Lakio Laura']
1851 ['Lakio Laura'] ['FI']
['Kumlien Jason']
1852 ['Kumlien Jason'] ['US']
['Li Lei']
1853 ['Li Lei'] ['CN']
['Jinno Tomonori']
1854 ['Jinno Tomonori'] ['JP']
['Lee Garam']
1855 ['Lee Garam'] ['KR']
['Vanacker Benoit']
1856 ['Vanacker Benoit'] ['FR']
['Fukuhara Yuichi']
1857 ['Fukuhara Yuichi'] ['JP']
['Nakano Takaaki']
1858 ['Nakano Takaaki'] ['JP']
['Christophe Naudin']
1859 ['Christophe Naudin'] ['FR']
['Bennett Sophie']
1860 ['Bennett Sophie'] ['FR']
['Lu Sheming']
1861 ['Lu Sheming'] ['CN']
['Zhang Bochao']
1862 ['Zhang Bochao'] ['CN']
['Mcconaughy Joseph']
1863 ['Mcconaughy Joseph'] ['US']
['Avenier Delphine']
1864 ['Avenier Delphine'] ['FR']
['Sommer Corina']
1865 ['Sommer Corina'] ['CH']
['Corsini Claudio']
1866 ['Corsini Claudio'] ['IT']
['Cirla Carlo Alberto']
1867 ['Cirla Carlo Alberto'] ['IT']
['Cedano Sergio']
1868 ['Cedano Sergio'] ['BR']
['Lehtonen Juha']
1869 ['Lehtonen Juha'] ['FI']
['Pellegrini Andrea']
1870 ['Pellegrini Andrea'] ['IT']
['Fioroni Massimo']
1871 ['Fioroni Massimo'] ['IT']
['Balduzzi Elena']
1872 ['Balduzzi Elena'] ['IT']
['Verstraete Kaz']
1873 ['Verstraete Kaz'] ['BE']
['Vaisanen Matti']
1874 ['Vaisanen Matti'] ['FI']
['Maksimainen Ville']
1875 ['Maksimainen Ville'] ['FI']
['Oppo Massimiliano']
1876 ['Oppo Massimiliano'] ['IT']
['Puydupin Sophie']
1877 ['Puydupin Sophie'] ['FR']
['Cane Mauro']
1878 ['Cane Mauro'] ['IT']
['Fairman Alex']
1879 ['Fairman Alex'] ['GB']
['Lim Handa']
1880 ['Lim Handa'] ['SG']
['Fisker Peter']
1881 ['Fisker Peter'] ['DK']
['Martinez Raya Francisco Manuel']
1882 ['Martinez Raya Francisco Manuel'] ['ES']
['Yeung Ka Lun']
1883 ['Yeung Ka Lun'] ['HK']
['Platini Martino']
1884 ['Platini Martino'] ['IT']
['Ferramondo Daniele']
1885 ['Ferramondo Daniele'] ['IT']
['Camarda Stefano']
1886 ['Camarda Stefano'] ['IT']
['Jeannet Gael']
1887 ['Jeannet Gael'] ['IT']
['Mignano Marco']
1888 ['Mignano Marco'] ['IT']
['Donghi Andrea']
1889 ['Donghi Andrea'] ['IT']
['Chiriotti Lorenzo']
1890 ['Chiriotti Lorenzo'] ['IT']
['Pinton Flavio']
1891 ['Pinton Flavio'] ['IT']
['Gavriil Charalampos Antonios']
1892 ['Gavriil Charalampos Antonios'] ['GR']
['Beletoiu Claudiu']
1893 ['Beletoiu Claudiu'] ['RO']
['Bonato Daniele']
1894 ['Bonato Daniele'] ['IT']
['Park Kwangwon']
1895 ['Park Kwangwon'] ['KR']
['Lometto Filippo']
1896 ['Lometto Filippo'] ['IT']
['Seo Soono']
1897 ['Seo Soono'] ['KR']
['Kim Minhee']
1898 ['Kim Minhee'] ['KR']
['Annaloro Christophe']
1899 ['Annaloro Christophe'] ['FR']
['Kodym Matthias']
1900 ['Kodym Matthias'] ['AT']
['Paoli Massimiliano']
1901 ['Paoli Massimiliano'] ['IT']
['Taylor James']
1902 ['Taylor James'] ['GB']
['Garnier David']
1903 ['Garnier David'] ['FR']
['Hanspal Ajay']
1904 ['Hanspal Ajay'] ['GB']
['Del Valle Herve']
1905 ['Del Valle Herve'] ['FR']
['Warmlander Anna']
1906 ['Warmlander Anna'] ['SE']
['Ritchie James']
1907 ['Ritchie James'] ['GB']
['Mustonen Petri']
1908 ['Mustonen Petri'] ['FI']
['Yasukochi Taito']
1909 ['Yasukochi Taito'] ['JP']
['Kingo Gunnar']
1910 ['Kingo Gunnar'] ['EE']
['Lasserre Francois']
1911 ['Lasserre Francois'] ['FR']
['Vento Giuseppe']
1912 ['Vento Giuseppe'] ['IT']
['Boizeau Jean']
1913 ['Boizeau Jean'] ['FR']
['Deramaix Mickael']
1914 ['Deramaix Mickael'] ['FR']
['Locci Philippe']
1915 ['Locci Philippe'] ['FR']
['Fujioka Masazumi']
1916 ['Fujioka Masazumi'] ['US']
['Guldbjrnsen Johan Andre']
1917 ['Guldbjrnsen Johan Andre'] ['NO']
['Kohler Victor']
1918 ['Kohler Victor'] ['FR']
['Buron Eric']
1919 ['Buron Eric'] ['FR']
['Garcia Pacheco Jordi']
1920 ['Garcia Pacheco Jordi'] ['ES']
['Sotillo Antoni']
1921 ['Sotillo Antoni'] ['ES']
['Casas Mendez Nicolas']
1922 ['Casas Mendez Nicolas'] ['AD']
['Giuliano Vittorio']
1923 ['Giuliano Vittorio'] ['IT']
['Delpierre Jean Luc']
1924 ['Delpierre Jean Luc'] ['BE']
['Connesson Laurent']
1925 ['Connesson Laurent'] ['FR']
['Ene Robert']
1926 ['Ene Robert'] ['GB']
['Caviglia Jerome']
1927 ['Caviglia Jerome'] ['FR']
['Williams Jonathan']
1928 ['Williams Jonathan'] ['GB']
['Andries Ann']
1929 ['Andries Ann'] ['BE']
['Larsson Bo']
1930 ['Larsson Bo'] ['DK']

['Zanotti Roberta']
1931 ['Zanotti Roberta'] ['IT']
['Yan Fei']
1932 ['Yan Fei'] ['CN']
['Lamaud Christophe']
1933 ['Lamaud Christophe'] ['FR']
['Markogiannopoulos Thrasyvoulos']
1934 ['Markogiannopoulos Thrasyvoulos'] ['GR']
['Schnitzer Johannes']
1935 ['Schnitzer Johannes'] ['CH']
['Hoyas Jimenez Luis']
1936 ['Hoyas Jimenez Luis'] ['ES']
['Jones Tim']
1937 ['Jones Tim'] ['GB']
['Vanzandt Marie']
1938 ['Vanzandt Marie'] ['US']
['Mazzon Mauro']
1939 ['Mazzon Mauro'] ['IT']
['Mossman Dawson']
1940 ['Mossman Dawson'] ['CA']
['Scandella Giulio']
1941 ['Scandella Giulio'] ['IT']
['Frino Stefano']
1942 ['Frino Stefano'] ['IT']
['Finnegan Irene']
1943 ['Finnegan Irene'] ['IE']
['Belometti Arnaldo']
1944 ['Belometti Arnaldo'] ['IT']
['Pilzer Mattia']
1945 ['Pilzer Mattia'] ['IT']
['Sheffield Drew']
1946 ['Sheffield Drew'] ['GB']
['Travaglini Gianluca']
1947 ['Travaglini Gianluca'] ['IT']
['Li Qiuhua']
1948 ['Li Qiuhua'] ['CN']
['Urabe Koji']
1949 ['Urabe Koji'] ['JP']
['Kamkoum Adam']
1950 ['Kamkoum Adam'] ['FR']
['Iles Aaron']
1951 ['Iles Aaron'] ['US']
['Marabese Ennio']
1952 ['Marabese Ennio'] ['IT']
['Abe Hiroshi']
1953 ['Abe Hiroshi'] ['JP']
['Blandin Fabrice']
1954 ['Blandin Fabrice'] ['FR']
['Tassan Toffola Mauro']
1955 ['Tassan Toffola Mauro'] ['IT']
['Kjeldsberg Mona']
1956 ['Kjeldsberg Mona'] ['NO']
['Martini Roberto']
1957 ['Martini Roberto'] ['IT']
['Visintin Lorenza']
1958 ['Visintin Lorenza'] ['IT']
['Scarano Pamela']
1959 ['Scarano Pamela'] ['IT']
['Li Wai Leung']
1960 ['Li Wai Leung'] ['HK']
['Scribano Massimo']
1961 ['Scribano Massimo'] ['IT']
['Carnevali Giorgio']
1962 ['Carnevali Giorgio'] ['IT']
['Mangini Angelo']
1963 ['Mangini Angelo'] ['IT']
['Rogorz Piotr']
1964 ['Rogorz Piotr'] ['PL']
['Hardy Serge']
1965 ['Hardy Serge'] ['FR']
['Wiwatsriprapha Puttasit']
1966 ['Wiwatsriprapha Puttasit'] ['TH']
['Cheng Angie']
1967 ['Cheng Angie'] ['HK']
['Chapple Baden']
1968 ['Chapple Baden'] ['AU']
['Suzuki Kanna']
1969 ['Suzuki Kanna'] ['JP']
['Ruille Jezequel Guillaume']
1970 ['Ruille Jezequel Guillaume'] ['FR']
['Massimi Francesco']
1971 ['Massimi Francesco'] ['IT']
['Xu Min']
1972 ['Xu Min'] ['CN']
['Savage Vicky']
1973 ['Savage Vicky'] ['GB']
['Burgazzi Alberto']
1974 ['Burgazzi Alberto'] ['IT']
['Sund Marc']
1975 ['Sund Marc'] ['DE']
['Andre Michael']
1976 ['Andre Michael'] ['FR']
['Orschiedt Jonathan']
1977 ['Orschiedt Jonathan'] ['DE']
['Fourez Pascal']
1978 ['Fourez Pascal'] ['BE']
['Vautrot Marine']
1979 ['Vautrot Marine'] ['FR']
['Ferrero Jerome']
1980 ['Ferrero Jerome'] ['FR']
['Molczyk ukasz']
1981 ['Molczyk ukasz'] ['PL']
['Kunz Ryan']
1982 ['Kunz Ryan'] ['US']
['Giusto Stefano']
1983 ['Giusto Stefano'] ['IT']
['Maran Stefano']
1984 ['Maran Stefano'] ['IT']
['Kaufmann Benjamin']
1985 ['Kaufmann Benjamin'] ['FR']
['Burdin Thomas']
1986 ['Burdin Thomas'] ['FR']
['Zinfolino Federica']
1987 ['Zinfolino Federica'] ['IT']
['Tazo Masahiro']
1988 ['Tazo Masahiro'] ['JP']
['Van Ranst Wiebe']
1989 ['Van Ranst Wiebe'] ['BE']
['Vilaseca Manuela']
1990 ['Vilaseca Manuela'] ['ES']
['Keane Conor']
1991 ['Keane Conor'] ['IE']
['Nunes Manuel']
1992 ['Nunes Manuel'] ['PT']
['Tam Chun Fung']
1993 ['Tam Chun Fung'] ['HK']
['Paris Giovanni']
1994 ['Paris Giovanni'] ['IT']
['Massignani Roberto']
1995 ['Massignani Roberto'] ['IT']
['Riban Denis']
1996 ['Riban Denis'] ['IT']
['Lau Kam Fai']
1997 ['Lau Kam Fai'] ['HK']
['Oswald Vicky']
1998 ['Oswald Vicky'] ['US']
['Grassi Matteo']
1999 ['Grassi Matteo'] ['IT']
['Kim Bongjae']
2000 ['Kim Bongjae'] ['KR']
['Kim Youngsun']
2001 ['Kim Youngsun'] ['KR']
['Van Duijl Susan']
2002 ['Van Duijl Susan'] ['NL']
['Zhang Dong']
2003 ['Zhang Dong'] ['CN']
['De Gennaro Laurent']
2004 ['De Gennaro Laurent'] ['FR']
['Guan Huajie']
2005 ['Guan Huajie'] ['CN']
['Blanchet Juliette']
2006 ['Blanchet Juliette'] ['FR']
['Rosset Rene']
2007 ['Rosset Rene'] ['IT']
['Bouche Jean Maxime']
2008 ['Bouche Jean Maxime'] ['GP']
['Kramer Lord Jens']
2009 ['Kramer Lord Jens'] ['IT']
['Del Re Domenico']
2010 ['Del Re Domenico'] ['IT']
['Zoratti Mauro']
2011 ['Zoratti Mauro'] ['IT']
['Weiss Wilfried']
2012 ['Weiss Wilfried'] ['DE']
['Wu Diesel']
2013 ['Wu Diesel'] ['CN']
['Coll Roland']
2014 ['Coll Roland'] ['FR']
['Surace Fabio']
2015 ['Surace Fabio'] ['IT']
['Beretta Gisella']
2016 ['Beretta Gisella'] ['IT']
['Marisco Nelson']
2017 ['Marisco Nelson'] ['BR']
['Canni Ferrari Eugenio Maria']
2018 ['Canni Ferrari Eugenio Maria'] ['IT']
['Fiore Jean Pascal']
2019 ['Fiore Jean Pascal'] ['FR']
['Regaldo Renzo']
2020 ['Regaldo Renzo'] ['IT']
['Lee Kok Cheu']
2021 ['Lee Kok Cheu'] ['SG']
['Harkat Cedric']
2022 ['Harkat Cedric'] ['FR']
['Borra Paolo']
2023 ['Borra Paolo'] ['IT']
['Kruk Sawomir']
2024 ['Kruk Sawomir'] ['PL']
['Luengo Silvio Eduardo']
2025 ['Luengo Silvio Eduardo'] ['IT']
['Tischer Jason']
2026 ['Tischer Jason'] ['US']
['Fanuel Francois']
2027 ['Fanuel Francois'] ['FR']
['Weber Pierre']
2028 ['Weber Pierre'] ['FR']
['Snyder Stephen']
2029 ['Snyder Stephen'] ['US']
['Morniroli Alessandro']
2030 ['Morniroli Alessandro'] ['IT']
['Kim Moon Hwan']
2031 ['Kim Moon Hwan'] ['KR']
['Lee Boram']
2032 ['Lee Boram'] ['KR']
['Lee Chunghyun']
2033 ['Lee Chunghyun'] ['KR']
['Lee Jee Hee']
2034 ['Lee Jee Hee'] ['KR']
['Gan Wei Yong']
2035 ['Gan Wei Yong'] ['SG']
['Gkountovas Dimitrios']
2036 ['Gkountovas Dimitrios'] ['GR']
['Hong Keumji']
2037 ['Hong Keumji'] ['KR']
['Jaciow Brent']
2038 ['Jaciow Brent'] ['CH']
['Orsingher Celine']
2039 ['Orsingher Celine'] ['FR']
['Taillon Richard']
2040 ['Taillon Richard'] ['CA']
['Huppertz Gaetan']
2041 ['Huppertz Gaetan'] ['BE']
['Ghio Valentina']
2042 ['Ghio Valentina'] ['IT']
['Poomski Daniel']
2043 ['Poomski Daniel'] ['PL']
['Castille Cedric']
2044 ['Castille Cedric'] ['GB']
['Pled Karine']
2045 ['Pled Karine'] ['FR']
['Barberis Negra Marzia']
2046 ['Barberis Negra Marzia'] ['IT']
['Ockeloen Frank']
2047 ['Ockeloen Frank'] ['NL']
['Papaleo Maurizio']
2048 ['Papaleo Maurizio'] ['IT']
['Goyeneche Gerard']
2049 ['Goyeneche Gerard'] ['FR']
['Li Ning']
2050 ['Li Ning'] ['DE']
['Davies Rob']
2051 ['Davies Rob'] ['US']
['Griffiths Bea']
2052 ['Griffiths Bea'] ['GB']
['Durand Claudio']
2053 ['Durand Claudio'] ['IT']
['Stefan Mateschke']
2054 ['Stefan Mateschke'] ['DE']
['Morris Benjamin']
2055 ['Morris Benjamin'] ['GB']
['Perboni Enrico']
2056 ['Perboni Enrico'] ['IT']
['Travostino Luca']
2057 ['Travostino Luca'] ['IT']
['Liu Zishu']
2058 ['Liu Zishu'] ['CN']
['Qu Minwei']
2059 ['Qu Minwei'] ['US']
['Meunier Jerome']
2060 ['Meunier Jerome'] ['FR']
['Trempala Cheryl']
2061 ['Trempala Cheryl'] ['US']
['Persson Andy']
2062 ['Persson Andy'] ['GB']
['Coll Theo']
2063 ['Coll Theo'] ['FR']
['Quirini Ewa']
2064 ['Quirini Ewa'] ['NZ']
['Yang Qifan']
2065 ['Yang Qifan'] ['CN']
['Leung Wan Yee']
2066 ['Leung Wan Yee'] ['HK']
['Hatori Yumi']
2067 ['Hatori Yumi'] ['JP']
['Mcloughlin Seamus']
2068 ['Mcloughlin Seamus'] ['IE']
['Baraniuk Yurii']
2069 ['Baraniuk Yurii'] ['IT']
['Cazzaniga Federico']
2070 ['Cazzaniga Federico'] ['IT']
['Laka Zelaia Inaki']
2071 ['Laka Zelaia Inaki'] ['ES']
['Foldes Dionyz']
2072 ['Foldes Dionyz'] ['SK']
['Chou Tzu Chen']
2073 ['Chou Tzu Chen'] ['TW']
['Mocellin Alessandro']
2074 ['Mocellin Alessandro'] ['IT']
['Debeuf Luc']
2075 ['Debeuf Luc'] ['BE']
['Van De Bergh Ingo']
2076 ['Van De Bergh Ingo'] ['NL']
['Tam Tak Seng']
2077 ['Tam Tak Seng'] ['MO']
['Lau Man To']
2078 ['Lau Man To'] ['HK']
['Bianchi Michele']
2079 ['Bianchi Michele'] ['IT']
['Payen Charles']
2080 ['Payen Charles'] ['FR']
['Gerber Patrick']
2081 ['Gerber Patrick'] ['CH']
['De Bruyne Bass']
2082 ['De Bruyne Bass'] ['BE']
['Kouider Leon']
2083 ['Kouider Leon'] ['FR']
['Sapone Fabrizio']
2084 ['Sapone Fabrizio'] ['IT']
['Nguyen Hieu']
2085 ['Nguyen Hieu'] ['VN']
['Tsukamura Hiroshi']
2086 ['Tsukamura Hiroshi'] ['JP']
['An Xiaofang']
2087 ['An Xiaofang'] ['CN']
['Barjolin Fabrice']
2088 ['Barjolin Fabrice'] ['FR']
['Jimenez Trenado Roberto']
2089 ['Jimenez Trenado Roberto'] ['ES']
['Okabe Takahiro']
2090 ['Okabe Takahiro'] ['JP']
['Li Xuesheng']
2091 ['Li Xuesheng'] ['CN']
['Autuori_Spitz Guilherme']
2092 ['Autuori_Spitz Guilherme'] ['BR']
['Quek Quek Ngak Jui']
2093 ['Quek Quek Ngak Jui'] ['MY']
['Fabries Stephane']
2094 ['Fabries Stephane'] ['FR']
['Adrian Scott']
2095 ['Adrian Scott'] ['GB']
['Sato Daisuke']
2096 ['Sato Daisuke'] ['JP']
['Volpe Rinonapoli Luca']
2097 ['Volpe Rinonapoli Luca'] ['IT']
['Sebastien Gerard']
2098 ['Sebastien Gerard'] ['FR']
['Bionaz Thierry']
2099 ['Bionaz Thierry'] ['IT']
['Ishikawa Koichi']
2100 ['Ishikawa Koichi'] ['JP']
['Suzuki Miki']
2101 ['Suzuki Miki'] ['JP']
['Kaneko Tsuyoshi']
2102 ['Kaneko Tsuyoshi'] ['FR']
['Jacquard Melicenne']
2103 ['Jacquard Melicenne'] ['BE']
['Rodriguez Pinzon Jose Antonio']
2104 ['Rodriguez Pinzon Jose Antonio'] ['CO']

['Calvi Stefano']
2105 ['Calvi Stefano'] ['IT']
['Pirinoli Giacomo']
2106 ['Pirinoli Giacomo'] ['IT']
['Assassa Yann Joel']
2107 ['Assassa Yann Joel'] ['FR']
['Kusumoto Sumiko']
2108 ['Kusumoto Sumiko'] ['JP']
['Xenos Miltos']
2109 ['Xenos Miltos'] ['GR']
['Auterives Florence']
2110 ['Auterives Florence'] ['FR']
['Rossi Stefano']
2111 ['Rossi Stefano'] ['IT']
['Khoo Hock Meng Wain']
2112 ['Khoo Hock Meng Wain'] ['SG']
['Korting Axel']
2113 ['Korting Axel'] ['DE']
['Takase Haruo']
2114 ['Takase Haruo'] ['JP']
['Livertoux Bruno']
2115 ['Livertoux Bruno'] ['FR']
['Christophe Magliano']
2116 ['Christophe Magliano'] ['FR']
['Grosso Eugenio']
2117 ['Grosso Eugenio'] ['IT']
['Lermat Michel']
2118 ['Lermat Michel'] ['FR']
['Gregorini Davide']
2119 ['Gregorini Davide'] ['IT']
['Ovcharov Denys']
2120 ['Ovcharov Denys'] ['UA']
['Struc Saso']
2121 ['Struc Saso'] ['SI']
['Quan Netzer']
2122 ['Quan Netzer'] ['GT']
['Teffo Olivier']
2123 ['Teffo Olivier'] ['FR']
['Orengo Giorgio']
2124 ['Orengo Giorgio'] ['IT']
['Boglioni Alessandra']
2125 ['Boglioni Alessandra'] ['IT']
['Rossini Luca']
2126 ['Rossini Luca'] ['IT']
['Higuchi Ayumi']
2127 ['Higuchi Ayumi'] ['JP']
['Horvath Peter']
2128 ['Horvath Peter'] ['HU']
['Mussou Marc']
2129 ['Mussou Marc'] ['FR']
['Meiser Franz']
2130 ['Meiser Franz'] ['DE']
['Mahfoud Meryem']
2131 ['Mahfoud Meryem'] ['MA']
['Massimelli Giorgio']
2132 ['Massimelli Giorgio'] ['IT']
['Boulay Fabien']
2133 ['Boulay Fabien'] ['FR']
['Manley Dirk']
2134 ['Manley Dirk'] ['US']
['Travaillot Marie Laure']
2135 ['Travaillot Marie Laure'] ['FR']
['Arouca Rui']
2136 ['Arouca Rui'] ['ZA']
['Feng Joanne']
2137 ['Feng Joanne'] ['FR']
['Hashizume Ichiro']
2138 ['Hashizume Ichiro'] ['FR']
['Petrovic Milos']
2139 ['Petrovic Milos'] ['RS']
['Tomlinson Max']
2140 ['Tomlinson Max'] ['GB']
['Mu Jie']
2141 ['Mu Jie'] ['CN']
['Jorioz Romano']
2142 ['Jorioz Romano'] ['IT']
['Lefebvre Stephane']
2143 ['Lefebvre Stephane'] ['FR']
['Hasman Alexa']
2144 ['Hasman Alexa'] ['US']
['Gaubert Claude']
2145 ['Gaubert Claude'] ['FR']
['Lombardo Roberto']
2146 ['Lombardo Roberto'] ['IT']
['Falk Engler']
2147 ['Falk Engler'] ['DE']
['Gunawan Santih']
2148 ['Gunawan Santih'] ['ID']
['Laglia Marco']
2149 ['Laglia Marco'] ['SM']
['Boscaro Cristian']
2150 ['Boscaro Cristian'] ['IT']
['Vinzia Alain']
2151 ['Vinzia Alain'] ['CH']
['Choi Yuet San']
2152 ['Choi Yuet San'] ['HK']
['Vaudry Franck']
2153 ['Vaudry Franck'] ['FR']
['Bonizzoni Emilio Giuliano Maria']
2154 ['Bonizzoni Emilio Giuliano Maria'] ['IT']
['Yamazaki Takahiro']
2155 ['Yamazaki Takahiro'] ['JP']
['Del Giorgio Danilo']
2156 ['Del Giorgio Danilo'] ['IT']
['Giacomini Giacomo']
2157 ['Giacomini Giacomo'] ['IT']
['Penate Suarez Fermin']
2158 ['Penate Suarez Fermin'] ['ES']
['Boothroyd Dave']
2159 ['Boothroyd Dave'] ['GB']
['Laufer Ken']
2160 ['Laufer Ken'] ['US']
['Semprini Roberto']
2161 ['Semprini Roberto'] ['IT']
['Campese Stefano']
2162 ['Campese Stefano'] ['IT']
['Spreafico Chiara']
2163 ['Spreafico Chiara'] ['IT']
['Ennis King Jonathan']
2164 ['Ennis King Jonathan'] ['AU']
['Yamaguchi Osamu']
2165 ['Yamaguchi Osamu'] ['JP']
['Diener Mattias']
2166 ['Diener Mattias'] ['SE']
['Andreu Sugranes Jordi']
2167 ['Andreu Sugranes Jordi'] ['ES']
['Pellicone Massimo']
2168 ['Pellicone Massimo'] ['IT']
['Hannes Pesserer']
2169 ['Hannes Pesserer'] ['AT']
['Favrel Jerome']
2170 ['Favrel Jerome'] ['FR']
['Dickson George']
2171 ['Dickson George'] ['GB']
['Rispal Yann']
2172 ['Rispal Yann'] ['FR']
['Ying Jun']
2173 ['Ying Jun'] ['CN']
['Serdino Claudio']
2174 ['Serdino Claudio'] ['IT']
['Guelpa Rolone Valentina']
2175 ['Guelpa Rolone Valentina'] ['IT']
['Tuberga Enrico']
2176 ['Tuberga Enrico'] ['IT']
['Eder Sigrid']
2177 ['Eder Sigrid'] ['AT']
['Papaevangelou Nikolaos']
2178 ['Papaevangelou Nikolaos'] ['CH']
['Gregorini Filippo']
2179 ['Gregorini Filippo'] ['IT']
['Kobayashi Daiki']
2180 ['Kobayashi Daiki'] ['JP']
['Fortin Caroline']
2181 ['Fortin Caroline'] ['CA']
['Tahtinen Jaakko']
2182 ['Tahtinen Jaakko'] ['FI']
['Leo Simone']
2183 ['Leo Simone'] ['IT']
['Lee Sangsin']
2184 ['Lee Sangsin'] ['KR']
['Saint Jean Sebastian']
2185 ['Saint Jean Sebastian'] ['AR']
['Baik Myungki']
2186 ['Baik Myungki'] ['KR']
['Kim Juae']
2187 ['Kim Juae'] ['KR']
['Choi Changhyu']
2188 ['Choi Changhyu'] ['KR']
['Zhang Zhang Wenjun']
2189 ['Zhang Zhang Wenjun'] ['CN']
['Arbizu Patxi']
2190 ['Arbizu Patxi'] ['ES']
['Raichon Sebastien']
2191 ['Raichon Sebastien'] ['FR']
['Benvenuto Enzo']
2192 ['Benvenuto Enzo'] ['IT']
['Perez Valero Albert']
2193 ['Perez Valero Albert'] ['ES']
['Olivier Romain']
2194 ['Olivier Romain'] ['FR']
['Cerlini Stefano']
2195 ['Cerlini Stefano'] ['IT']
['Bignell Alister']
2196 ['Bignell Alister'] ['GB']
['Jumisko Juha']
2197 ['Jumisko Juha'] ['FI']
['Allieta Andrea']
2198 ['Allieta Andrea'] ['IT']
['Boggio Chiara']
2199 ['Boggio Chiara'] ['IT']
['Koop Jason']
2200 ['Koop Jason'] ['US']
['Petr Kucera']
2201 ['Petr Kucera'] ['CZ']
['Annovazzi Giancarlo']
2202 ['Annovazzi Giancarlo'] ['IT']
['Clap Cesare']
2203 ['Clap Cesare'] ['IT']
['Bertelle Alessandro']
2204 ['Bertelle Alessandro'] ['IT']
['Le Clainche Pierre']
2205 ['Le Clainche Pierre'] ['FR']
['Chen Bo']
2206 ['Chen Bo'] ['CN']
['Niwa Kaori']
2207 ['Niwa Kaori'] ['JP']
['Passaquay Florian']
2208 ['Passaquay Florian'] ['FR']
['Billet Jean Marc']
2209 ['Billet Jean Marc'] ['FR']
['Giordano Ivan']
2210 ['Giordano Ivan'] ['IT']
['Depaoli Mattia']
2211 ['Depaoli Mattia'] ['IT']
['Gross Annemarie']
2212 ['Gross Annemarie'] ['IT']
['Kirsic Igor']
2213 ['Kirsic Igor'] ['HR']
['Dietrich Christophe']
2214 ['Dietrich Christophe'] ['FR']
['Souloumiac Arnaud']
2215 ['Souloumiac Arnaud'] ['FR']
['Meoli Andrea']
2216 ['Meoli Andrea'] ['IT']
['Salt Zoe']
2217 ['Salt Zoe'] ['GB']
['Fagereng Ake']
2218 ['Fagereng Ake'] ['NO']
['Straumann Alain']
2219 ['Straumann Alain'] ['CH']
['Piceu Darcy']
2220 ['Piceu Darcy'] ['US']
['Moog Paul']
2221 ['Moog Paul'] ['FR']
['Figueroa Lago Antonio']
2222 ['Figueroa Lago Antonio'] ['ES']
['Hopwood Paul']
2223 ['Hopwood Paul'] ['GB']
['Turgeon Richard']
2224 ['Turgeon Richard'] ['CA']
['Luca Marconi']
2225 ['Luca Marconi'] ['IT']
['Rosati Luciano']
2226 ['Rosati Luciano'] ['IT']
['Bonandrini Paolo']
2227 ['Bonandrini Paolo'] ['IT']
['Gu Xibo']
2228 ['Gu Xibo'] ['CN']
['Guasina Giorgio']
2229 ['Guasina Giorgio'] ['IT']
['Beletoiu Claudiu Ionel']
2230 ['Beletoiu Claudiu Ionel'] ['RO']
['Curtil Raphael']
2231 ['Curtil Raphael'] ['FR']
['Tardivel Bruno']
2232 ['Tardivel Bruno'] ['FR']
['Charreau Benoist']
2233 ['Charreau Benoist'] ['FR']
['Zhou Daoting']
2234 ['Zhou Daoting'] ['CN']
['Henry Patrice']
2235 ['Henry Patrice'] ['FR']
['Sciarretta Christian']
2236 ['Sciarretta Christian'] ['IT']
['Maisonnier Paul']
2237 ['Maisonnier Paul'] ['FR']
['Tani Nobuya']
2238 ['Tani Nobuya'] ['JP']
['Deshaies Eric']
2239 ['Deshaies Eric'] ['CA']
['Cortese Gianpiero']
2240 ['Cortese Gianpiero'] ['IT']
['Moreno Novello']
2241 ['Moreno Novello'] ['IT']
['Vassalli Davide']
2242 ['Vassalli Davide'] ['CH']
['Venneugues Alban']
2243 ['Venneugues Alban'] ['FR']
['Fumat Michel']
2244 ['Fumat Michel'] ['FR']
['Buitrago Oscar']
2245 ['Buitrago Oscar'] ['CO']
['Guilera Monica']
2246 ['Guilera Monica'] ['ES']
['Rossi Claudio']
2247 ['Rossi Claudio'] ['IT']
['Colabello Luigi']
2248 ['Colabello Luigi'] ['IT']
['Miehe Azzouz Manuel']
2249 ['Miehe Azzouz Manuel'] ['FR']
['Schlosser Frank']
2250 ['Schlosser Frank'] ['FR']
['Pemsel Dennis']
2251 ['Pemsel Dennis'] ['DE']
['De Colle Rodolfo']
2252 ['De Colle Rodolfo'] ['IT']
['Szerda Gabriel']
2253 ['Szerda Gabriel'] ['AU']
['Gemelli Ezio']
2254 ['Gemelli Ezio'] ['IT']
['Agnoli Cristian']
2255 ['Agnoli Cristian'] ['IT']
['Gilardoni Alessandro']
2256 ['Gilardoni Alessandro'] ['IT']
['Francisco Flavio']
2257 ['Francisco Flavio'] ['PT']
['Sanglas Ayats Josep']
2258 ['Sanglas Ayats Josep'] ['ES']
['England Stephen']
2259 ['England Stephen'] ['GB']
['Mauro Abbate']
2260 ['Mauro Abbate'] ['IT']
['Iotti Sebastien']
2261 ['Iotti Sebastien'] ['FR']
['Anthonioz Pierre']
2262 ['Anthonioz Pierre'] ['FR']
['Goeringer Patrick']
2263 ['Goeringer Patrick'] ['FR']
['Mrtinez Jose']
2264 ['Mrtinez Jose'] ['ES']
['Doiron Guy']
2265 ['Doiron Guy'] ['CA']
['Khrapko Sergii']
2266 ['Khrapko Sergii'] ['UA']
['Letourneau Benoit']
2267 ['Letourneau Benoit'] ['CA']
['Quinaou Yannick']
2268 ['Quinaou Yannick'] ['FR']
['Hayes Steve']
2269 ['Hayes Steve'] ['GB']
['Sperka Tamas']
2270 ['Sperka Tamas'] ['HU']
['Vukotic Dejan']
2271 ['Vukotic Dejan'] ['SI']
['Fink Alain']
2272 ['Fink Alain'] ['BE']
['Vazquez Blas']
2273 ['Vazquez Blas'] ['ES']
['Vogel Timo']
2274 ['Vogel Timo'] ['DE']
['Pietrelli Enrico']
2275 ['Pietrelli Enrico'] ['IT']
['Gentilini Iader']
2276 ['Gentilini Iader'] ['IT']
['Xiong Pengpeng']
2277 ['Xiong Pengpeng'] ['CN']
['Ottobon Davis']
2278 ['Ottobon Davis'] ['IT']
['Tiziano Rolando']
2279 ['Tiziano Rolando'] ['IT']
['Balestri Micheke']
2280 ['Balestri Micheke'] ['IT']
['Biondi Chiara']
2281 ['Biondi Chiara'] ['IT']
['Urizar Jose']
2282 ['Urizar Jose'] ['CH']
['Saevarsoon Birgir']
2283 ['Saevarsoon Birgir'] ['IS']
['Neale Matt']
2284 ['Neale Matt'] ['GB']
['Barret Fabien']
2285 ['Barret Fabien'] ['FR']
['Jeanson Hubert']
2286 ['Jeanson Hubert'] ['FR']
['Chpak Duncan']
2287 ['Chpak Duncan'] ['FR']
['Romano Enrico']
2288 ['Romano Enrico'] ['IT']
['Busca Andrea']
2289 ['Busca Andrea'] ['IT']
['Gay Jean Philippe']
2290 ['Gay Jean Philippe'] ['FR']
['Guyonnet Wilfrid']
2291 ['Guyonnet Wilfrid'] ['FR']
['Codern Guillem']
2292 ['Codern Guillem'] ['ES']
['Heath Richard']
2293 ['Heath Richard'] ['GB']
['Caccia Daniele']
2294 ['Caccia Daniele'] ['IT']
['Omar Motta']
2295 ['Omar Motta'] ['IT']
['Lassila Ilkka']
2296 ['Lassila Ilkka'] ['FI']
['Yamamoto Takashi']
2297 ['Yamamoto Takashi'] ['JP']
['Forcelledo Cesar']
2298 ['Forcelledo Cesar'] ['ES']
['Fernandez Blanco Fernando']
2299 ['Fernandez Blanco Fernando'] ['ES']

['Bastrentaz Claudio']
2300 ['Bastrentaz Claudio'] ['IT']
['Rosenstein Frederic']
2301 ['Rosenstein Frederic'] ['FR']
['Ishida Kensei']
2302 ['Ishida Kensei'] ['JP']
['Denis Wischniewski']
2303 ['Denis Wischniewski'] ['DE']
['Luca Bonfante']
2304 ['Luca Bonfante'] ['IT']
['Visse Stephane']
2305 ['Visse Stephane'] ['FR']
['Perez Minana Ricard']
2306 ['Perez Minana Ricard'] ['ES']
['Salendres JeanChristophe']
2307 ['Salendres JeanChristophe'] ['FR']
['Ageorges Fabrice']
2308 ['Ageorges Fabrice'] ['FR']
['Sousa Pedro']
2309 ['Sousa Pedro'] ['PT']
['Brignoli Cristian']
2310 ['Brignoli Cristian'] ['IT']
['Compagnoni Gustavo']
2311 ['Compagnoni Gustavo'] ['AR']
['Ekse Kaisa']
2312 ['Ekse Kaisa'] ['FI']
['Bauer Erwin']
2313 ['Bauer Erwin'] ['DE']
['Gil Frederic']
2314 ['Gil Frederic'] ['FR']
['Carranza Miguel']
2315 ['Carranza Miguel'] ['AR']
['Nasser Miguel Jose']
2316 ['Nasser Miguel Jose'] ['ES']
['Yoshizawa Madoka']
2317 ['Yoshizawa Madoka'] ['JP']
['Puaud Olivier']
2318 ['Puaud Olivier'] ['FR']
['Marchi Mauro']
2319 ['Marchi Mauro'] ['IT']
['Alba Raul']
2320 ['Alba Raul'] ['ES']
['Akimoto Tsuneo']
2321 ['Akimoto Tsuneo'] ['JP']
['Musina Antonello']
2322 ['Musina Antonello'] ['IT']
['Robert Denis']
2323 ['Robert Denis'] ['FR']
['Humphrey Andy']
2324 ['Humphrey Andy'] ['GB']
['Bremmers Paul']
2325 ['Bremmers Paul'] ['NL']
['Juri Maraldo']
2326 ['Juri Maraldo'] ['IT']
['Serena Stefano']
2327 ['Serena Stefano'] ['IT']
['Poetto Giovanni']
2328 ['Poetto Giovanni'] ['IT']
['Olivier John Lee']
2329 ['Olivier John Lee'] ['FR']
['Rao Shashwat']
2330 ['Rao Shashwat'] ['IN']
['Fohrmeister Volker']
2331 ['Fohrmeister Volker'] ['DE']
['Bigard Alain']
2332 ['Bigard Alain'] ['FR']
['Bassanoni Paolo']
2333 ['Bassanoni Paolo'] ['IT']
['Barucco Federico']
2334 ['Barucco Federico'] ['IT']
['Plasmanne Maxime']
2335 ['Plasmanne Maxime'] ['BE']
['Yu Hongyan']
2336 ['Yu Hongyan'] ['CN']
['Zhang Zhang Hu']
2337 ['Zhang Zhang Hu'] ['CN']
['Rossier Francois']
2338 ['Rossier Francois'] ['CH']
['Hugot Jean Victor']
2339 ['Hugot Jean Victor'] ['FR']
['Blanc Elisabeth']
2340 ['Blanc Elisabeth'] ['FR']
['LHeureux Yvan']
2341 ['LHeureux Yvan'] ['CA']
['Roux William']
2342 ['Roux William'] ['FR']
['Carminati Mirko']
2343 ['Carminati Mirko'] ['IT']
['Falcy Jean Pierre']
2344 ['Falcy Jean Pierre'] ['FR']
['Zanotti Paolo']
2345 ['Zanotti Paolo'] ['IT']
['Pretti Giovanni']
2346 ['Pretti Giovanni'] ['IT']
['Chapuis Serge']
2347 ['Chapuis Serge'] ['FR']
['Camacho Noelia']
2348 ['Camacho Noelia'] ['ES']
['Watkins Natalia']
2349 ['Watkins Natalia'] ['GB']
['Thomas Joel']
2350 ['Thomas Joel'] ['NZ']
['Smith Hugo']
2351 ['Smith Hugo'] ['GB']
['Heine Patrick']
2352 ['Heine Patrick'] ['US']
['Draskovic Igor']
2353 ['Draskovic Igor'] ['HR']
['Braun Paul Andre']
2354 ['Braun Paul Andre'] ['FR']
['Brunazzi Carlo']
2355 ['Brunazzi Carlo'] ['IT']
['Renson Patrice']
2356 ['Renson Patrice'] ['BE']
['Rebillard Sylvain']
2357 ['Rebillard Sylvain'] ['CH']
['Bidault Florian']
2358 ['Bidault Florian'] ['FR']
['Ferrero Alberto']
2359 ['Ferrero Alberto'] ['IT']
['Vandelli Andrea']
2360 ['Vandelli Andrea'] ['IT']
['Cruz Diego']
2361 ['Cruz Diego'] ['EC']
['Silvio Ogliaro']
2362 ['Silvio Ogliaro'] ['IT']
['Adnet Abel']
2363 ['Adnet Abel'] ['FR']
['Giabardo Fulvio']
2364 ['Giabardo Fulvio'] ['IT']
['Marchi Giovanni']
2365 ['Marchi Giovanni'] ['IT']
['Ito Tomohiko']
2366 ['Ito Tomohiko'] ['JP']
['Yamamoto Akira']
2367 ['Yamamoto Akira'] ['JP']
['Van Ryswyck Michael']
2368 ['Van Ryswyck Michael'] ['ZA']
['Francheteau Anthony']
2369 ['Francheteau Anthony'] ['FR']
['Joao Rodrigo']
2370 ['Joao Rodrigo'] ['BR']
['Bonsembiante Nicholas']
2371 ['Bonsembiante Nicholas'] ['IT']
['Michetti Andrea']
2372 ['Michetti Andrea'] ['IT']
['Chen Wen Tsan']
2373 ['Chen Wen Tsan'] ['TW']
['Milani Andrea']
2374 ['Milani Andrea'] ['IT']
['Codina Nuria']
2375 ['Codina Nuria'] ['ES']
['Durand Marc']
2376 ['Durand Marc'] ['FR']
['Parent Jerome']
2377 ['Parent Jerome'] ['FR']
['Filipovic Jelena']
2378 ['Filipovic Jelena'] ['RS']
['Podrzycki Marc']
2379 ['Podrzycki Marc'] ['FR']
['Bourdilloud Christophe']
2380 ['Bourdilloud Christophe'] ['CH']
['Davidsson Jonas']
2381 ['Davidsson Jonas'] ['SE']
['Giorgio Bertolo']
2382 ['Giorgio Bertolo'] ['IT']
['Vecchi Manuele']
2383 ['Vecchi Manuele'] ['IT']
['Riccardi Omar']
2384 ['Riccardi Omar'] ['IT']
['Monteyrimard Alain']
2385 ['Monteyrimard Alain'] ['FR']
['Madonnini Daniele']
2386 ['Madonnini Daniele'] ['IT']
['Pujal Carabantes Pep']
2387 ['Pujal Carabantes Pep'] ['AD']
['Limousin Anthony']
2388 ['Limousin Anthony'] ['FR']
['You Raphael']
2389 ['You Raphael'] ['FR']
['Calas Olivier']
2390 ['Calas Olivier'] ['FR']
['Amosso Gaspare Matteo']
2391 ['Amosso Gaspare Matteo'] ['IT']
['Pastorino Mauro']
2392 ['Pastorino Mauro'] ['IT']
['Mcallister Marco Sean']
2393 ['Mcallister Marco Sean'] ['IT']
['Ceci Adeodato']
2394 ['Ceci Adeodato'] ['IT']
['Benvenuti Vittorio']
2395 ['Benvenuti Vittorio'] ['IT']
['Otomo Rui']
2396 ['Otomo Rui'] ['JP']
['Inoue Chizuru']
2397 ['Inoue Chizuru'] ['JP']
['Jang Youngcho']
2398 ['Jang Youngcho'] ['KR']
['Montelimard Francois']
2399 ['Montelimard Francois'] ['FR']
['Peluyet Bruno']
2400 ['Peluyet Bruno'] ['FR']
['Solomakhin Dmitry']
2401 ['Solomakhin Dmitry'] ['GB']
['Bendotti Sabrina']
2402 ['Bendotti Sabrina'] ['IT']
['Jiang Bin']
2403 ['Jiang Bin'] ['CN']
['Heizmann Thomas']
2404 ['Heizmann Thomas'] ['DE']
['Ober Pierrot']
2405 ['Ober Pierrot'] ['FR']
['Yamada Hirofumi']
2406 ['Yamada Hirofumi'] ['JP']
['Clerc Jean Marc']
2407 ['Clerc Jean Marc'] ['FR']
['Mancini Marco']
2408 ['Mancini Marco'] ['IT']
['Brogniez Sylvain']
2409 ['Brogniez Sylvain'] ['FR']
['Couret Jacques']
2410 ['Couret Jacques'] ['FR']
['Zhang Xingru']
2411 ['Zhang Xingru'] ['CN']
['Rodriguez Sanchez Jose Angel']
2412 ['Rodriguez Sanchez Jose Angel'] ['ES']
['Cal Mitchell']
2413 ['Cal Mitchell'] ['CA']
['Fondriest Alberto']
2414 ['Fondriest Alberto'] ['IT']
['Pelletier Pierre']
2415 ['Pelletier Pierre'] ['GB']
['Dorn Andreas']
2416 ['Dorn Andreas'] ['CH']
['Davis Matthew']
2417 ['Davis Matthew'] ['GB']
['Pincetti Enrico']
2418 ['Pincetti Enrico'] ['IT']
['Ndlovu Sophia']
2419 ['Ndlovu Sophia'] ['DE']
['Tramolay Sebastien']
2420 ['Tramolay Sebastien'] ['FR']
['Gomez Hugo Fernando']
2421 ['Gomez Hugo Fernando'] ['CO']
['Lodo Simone']
2422 ['Lodo Simone'] ['IT']
['Leva Giovanni Luca']
2423 ['Leva Giovanni Luca'] ['IT']
['Padovani Danilo']
2424 ['Padovani Danilo'] ['IT']
['Regazzoni Massimo']
2425 ['Regazzoni Massimo'] ['IT']
['Ochoa Liliana']
2426 ['Ochoa Liliana'] ['CO']
['Zarandieta Mendez Patxi']
2427 ['Zarandieta Mendez Patxi'] ['ES']
['Pinatel Eugenio Riccardo']
2428 ['Pinatel Eugenio Riccardo'] ['IT']
['Vorobev Evgenii']
2429 ['Vorobev Evgenii'] ['RU']
['Dukino Jacqueline']
2430 ['Dukino Jacqueline'] ['AU']
['Faella Samuel']
2431 ['Faella Samuel'] ['IT']
['Zanardi Carlo']
2432 ['Zanardi Carlo'] ['IT']
['Pizzamiglio Luca']
2433 ['Pizzamiglio Luca'] ['IT']
['Menicucci Roberto']
2434 ['Menicucci Roberto'] ['IT']
['Cavallo Roberto']
2435 ['Cavallo Roberto'] ['IT']
['Martins Jorge']
2436 ['Martins Jorge'] ['FR']
['Albert Pascal']
2437 ['Albert Pascal'] ['FR']
['Doyen Frederic']
2438 ['Doyen Frederic'] ['FR']
['Horton Roch']
2439 ['Horton Roch'] ['US']
['Tscherny Florian']
2440 ['Tscherny Florian'] ['AT']
['Turcanu Dinu']
2441 ['Turcanu Dinu'] ['RO']
['Temperli Philippe']
2442 ['Temperli Philippe'] ['CH']
['Gauthier Dominique']
2443 ['Gauthier Dominique'] ['FR']
['Amarotti Giovanni']
2444 ['Amarotti Giovanni'] ['IT']
['Peracchiotti Alberto']
2445 ['Peracchiotti Alberto'] ['IT']
['Zanoni Paolo']
2446 ['Zanoni Paolo'] ['IT']
['Bustard Chris']
2447 ['Bustard Chris'] ['US']
['Aujard Jean Paul']
2448 ['Aujard Jean Paul'] ['FR']
['Pelletier Bertrand']
2449 ['Pelletier Bertrand'] ['FR']
['Narbaiza Joseba']
2450 ['Narbaiza Joseba'] ['ES']
['Belar Gomez De Segura Iker']
2451 ['Belar Gomez De Segura Iker'] ['ES']
['Orr David']
2452 ['Orr David'] ['CA']
['Yu Changjiu']
2453 ['Yu Changjiu'] ['CN']
['Dessi Davide']
2454 ['Dessi Davide'] ['IT']
['Huber Sigrid']
2455 ['Huber Sigrid'] ['AT']
['Kotalakidis Konstantinos']
2456 ['Kotalakidis Konstantinos'] ['GR']
['Antonini Massimo']
2457 ['Antonini Massimo'] ['IT']
['Bruno Roberto']
2458 ['Bruno Roberto'] ['IT']
['Cortassa Diego']
2459 ['Cortassa Diego'] ['IT']
['Lambiase Manuele']
2460 ['Lambiase Manuele'] ['IT']
['Allolio Vittorio']
2461 ['Allolio Vittorio'] ['IT']
['Houstin Vincent']
2462 ['Houstin Vincent'] ['FR']
['Xu Wenwei']
2463 ['Xu Wenwei'] ['CN']
['Windal Emmanuel']
2464 ['Windal Emmanuel'] ['FR']
['Windal Pierre']
2465 ['Windal Pierre'] ['FR']
['Gianola Fabio']
2466 ['Gianola Fabio'] ['IT']
['Camillo Caniglia']
2467 ['Camillo Caniglia'] ['IT']
['Hoo Bryan']
2468 ['Hoo Bryan'] ['SG']
['Carminati Daniele']
2469 ['Carminati Daniele'] ['IT']
['Charrance Lorella']
2470 ['Charrance Lorella'] ['IT']
['Gerard Dante']
2471 ['Gerard Dante'] ['IT']
['Castelli Simonetta']
2472 ['Castelli Simonetta'] ['IT']
['Paolo Benetti']
2473 ['Paolo Benetti'] ['IT']
['Capili Aleksis']
2474 ['Capili Aleksis'] ['PH']
['Douvier Dominique']
2475 ['Douvier Dominique'] ['FR']
['Falso Daniele']
2476 ['Falso Daniele'] ['IT']
['Olcsak Jozsef']
2477 ['Olcsak Jozsef'] ['HU']
['Thomas Will']
2478 ['Thomas Will'] ['US']

['Ishida Yuki']
2479 ['Ishida Yuki'] ['JP']
['Ruffier Erik']
2480 ['Ruffier Erik'] ['IT']
['Miringu Victor Kamau']
2481 ['Miringu Victor Kamau'] ['KE']
['Gandini Andrea']
2482 ['Gandini Andrea'] ['IT']
['Isidori Luca']
2483 ['Isidori Luca'] ['IT']
['Alberti Giulia']
2484 ['Alberti Giulia'] ['IT']
['Bisson Luciano']
2485 ['Bisson Luciano'] ['IT']
['Takuya Oda']
2486 ['Takuya Oda'] ['JP']
['Oliver Munar Mateu']
2487 ['Oliver Munar Mateu'] ['ES']
['Amabrini Fabio']
2488 ['Amabrini Fabio'] ['IT']
['Froelicher Vincent']
2489 ['Froelicher Vincent'] ['FR']
['Papi Marco']
2490 ['Papi Marco'] ['IT']
['Pellegatta Gianluca']
2491 ['Pellegatta Gianluca'] ['IT']
['Vanetti Marco']
2492 ['Vanetti Marco'] ['IT']
['Remondaz Sergio']
2493 ['Remondaz Sergio'] ['IT']
['Voillaume Fabrice']
2494 ['Voillaume Fabrice'] ['FR']
['Maranzana Eric']
2495 ['Maranzana Eric'] ['FR']
['Caminita Vincenzo']
2496 ['Caminita Vincenzo'] ['IT']
['Hun Hunghsin']
2497 ['Hun Hunghsin'] ['TW']
['Di Giannantonio Gianluca']
2498 ['Di Giannantonio Gianluca'] ['IT']
['Vandermolen Sebastiaan']
2499 ['Vandermolen Sebastiaan'] ['BE']
['Vandewiele Christoph']
2500 ['Vandewiele Christoph'] ['BE']
['Spiniella Daniele']
2501 ['Spiniella Daniele'] ['IT']
['Pu Aimin']
2502 ['Pu Aimin'] ['CN']
['Finetto Albino']
2503 ['Finetto Albino'] ['IT']
['Perbellini Davide']
2504 ['Perbellini Davide'] ['IT']
['Mueller Annabel']
2505 ['Mueller Annabel'] ['DE']
['Uragami Kenji']
2506 ['Uragami Kenji'] ['JP']
['Gao Zhongkun']
2507 ['Gao Zhongkun'] ['CN']
['Yang Liming']
2508 ['Yang Liming'] ['CN']
['Gerardin Rodrigo']
2509 ['Gerardin Rodrigo'] ['AR']
['Mussi Josef']
2510 ['Mussi Josef'] ['IT']
['Gao Zhigang']
2511 ['Gao Zhigang'] ['CN']
['Ancellin Christophe']
2512 ['Ancellin Christophe'] ['FR']
['Sardi Aldo Pietro Stefano']
2513 ['Sardi Aldo Pietro Stefano'] ['IT']
['Bazin Mathieu']
2514 ['Bazin Mathieu'] ['FR']
['Dalfino Davide']
2515 ['Dalfino Davide'] ['IT']
['Ban Akimi']
2516 ['Ban Akimi'] ['JP']
['Uno Takayuki']
2517 ['Uno Takayuki'] ['JP']
['Rossi Laurent']
2518 ['Rossi Laurent'] ['FR']
['Fornara Davide']
2519 ['Fornara Davide'] ['IT']
['Tsukada Ayumu']
2520 ['Tsukada Ayumu'] ['JP']
['Yanagihara Takashi']
2521 ['Yanagihara Takashi'] ['JP']
['Ghirelli Eugenio']
2522 ['Ghirelli Eugenio'] ['IT']
['Trabucchi Pietro']
2523 ['Trabucchi Pietro'] ['IT']
['Mosca Fabiano']
2524 ['Mosca Fabiano'] ['IT']
['Rota Romina']
2525 ['Rota Romina'] ['IT']
['Cervasi Philippe']
2526 ['Cervasi Philippe'] ['FR']
['Bonnevialle Christophe']
2527 ['Bonnevialle Christophe'] ['FR']
['Konda Kazumi']
2528 ['Konda Kazumi'] ['JP']
['Frisullo Roberto']
2529 ['Frisullo Roberto'] ['IT']
['Martin Olivier']
2530 ['Martin Olivier'] ['FR']
['Framarin Sergio']
2531 ['Framarin Sergio'] ['IT']
['Rosati Michele']
2532 ['Rosati Michele'] ['IT']
['Cambiano Giorgio']
2533 ['Cambiano Giorgio'] ['IT']
['Mauro Nacci']
2534 ['Mauro Nacci'] ['IT']
['Laperche Marc']
2535 ['Laperche Marc'] ['FR']
['Gerville Philippe']
2536 ['Gerville Philippe'] ['FR']
['Cui Yibing']
2537 ['Cui Yibing'] ['CN']
['Roveta Tomaso']
2538 ['Roveta Tomaso'] ['IT']
['Canton Anna Lisa']
2539 ['Canton Anna Lisa'] ['IT']
['Gonzalez Solis Alejandra']
2540 ['Gonzalez Solis Alejandra'] ['MX']
['Ermacora Marco']
2541 ['Ermacora Marco'] ['IT']
['Castellaro Marco']
2542 ['Castellaro Marco'] ['IT']
['Balli Niccolo']
2543 ['Balli Niccolo'] ['IT']
['Pezzetti Paolo']
2544 ['Pezzetti Paolo'] ['IT']
['Joly Yannick']
2545 ['Joly Yannick'] ['IT']
['Gerard Antonio']
2546 ['Gerard Antonio'] ['IT']
['Haughton Timothy']
2547 ['Haughton Timothy'] ['GB']
['Kirui Cheruiyot']
2548 ['Kirui Cheruiyot'] ['KE']
['Bastian Jacek']
2549 ['Bastian Jacek'] ['PL']
['Hsieh Chang Lin']
2550 ['Hsieh Chang Lin'] ['TW']
['Corsico Annamaria']
2551 ['Corsico Annamaria'] ['IT']
['Faivre Demoly Pierre Hugues']
2552 ['Faivre Demoly Pierre Hugues'] ['FR']
['Aeberli Fabien']
2553 ['Aeberli Fabien'] ['FR']
['Ait Abdelmaleck Seddik']
2554 ['Ait Abdelmaleck Seddik'] ['FR']
['Allaire Jean Philippe']
2555 ['Allaire Jean Philippe'] ['FR']
['Aloisi Fabrizio']
2556 ['Aloisi Fabrizio'] ['IT']
['Amoretti Stefano']
2557 ['Amoretti Stefano'] ['IT']
['Andrea Schena']
2558 ['Andrea Schena'] ['IT']
['Arnould Aurore']
2559 ['Arnould Aurore'] ['FR']
['Azzoug Said']
2560 ['Azzoug Said'] ['FR']
['Balagat Ramil']
2561 ['Balagat Ramil'] ['PH']
['Baranzelli Davide']
2562 ['Baranzelli Davide'] ['IT']
['Barbarit Marion']
2563 ['Barbarit Marion'] ['FR']
['Barlow Nick']
2564 ['Barlow Nick'] ['AU']
['Baudracco Chiara']
2565 ['Baudracco Chiara'] ['IT']
['Beraldo Maurizio']
2566 ['Beraldo Maurizio'] ['IT']
['Berardi Walter']
2567 ['Berardi Walter'] ['IT']
['Bermudez Leonardo Ariel']
2568 ['Bermudez Leonardo Ariel'] ['AR']
['Bertoglio Gris Domenico']
2569 ['Bertoglio Gris Domenico'] ['IT']
['Bidese Sabrina']
2570 ['Bidese Sabrina'] ['IT']
['Billi Daniela']
2571 ['Billi Daniela'] ['IT']
['Boix Ferrando Lucas']
2572 ['Boix Ferrando Lucas'] ['ES']
['Bonfiglioli Pietro']
2573 ['Bonfiglioli Pietro'] ['IT']
['Bopp Robert']
2574 ['Bopp Robert'] ['NL']
['Bordini Gianluca']
2575 ['Bordini Gianluca'] ['IT']
['Bortolazzo Renzo']
2576 ['Bortolazzo Renzo'] ['IT']
['Boscarioli Clodis']
2577 ['Boscarioli Clodis'] ['BR']
['Bovet Ruben']
2578 ['Bovet Ruben'] ['IT']
['Brera Molinaro Rosalba']
2579 ['Brera Molinaro Rosalba'] ['IT']
['Bringhen Alessandro']
2580 ['Bringhen Alessandro'] ['IT']
['Buckledee Christine']
2581 ['Buckledee Christine'] ['GB']
['Busca Alberto']
2582 ['Busca Alberto'] ['IT']
['Caldwell Mark']
2583 ['Caldwell Mark'] ['GB']
['Campana Valerio']
2584 ['Campana Valerio'] ['IT']
['Campbell Donald']
2585 ['Campbell Donald'] ['GB']
['Carlo Alberto Lapponi']
2586 ['Carlo Alberto Lapponi'] ['IT']
['Carrel Stefano']
2587 ['Carrel Stefano'] ['IT']
['Carte Thierry']
2588 ['Carte Thierry'] ['FR']
['Castaldo Matteo']
2589 ['Castaldo Matteo'] ['IT']
['Castro Machado Solane']
2590 ['Castro Machado Solane'] ['BR']
['Cavalli Giovanni']
2591 ['Cavalli Giovanni'] ['IT']
['Cazzoli Filippo']
2592 ['Cazzoli Filippo'] ['IT']
['Celleri Simone']
2593 ['Celleri Simone'] ['IT']
['Chemello Mirko']
2594 ['Chemello Mirko'] ['IT']
['Chen Fang']
2595 ['Chen Fang'] ['CN']
['Chiarello Tommaso']
2596 ['Chiarello Tommaso'] ['IT']
['Ciliberti Elisa']
2597 ['Ciliberti Elisa'] ['FR']
['Ciobanu Denis Dumitrel']
2598 ['Ciobanu Denis Dumitrel'] ['IT']
['Clappey Mauro']
2599 ['Clappey Mauro'] ['IT']
['Colombo Alexandro']
2600 ['Colombo Alexandro'] ['IT']
['Conroy Simon']
2601 ['Conroy Simon'] ['GB']
['Corradini Morgan']
2602 ['Corradini Morgan'] ['IT']
['Correale Veronica']
2603 ['Correale Veronica'] ['IT']
['Cortina Ramon']
2604 ['Cortina Ramon'] ['ES']
['Cortina Sergio Edgardo']
2605 ['Cortina Sergio Edgardo'] ['AR']
['Cucco Francesco']
2606 ['Cucco Francesco'] ['IT']
['Cum Andrea']
2607 ['Cum Andrea'] ['IT']
['Dalibert Emilie']
2608 ['Dalibert Emilie'] ['FR']
['Damiani Andrea']
2609 ['Damiani Andrea'] ['IT']
['David Mousseaux']
2610 ['David Mousseaux'] ['FR']
['Davide Mappelli']
2611 ['Davide Mappelli'] ['IT']
['Dawson Catherine']
2612 ['Dawson Catherine'] ['GB']
['De Cilladi Mara Antonella']
2613 ['De Cilladi Mara Antonella'] ['IT']
['Debevec Ursula']
2614 ['Debevec Ursula'] ['SI']
['Dell Utri Marcella']
2615 ['Dell Utri Marcella'] ['IT']
['Denoncin Thierry']
2616 ['Denoncin Thierry'] ['BE']
['Desgeorge Eric']
2617 ['Desgeorge Eric'] ['FR']
['Devine Keri']
2618 ['Devine Keri'] ['NZ']
['Di Giacomo Fabio']
2619 ['Di Giacomo Fabio'] ['IT']
['Di Martino Vito']
2620 ['Di Martino Vito'] ['IT']
['Digirolamo Andrea']
2621 ['Digirolamo Andrea'] ['IT']
['Du Haifeng']
2622 ['Du Haifeng'] ['CN']
['Ellemunt Eugen']
2623 ['Ellemunt Eugen'] ['IT']
['Emanuel Laura']
2624 ['Emanuel Laura'] ['IT']
['Ferrari Andrea']
2625 ['Ferrari Andrea'] ['IT']
['Ferrari Enzo']
2626 ['Ferrari Enzo'] ['IT']
['Ferrati Matteo']
2627 ['Ferrati Matteo'] ['IT']
['Fievet Damien']
2628 ['Fievet Damien'] ['FR']
['Flage Michele']
2629 ['Flage Michele'] ['FR']
['Franceschelli Pietro']
2630 ['Franceschelli Pietro'] ['IT']
['Furlanetto Marta']
2631 ['Furlanetto Marta'] ['IT']
['Furtado Sonia']
2632 ['Furtado Sonia'] ['FR']
['Gaglio Fabrizio']
2633 ['Gaglio Fabrizio'] ['IT']
['Gallicet Sergio']
2634 ['Gallicet Sergio'] ['IT']
['Gambacorta Davide']
2635 ['Gambacorta Davide'] ['IT']
['Gatta Pasquale']
2636 ['Gatta Pasquale'] ['IT']
['Gaudin Vincent']
2637 ['Gaudin Vincent'] ['FR']
['Gianluca Caimi']
2638 ['Gianluca Caimi'] ['IT']
['Gil Francisco']
2639 ['Gil Francisco'] ['ES']
['Gilardi Federico']
2640 ['Gilardi Federico'] ['IT']
['Godani Alessandro']
2641 ['Godani Alessandro'] ['IT']
['Gogniat Gregoire']
2642 ['Gogniat Gregoire'] ['CH']
['Gouet Magali']
2643 ['Gouet Magali'] ['FR']
['Grange Giuseppe']
2644 ['Grange Giuseppe'] ['IT']
['Groscol Maxime']
2645 ['Groscol Maxime'] ['FR']
['Grove Chris']
2646 ['Grove Chris'] ['US']
['Guazzo Raffaele']
2647 ['Guazzo Raffaele'] ['IT']
['Guglielmo Francesco']
2648 ['Guglielmo Francesco'] ['IT']
['Guignier Regis']
2649 ['Guignier Regis'] ['FR']
['Hayashi Miwako']
2650 ['Hayashi Miwako'] ['JP']
['Hunter Dan']
2651 ['Hunter Dan'] ['GB']
['Ieng Cheung']
2652 ['Ieng Cheung'] ['MO']
['Ji Yuan']
2653 ['Ji Yuan'] ['CN']
['Joergensen Peter']
2654 ['Joergensen Peter'] ['DK']
['Junko Kazukawa']
2655 ['Junko Kazukawa'] ['JP']
['Kaczmarek Pawel']
2656 ['Kaczmarek Pawel'] ['PL']
['Kedami Ali']
2657 ['Kedami Ali'] ['LB']
['Kikuchi Nobuaki']
2658 ['Kikuchi Nobuaki'] ['JP']
['Kim Jinyoung']
2659 ['Kim Jinyoung'] ['KR']
['Kitamura Makoto']
2660 ['Kitamura Makoto'] ['JP']
['Klanjsek Milan']
2661 ['Klanjsek Milan'] ['CA']
['Krier Benoit']
2662 ['Krier Benoit'] ['BE']
['L Hostis Yann']
2663 ['L Hostis Yann'] ['FR']
['Latreille Didier']
2664 ['Latreille Didier'] ['FR']
['Lecomte Emilie']
2665 ['Lecomte Emilie'] ['FR']

['Levai Valerie']
2666 ['Levai Valerie'] ['FR']
['Li Chao']
2667 ['Li Chao'] ['CN']
['Limontini Mattia']
2668 ['Limontini Mattia'] ['IT']
['Loeffen Dirk']
2669 ['Loeffen Dirk'] ['NL']
['Luglio Fabrizio']
2670 ['Luglio Fabrizio'] ['IT']
['Lyu Hao']
2671 ['Lyu Hao'] ['CN']
['Macchetto Nicola']
2672 ['Macchetto Nicola'] ['IT']
['Maneglia Andrea']
2673 ['Maneglia Andrea'] ['IT']
['Marechal Anthony']
2674 ['Marechal Anthony'] ['BE']
['Maresca Atilio']
2675 ['Maresca Atilio'] ['AR']
['Martin Frank']
2676 ['Martin Frank'] ['FR']
['Martines Luca']
2677 ['Martines Luca'] ['IT']
['Massart Jean Christophe']
2678 ['Massart Jean Christophe'] ['BE']
['Mattiolo Filippo']
2679 ['Mattiolo Filippo'] ['IT']
['Maurin Christophe']
2680 ['Maurin Christophe'] ['FR']
['Meazzi Riccardo']
2681 ['Meazzi Riccardo'] ['IT']
['Melacarne Michele']
2682 ['Melacarne Michele'] ['IT']
['Mercier Olivier']
2683 ['Mercier Olivier'] ['FR']
['Miao Lei']
2684 ['Miao Lei'] ['CN']
['Milazzo Angelo']
2685 ['Milazzo Angelo'] ['IT']
['Millan Verdu Joan Manuel']
2686 ['Millan Verdu Joan Manuel'] ['ES']
['Mischler Gregoire']
2687 ['Mischler Gregoire'] ['CH']
['Mitsiou Georgia']
2688 ['Mitsiou Georgia'] ['GR']
['Mohammad Zen Hendra Wijaya']
2689 ['Mohammad Zen Hendra Wijaya'] ['ID']
['Montem Sean']
2690 ['Montem Sean'] ['DK']
['Motteli Hansueli']
2691 ['Motteli Hansueli'] ['CH']
['Nakamura Shinichi']
2692 ['Nakamura Shinichi'] ['JP']
['Nalin Riccardo']
2693 ['Nalin Riccardo'] ['IT']
['Navillod Tarcisio']
2694 ['Navillod Tarcisio'] ['IT']
['Negra Gianluca']
2695 ['Negra Gianluca'] ['IT']
['Ng Koon Wei']
2696 ['Ng Koon Wei'] ['SG']
['Nicolina Luca']
2697 ['Nicolina Luca'] ['IT']
['Niederreuther Mark Nils']
2698 ['Niederreuther Mark Nils'] ['DE']
['Olesen Martin Panduro']
2699 ['Olesen Martin Panduro'] ['DK']
['Oristil Alexandre']
2700 ['Oristil Alexandre'] ['FR']
['Orlando Corrado']
2701 ['Orlando Corrado'] ['IT']
['Ouvrier Giuseppe']
2702 ['Ouvrier Giuseppe'] ['IT']
['Panzeri Mario']
2703 ['Panzeri Mario'] ['IT']
['Pasquale Giampaolo']
2704 ['Pasquale Giampaolo'] ['IT']
['Paul Mathias']
2705 ['Paul Mathias'] ['DE']
['Pedon Silvio']
2706 ['Pedon Silvio'] ['IT']
['Peirano Gianluca']
2707 ['Peirano Gianluca'] ['IT']
['Perona Paolo']
2708 ['Perona Paolo'] ['IT']
['Pessini Roberto']
2709 ['Pessini Roberto'] ['IT']
['Pession Valentino']
2710 ['Pession Valentino'] ['IT']
['Petani Oriana']
2711 ['Petani Oriana'] ['IT']
['Petitpas Christophe']
2712 ['Petitpas Christophe'] ['FR']
['Piloni Francesco']
2713 ['Piloni Francesco'] ['IT']
['Poh Seivland']
2714 ['Poh Seivland'] ['SG']
['Pollet Manu']
2715 ['Pollet Manu'] ['BE']
['Post Holmberg Jeffrey']
2716 ['Post Holmberg Jeffrey'] ['US']
['Pretto Way']
2717 ['Pretto Way'] ['IT']
['Provero Luigi']
2718 ['Provero Luigi'] ['IT']
['Pruefer Martina']
2719 ['Pruefer Martina'] ['DE']
['Quadrelli Rosalba']
2720 ['Quadrelli Rosalba'] ['IT']
['Quaglini Davide']
2721 ['Quaglini Davide'] ['IT']
['Quaglio Albano']
2722 ['Quaglio Albano'] ['IT']
['Quenneville Eric']
2723 ['Quenneville Eric'] ['FR']
['Quintana Santana Daniel']
2724 ['Quintana Santana Daniel'] ['ES']
['Rakotosaona Nirina']
2725 ['Rakotosaona Nirina'] ['MG']
['Ranzini Giulia']
2726 ['Ranzini Giulia'] ['IT']
['Ravarono Alessandro']
2727 ['Ravarono Alessandro'] ['IT']
['Rea Antonio']
2728 ['Rea Antonio'] ['IT']
['Reali Leandro']
2729 ['Reali Leandro'] ['IT']
['Rossetti Andrea']
2730 ['Rossetti Andrea'] ['IT']
['Rossi Luigi']
2731 ['Rossi Luigi'] ['IT']
['Rouget Joseph']
2732 ['Rouget Joseph'] ['FR']
['Roux Christophe']
2733 ['Roux Christophe'] ['FR']
['Rouxel Christan']
2734 ['Rouxel Christan'] ['FR']
['Ruggeri Giuseppe']
2735 ['Ruggeri Giuseppe'] ['IT']
['Ruiz Garcia Juan Antonio']
2736 ['Ruiz Garcia Juan Antonio'] ['ES']
['Ruzza Stefano']
2737 ['Ruzza Stefano'] ['IT']
['Salommo Normann']
2738 ['Salommo Normann'] ['DE']
['Sampaio Quim']
2739 ['Sampaio Quim'] ['PT']
['Samwell Ben']
2740 ['Samwell Ben'] ['ZA']
['Saporiti Raffaele']
2741 ['Saporiti Raffaele'] ['IT']
['Sava Catalin']
2742 ['Sava Catalin'] ['RO']
['Schiavone Sara']
2743 ['Schiavone Sara'] ['IT']
['Sciuchetti Daniele']
2744 ['Sciuchetti Daniele'] ['IT']
['Sereno Regis Piero']
2745 ['Sereno Regis Piero'] ['IT']
['Sergio Migliore']
2746 ['Sergio Migliore'] ['IT']
['Sesso Mirko']
2747 ['Sesso Mirko'] ['IT']
['Sevin Claude']
2748 ['Sevin Claude'] ['FR']
['Shen Gai Lee']
2749 ['Shen Gai Lee'] ['TW']
['Sibal Joseph']
2750 ['Sibal Joseph'] ['PH']
['Sibulak Kevin']
2751 ['Sibulak Kevin'] ['CA']
['Soler Cozar Mireia']
2752 ['Soler Cozar Mireia'] ['ES']
['Sottini Mattia']
2753 ['Sottini Mattia'] ['IT']
['Sykes Dean']
2754 ['Sykes Dean'] ['GB']
['Tamargo Valdes Joel']
2755 ['Tamargo Valdes Joel'] ['ES']
['Tanaka Yoshiyuki']
2756 ['Tanaka Yoshiyuki'] ['JP']
['Tasin Maura']
2757 ['Tasin Maura'] ['IT']
['Tay Chee Meng']
2758 ['Tay Chee Meng'] ['SG']
['Teknetzis Apostolos']
2759 ['Teknetzis Apostolos'] ['FR']
['Tonon Lino']
2760 ['Tonon Lino'] ['IT']
['Trovati Cristiano']
2761 ['Trovati Cristiano'] ['IT']
['Tschoepe Frank']
2762 ['Tschoepe Frank'] ['DE']
['Valenti Luca']
2763 ['Valenti Luca'] ['IT']
['Vallet Matteo']
2764 ['Vallet Matteo'] ['IT']
['Viot Valter']
2765 ['Viot Valter'] ['IT']
['Vu Thanh']
2766 ['Vu Thanh'] ['VN']
['Wade Walter']
2767 ['Wade Walter'] ['AR']
['Wakui Motohiro']
2768 ['Wakui Motohiro'] ['JP']
['William Ardemagni']
2769 ['William Ardemagni'] ['IT']
['Wong Yeungming Edmund']
2770 ['Wong Yeungming Edmund'] ['GB']
['Wu Hai Zhong']
2771 ['Wu Hai Zhong'] ['CN']
['Yoshizawa Hirotomo']
2772 ['Yoshizawa Hirotomo'] ['JP']
['Zammaretti Davide']
2773 ['Zammaretti Davide'] ['IT']
['Zanoni Giovanni']
2774 ['Zanoni Giovanni'] ['IT']
['Zhang Yuren']
2775 ['Zhang Yuren'] ['CN']
['Zhao Yingkai']
2776 ['Zhao Yingkai'] ['CN']
['Toriumi Kouta']
2777 ['Toriumi Kouta'] ['JP']
['Smith Matthew']
2778 ['Smith Matthew'] ['US']
['Luke Nelson']
2779 ['Luke Nelson'] ['US']
['Siraudin Mathieu']
2780 ['Siraudin Mathieu'] ['FR']
['Kennedy Matthew']
2781 ['Kennedy Matthew'] ['GB']
['Stegagnini Luca']
2782 ['Stegagnini Luca'] ['IT']
['Delikat Patrick']
2783 ['Delikat Patrick'] ['FR']
['Thierry Ador']
2784 ['Thierry Ador'] ['FR']
['Petrut Alex Cosmin']
2785 ['Petrut Alex Cosmin'] ['RO']
['Palli Gianluca']
2786 ['Palli Gianluca'] ['IT']
['Bragg Jez']
2787 ['Bragg Jez'] ['GB']
['Wang Xiaolin']
2788 ['Wang Xiaolin'] ['CN']
['Aarons Jamie']
2789 ['Aarons Jamie'] ['GB']
['Jaile Casademont Joel']
2790 ['Jaile Casademont Joel'] ['ES']
['Guo Qiyun']
2791 ['Guo Qiyun'] ['CN']
['Martin Gomez David']
2792 ['Martin Gomez David'] ['ES']
['Case Stephanie']
2793 ['Case Stephanie'] ['CA']
['Anderson John']
2794 ['Anderson John'] ['US']
['Liu Chao']
2795 ['Liu Chao'] ['CN']
['Souchon Frederic']
2796 ['Souchon Frederic'] ['FR']
['Girgin Sertan']
2797 ['Girgin Sertan'] ['TR']
['Bourdais Olivier']
2798 ['Bourdais Olivier'] ['FR']
['Dove Matthew']
2799 ['Dove Matthew'] ['ZA']
['Kuchimi Taro']
2800 ['Kuchimi Taro'] ['JP']
['Sala Mario']
2801 ['Sala Mario'] ['IT']
['Patierno Gennaro']
2802 ['Patierno Gennaro'] ['IT']
['Saggin Giulia']
2803 ['Saggin Giulia'] ['IT']
['Breda Alessio']
2804 ['Breda Alessio'] ['IT']
['Treu Denis']
2805 ['Treu Denis'] ['IT']
['Baastrup Thure']
2806 ['Baastrup Thure'] ['DK']
['Danet Fabien']
2807 ['Danet Fabien'] ['FR']
['Malai Viorica']
2808 ['Malai Viorica'] ['MD']
['Rousset Alexandra']
2809 ['Rousset Alexandra'] ['FR']
['Arrigoni Giuliana']
2810 ['Arrigoni Giuliana'] ['IT']
['Bourgnon Julien']
2811 ['Bourgnon Julien'] ['CH']
['Pelletier Jeff']
2812 ['Pelletier Jeff'] ['CA']
['Lasater Chad']
2813 ['Lasater Chad'] ['US']
['Pomel Christophe']
2814 ['Pomel Christophe'] ['FR']
['Fernandes Estrada Daniel']
2815 ['Fernandes Estrada Daniel'] ['ES']
['Gilgen Roger']
2816 ['Gilgen Roger'] ['CH']
['Taguchi Minori']
2817 ['Taguchi Minori'] ['JP']
['Galpin Thomas']
2818 ['Galpin Thomas'] ['FR']
['Plavan Marina']
2819 ['Plavan Marina'] ['IT']
['Luca Franceschini']
2820 ['Luca Franceschini'] ['IT']
['Yamada Takashi']
2821 ['Yamada Takashi'] ['JP']
['Etcheverry Munoz Fernando']
2822 ['Etcheverry Munoz Fernando'] ['CL']
['Cornejo Marco']
2823 ['Cornejo Marco'] ['CL']
['Benamati Michele']
2824 ['Benamati Michele'] ['IT']
['Rabito Massimo']
2825 ['Rabito Massimo'] ['IT']
['Mignacco Gianluigi']
2826 ['Mignacco Gianluigi'] ['IT']
['Kelly Glenn']
2827 ['Kelly Glenn'] ['NZ']
['Gu Haiyan']
2828 ['Gu Haiyan'] ['CN']
['Bodere Henri']
2829 ['Bodere Henri'] ['FR']
['Kirren Patrice']
2830 ['Kirren Patrice'] ['FR']
['Dufour Olivier']
2831 ['Dufour Olivier'] ['ME']
['Dehnbostel Jacques']
2832 ['Dehnbostel Jacques'] ['DK']
['Marquis Micha']
2833 ['Marquis Micha'] ['FR']
['Sequeira Rui']
2834 ['Sequeira Rui'] ['PT']
['La Rocca Giovanni']
2835 ['La Rocca Giovanni'] ['IT']
['Lagarde Vincent']
2836 ['Lagarde Vincent'] ['FR']
['Jurado Contreras Jonatan']
2837 ['Jurado Contreras Jonatan'] ['ES']
['Pinto Fulla Enric']
2838 ['Pinto Fulla Enric'] ['ES']
['Nakagawa Nozomu']
2839 ['Nakagawa Nozomu'] ['JP']
['Samaniego Jose']
2840 ['Samaniego Jose'] ['ES']
['Tribolo Philippe']
2841 ['Tribolo Philippe'] ['FR']

['Chaberge Fabrizio']
2842 ['Chaberge Fabrizio'] ['IT']
['Crippa Veronica']
2843 ['Crippa Veronica'] ['IT']
['Perrone Fodaro Carmelo']
2844 ['Perrone Fodaro Carmelo'] ['IT']
['Hajek Jakub']
2845 ['Hajek Jakub'] ['CZ']
['Hernandez Hernandez Narciso Ignacio']
2846 ['Hernandez Hernandez Narciso Ignacio'] ['ES']
['Javega David']
2847 ['Javega David'] ['ES']
['Moncanut Baptiste']
2848 ['Moncanut Baptiste'] ['FR']
['Oeillet Sylvain']
2849 ['Oeillet Sylvain'] ['FR']
['Calvo Requena Albert']
2850 ['Calvo Requena Albert'] ['AD']
['Betouret Sebastien']
2851 ['Betouret Sebastien'] ['FR']
['Olivson Oleksandr']
2852 ['Olivson Oleksandr'] ['UA']
['Cheng Chih Jen']
2853 ['Cheng Chih Jen'] ['TW']
['Zanarella Cristiano']
2854 ['Zanarella Cristiano'] ['IT']
['Lundstrom Jon']
2855 ['Lundstrom Jon'] ['DK']
['Carrara Ivano']
2856 ['Carrara Ivano'] ['IT']
['Pietrzak Krystian']
2857 ['Pietrzak Krystian'] ['PL']
['Bedhet Guillaume']
2858 ['Bedhet Guillaume'] ['FR']
['Aubert Florent']
2859 ['Aubert Florent'] ['FR']
['Cottens Valerie']
2860 ['Cottens Valerie'] ['CH']
['Generali Alessandro']
2861 ['Generali Alessandro'] ['IT']
['Van Der Hoeven Jan Jilles']
2862 ['Van Der Hoeven Jan Jilles'] ['NL']
['Gregaard Frederik']
2863 ['Gregaard Frederik'] ['DK']
['Knap John']
2864 ['Knap John'] ['GB']
['De Santiago Iglesias Luis']
2865 ['De Santiago Iglesias Luis'] ['ES']
['Girard Norbert']
2866 ['Girard Norbert'] ['FR']
['Comte Dominique']
2867 ['Comte Dominique'] ['FR']
['More Rossana']
2868 ['More Rossana'] ['IT']
['Ando Akihide']
2869 ['Ando Akihide'] ['JP']
['Rafii Arash']
2870 ['Rafii Arash'] ['QA']
['Leung King Yan Anthony']
2871 ['Leung King Yan Anthony'] ['HK']
['Isernia Ruggiero']
2872 ['Isernia Ruggiero'] ['IT']
['Nogaret Alain']
2873 ['Nogaret Alain'] ['FR']
['De Prati Giovanni']
2874 ['De Prati Giovanni'] ['IT']
['Nikolic Predrag']
2875 ['Nikolic Predrag'] ['HR']
['Roig Carcel Josep']
2876 ['Roig Carcel Josep'] ['AD']
['Sciebura Pawel']
2877 ['Sciebura Pawel'] ['PL']
['Diemoz Paolo']
2878 ['Diemoz Paolo'] ['IT']
['Henry Didier']
2879 ['Henry Didier'] ['FR']
['Lovera Pierluigi']
2880 ['Lovera Pierluigi'] ['IT']
['Longhini Piero']
2881 ['Longhini Piero'] ['IT']
['Marin Jerome']
2882 ['Marin Jerome'] ['FR']
['Girgin Serkan']
2883 ['Girgin Serkan'] ['TR']
['Marzotto Ita Emanuela']
2884 ['Marzotto Ita Emanuela'] ['IT']
['Zuncheddu Matteo']
2885 ['Zuncheddu Matteo'] ['IT']
['Laurent Pascal']
2886 ['Laurent Pascal'] ['FR']
['Conz Tommaso']
2887 ['Conz Tommaso'] ['IT']
['Dubouilh Cedric']
2888 ['Dubouilh Cedric'] ['FR']
['Cheng Kuo Pin']
2889 ['Cheng Kuo Pin'] ['TW']
['Trentani Laura']
2890 ['Trentani Laura'] ['IT']
['Codina Ventura Jordi']
2891 ['Codina Ventura Jordi'] ['ES']
['Acquistapace Alfredo']
2892 ['Acquistapace Alfredo'] ['IT']
['Luet Dominique']
2893 ['Luet Dominique'] ['FR']
['Katsiropoulos Christos']
2894 ['Katsiropoulos Christos'] ['GR']
['Boncompagni Roberto']
2895 ['Boncompagni Roberto'] ['IT']
['Gong Mingcheng']
2896 ['Gong Mingcheng'] ['CN']
['Mayen Jean Sebastien']
2897 ['Mayen Jean Sebastien'] ['FR']
['Radi Davide']
2898 ['Radi Davide'] ['IT']
['Ponzin Francesco']
2899 ['Ponzin Francesco'] ['IT']
['Kolaczek Ludovic']
2900 ['Kolaczek Ludovic'] ['FR']
['Baars Anouk']
2901 ['Baars Anouk'] ['NL']
['Cataltepe Servet']
2902 ['Cataltepe Servet'] ['TR']
['Leveque Denis']
2903 ['Leveque Denis'] ['FR']
['Tormena Fabio']
2904 ['Tormena Fabio'] ['IT']
['Alleguede Stephane']
2905 ['Alleguede Stephane'] ['FR']
['Lebole Enrico']
2906 ['Lebole Enrico'] ['IT']
['Abanera Luca']
2907 ['Abanera Luca'] ['IT']
['Ballesteros Victor']
2908 ['Ballesteros Victor'] ['US']
['Paladin Tiziano']
2909 ['Paladin Tiziano'] ['IT']
['Tristram Antoine']
2910 ['Tristram Antoine'] ['FR']
['Vitiere Laurent']
2911 ['Vitiere Laurent'] ['FR']
['Perrier Jerome']
2912 ['Perrier Jerome'] ['FR']
['Li Zhongxue']
2913 ['Li Zhongxue'] ['CN']
['Macchia Marco Antonio']
2914 ['Macchia Marco Antonio'] ['IT']
['Gregoire Olivier']
2915 ['Gregoire Olivier'] ['BE']
['Barret Thierry']
2916 ['Barret Thierry'] ['FR']
['Bokov Vasily']
2917 ['Bokov Vasily'] ['UA']
['Dubrovin Gennady']
2918 ['Dubrovin Gennady'] ['RU']
['La Martina Dario']
2919 ['La Martina Dario'] ['IT']
['Rothan Benoit']
2920 ['Rothan Benoit'] ['FR']
['Girardot Jacques']
2921 ['Girardot Jacques'] ['FR']
['Gross Cristiano']
2922 ['Gross Cristiano'] ['IT']
['D Alessio Joseph']
2923 ['D Alessio Joseph'] ['US']
['Serban Mihai']
2924 ['Serban Mihai'] ['RO']
['Nedelec Patrice']
2925 ['Nedelec Patrice'] ['FR']
['Brussolo Simone']
2926 ['Brussolo Simone'] ['IT']
['Piccitto Thomas']
2927 ['Piccitto Thomas'] ['FR']
['Rive Leanne Rive']
2928 ['Rive Leanne Rive'] ['GB']
['Guillamet Christophe']
2929 ['Guillamet Christophe'] ['FR']
['Junod Nadir']
2930 ['Junod Nadir'] ['IT']
['Szymik Marcin']
2931 ['Szymik Marcin'] ['PL']
['Ariens Jordy']
2932 ['Ariens Jordy'] ['NL']
['Spicci Sergio']
2933 ['Spicci Sergio'] ['IT']
['Weber Marcus']
2934 ['Weber Marcus'] ['DE']
['Bosco Paolo']
2935 ['Bosco Paolo'] ['IT']
['Galletto Marco']
2936 ['Galletto Marco'] ['IT']
['Crivellaro Matteo']
2937 ['Crivellaro Matteo'] ['IT']
['Cochet Ludovic']
2938 ['Cochet Ludovic'] ['FR']
['Pumphrey Andrew']
2939 ['Pumphrey Andrew'] ['GB']
['Spurlock Dan']
2940 ['Spurlock Dan'] ['US']
['Aragon Joel']
2941 ['Aragon Joel'] ['FR']
['Draghetti Marco']
2942 ['Draghetti Marco'] ['IT']
['Bilancioni Mirko']
2943 ['Bilancioni Mirko'] ['IT']
['Maughan Grant']
2944 ['Maughan Grant'] ['AU']
['Alaverdov Gerald']
2945 ['Alaverdov Gerald'] ['FR']
['Douglas Dave']
2946 ['Douglas Dave'] ['GB']
['Lee Gwan Woo']
2947 ['Lee Gwan Woo'] ['KR']
['Berruquier Paolo']
2948 ['Berruquier Paolo'] ['IT']
['Mostosi Luigi']
2949 ['Mostosi Luigi'] ['IT']
['Barcella Sergio']
2950 ['Barcella Sergio'] ['IT']
['Koizumi Yasuyuki']
2951 ['Koizumi Yasuyuki'] ['JP']
['Ouziel Alejandro']
2952 ['Ouziel Alejandro'] ['ES']
['Curtaz Claudio']
2953 ['Curtaz Claudio'] ['IT']
['Lazzaro Rafinski Michal']
2954 ['Lazzaro Rafinski Michal'] ['IT']
['Bressy Paolo']
2955 ['Bressy Paolo'] ['IT']
['Shimizu Hiroaki']
2956 ['Shimizu Hiroaki'] ['JP']
['Georgoulopoulos Nikolaos']
2957 ['Georgoulopoulos Nikolaos'] ['GR']
['Tani Stanghellini Jose Luis']
2958 ['Tani Stanghellini Jose Luis'] ['IT']
['Caso Marco']
2959 ['Caso Marco'] ['IT']
['Grillo Ennio']
2960 ['Grillo Ennio'] ['IT']
['Lucot Armand']
2961 ['Lucot Armand'] ['IT']
['Bordini William']
2962 ['Bordini William'] ['IT']
['Rojo Rios Daniel']
2963 ['Rojo Rios Daniel'] ['ES']
['Kosmala Pawel']
2964 ['Kosmala Pawel'] ['PL']
['Schroth Markus']
2965 ['Schroth Markus'] ['DE']
['Macchia Giulio']
2966 ['Macchia Giulio'] ['IT']
['Pozzali Pierluigi']
2967 ['Pozzali Pierluigi'] ['IT']
['Vezzani Roberto']
2968 ['Vezzani Roberto'] ['IT']
['Archer Bertrand']
2969 ['Archer Bertrand'] ['FR']
['Ang Choo Siong']
2970 ['Ang Choo Siong'] ['SG']
['Juillerat Jean Louis']
2971 ['Juillerat Jean Louis'] ['CH']
['Ramos Mario Wilbert']
2972 ['Ramos Mario Wilbert'] ['PE']
['Berthe Cyrille']
2973 ['Berthe Cyrille'] ['FR']
['Mastroperros Panagiotis']
2974 ['Mastroperros Panagiotis'] ['GR']
['Tanada Takayuki']
2975 ['Tanada Takayuki'] ['JP']
['Bonin Charles']
2976 ['Bonin Charles'] ['FR']
['He Yunting']
2977 ['He Yunting'] ['CN']
['Evans John']
2978 ['Evans John'] ['GB']
['Paredi Giulio']
2979 ['Paredi Giulio'] ['IT']
['Olvback Angela']
2980 ['Olvback Angela'] ['IT']
['Togumi Sidney']
2981 ['Togumi Sidney'] ['BR']
['Giuseppe Garbarino']
2982 ['Giuseppe Garbarino'] ['IT']
['Gayraud Jean Philippe']
2983 ['Gayraud Jean Philippe'] ['FR']
['Bouteille Denis']
2984 ['Bouteille Denis'] ['FR']
['Boifava Federica']
2985 ['Boifava Federica'] ['IT']
['Dakhil Mohamed El Amin']
2986 ['Dakhil Mohamed El Amin'] ['IT']
['Walters Jere Patricia']
2987 ['Walters Jere Patricia'] ['US']
['Melto Mikael']
2988 ['Melto Mikael'] ['SE']
['Luzzatto Enrico']
2989 ['Luzzatto Enrico'] ['IT']
['Lanzoni Fausto']
2990 ['Lanzoni Fausto'] ['IT']
['Lee Wontae']
2991 ['Lee Wontae'] ['KR']
['Daele Jean Marc']
2992 ['Daele Jean Marc'] ['BE']
['Braidwood Douglas']
2993 ['Braidwood Douglas'] ['GB']
['Merlet Laurent']
2994 ['Merlet Laurent'] ['IT']
['Rosso Michela']
2995 ['Rosso Michela'] ['IT']
['Petitjean Pascal']
2996 ['Petitjean Pascal'] ['FR']
['Settembrini Nicola']
2997 ['Settembrini Nicola'] ['IT']
['Carmela Vergura']
2998 ['Carmela Vergura'] ['IT']
['Habe Paolo']
2999 ['Habe Paolo'] ['IT']
['Gimbert Philippe']
3000 ['Gimbert Philippe'] ['FR']
['Bartoli Omar']
3001 ['Bartoli Omar'] ['IT']
['Soresi Leonardo']
3002 ['Soresi Leonardo'] ['IT']
['Wang Yu']
3003 ['Wang Yu'] ['CN']
['Fukuyama Masahiro']
3004 ['Fukuyama Masahiro'] ['JP']
['Gallinucci Luca']
3005 ['Gallinucci Luca'] ['IT']
['Tassone Roberto']
3006 ['Tassone Roberto'] ['IT']
['Ladislav Farkas']
3007 ['Ladislav Farkas'] ['SK']
['Bonin Cyrille']
3008 ['Bonin Cyrille'] ['FR']
['Gilbank Pascale']
3009 ['Gilbank Pascale'] ['FR']
['Nunez Matias Nelson']
3010 ['Nunez Matias Nelson'] ['AR']
['Orella Adriano']
3011 ['Orella Adriano'] ['IT']
['Cappuzzo Elisa']
3012 ['Cappuzzo Elisa'] ['IT']
['Manolino Davide']
3013 ['Manolino Davide'] ['IT']
['Hentsch Torsten']
3014 ['Hentsch Torsten'] ['DE']
['Kanisch Holger']
3015 ['Kanisch Holger'] ['DE']
['Saito Miki']
3016 ['Saito Miki'] ['JP']
['Buckingham Anna']
3017 ['Buckingham Anna'] ['GB']
['Domazetovic Tomas']
3018 ['Domazetovic Tomas'] ['ME']
['Spadola Giorgio']
3019 ['Spadola Giorgio'] ['IT']
['Pagliero Giorgio']
3020 ['Pagliero Giorgio'] ['IT']
['Tokoro Sachiko']
3021 ['Tokoro Sachiko'] ['JP']
['Marconi Massimo']
3022 ['Marconi Massimo'] ['IT']
['Tay Roy Kian Mong']
3023 ['Tay Roy Kian Mong'] ['SG']
['Di Cola Giovanni']
3024 ['Di Cola Giovanni'] ['IT']
['Azhagarasan Ashok']
3025 ['Azhagarasan Ashok'] ['IN']
['Prendes Rodriguez Ivan']
3026 ['Prendes Rodriguez Ivan'] ['ES']
['Caporali Fabio']
3027 ['Caporali Fabio'] ['IT']
['Casale Luigi']
3028 ['Casale Luigi'] ['IT']
['Moro Franco']
3029 ['Moro Franco'] ['IT']
['Bernard Christophe']
3030 ['Bernard Christophe'] ['FR']
['Zandonai Claudio']
3031 ['Zandonai Claudio'] ['IT']

['Herrera Noelia']
3032 ['Herrera Noelia'] ['ES']
['Guan Yadi']
3033 ['Guan Yadi'] ['CN']
['Ducly Remo']
3034 ['Ducly Remo'] ['IT']
['Javaheri Nima']
3035 ['Javaheri Nima'] ['GB']
['Komurcu Osman']
3036 ['Komurcu Osman'] ['GB']
['Marzano Massimo']
3037 ['Marzano Massimo'] ['IT']
['Delval Lionel']
3038 ['Delval Lionel'] ['FR']
['Lam Ka Man']
3039 ['Lam Ka Man'] ['HK']
['Ng Jonathan']
3040 ['Ng Jonathan'] ['HK']
['Vulcan Alessio']
3041 ['Vulcan Alessio'] ['IT']
['Cayuela Gomez Miguel Angel']
3042 ['Cayuela Gomez Miguel Angel'] ['ES']
['Martignoni Alessandro']
3043 ['Martignoni Alessandro'] ['IT']
['Sordi Paolo']
3044 ['Sordi Paolo'] ['IT']
['Fachino Sandro']
3045 ['Fachino Sandro'] ['IT']
['Sedda Ivan']
3046 ['Sedda Ivan'] ['IT']
['Arnold Andrew']
3047 ['Arnold Andrew'] ['GB']
['Xu Tianshu']
3048 ['Xu Tianshu'] ['CN']
['Garcia Marc']
3049 ['Garcia Marc'] ['ES']
['Capus Berard Isabelle']
3050 ['Capus Berard Isabelle'] ['FR']
['Priod Giancarlo']
3051 ['Priod Giancarlo'] ['IT']
['Medici Andrea']
3052 ['Medici Andrea'] ['IT']
['Hattori Shin']
3053 ['Hattori Shin'] ['JP']
['Iwashita Yoshitaka']
3054 ['Iwashita Yoshitaka'] ['JP']
['Chang Jiang']
3055 ['Chang Jiang'] ['CN']
['Legrain Thomas']
3056 ['Legrain Thomas'] ['FR']
['Djakovic Aleksandar']
3057 ['Djakovic Aleksandar'] ['RS']
['Ponnelle Albert']
3058 ['Ponnelle Albert'] ['GB']
['Zampella Vincenzo']
3059 ['Zampella Vincenzo'] ['IT']
['Muller Seidelmann Frank']
3060 ['Muller Seidelmann Frank'] ['DE']
['Zelenka Alexander']
3061 ['Zelenka Alexander'] ['CH']
['Caracciolo Francesco']
3062 ['Caracciolo Francesco'] ['IT']
['Giovannangelo Alain']
3063 ['Giovannangelo Alain'] ['BE']
['Kronal Olivier']
3064 ['Kronal Olivier'] ['BE']
['Lux Arno']
3065 ['Lux Arno'] ['BE']
['Miret Albert']
3066 ['Miret Albert'] ['ES']
['Tolle Mathieu']
3067 ['Tolle Mathieu'] ['FR']
['Scarpellini Alessandro']
3068 ['Scarpellini Alessandro'] ['IT']
['Wen Haiqing']
3069 ['Wen Haiqing'] ['CN']
['Ewald Bjoern']
3070 ['Ewald Bjoern'] ['DE']
['Frangi Barbara']
3071 ['Frangi Barbara'] ['IT']
['Esposito Mirko']
3072 ['Esposito Mirko'] ['IT']
['Giambattistoni Nicola']
3073 ['Giambattistoni Nicola'] ['IT']
['Wullens Regis']
3074 ['Wullens Regis'] ['FR']
['Bossen Erik']
3075 ['Bossen Erik'] ['DK']
['Alessandrini Michele']
3076 ['Alessandrini Michele'] ['IT']
['Tung Alan']
3077 ['Tung Alan'] ['SG']
['Chau Kwan Hung Joe']
3078 ['Chau Kwan Hung Joe'] ['HK']
['Eremeeva Alevtina']
3079 ['Eremeeva Alevtina'] ['FR']
['Paolini Francesca']
3080 ['Paolini Francesca'] ['IT']
['Barbier Colin']
3081 ['Barbier Colin'] ['FR']
['Furlati Stefano']
3082 ['Furlati Stefano'] ['IT']
['Bertolotti Fabrice']
3083 ['Bertolotti Fabrice'] ['FR']
['Adama Camille']
3084 ['Adama Camille'] ['FR']
['Denolf Danny']
3085 ['Denolf Danny'] ['BE']
['Termite Massimo']
3086 ['Termite Massimo'] ['IT']
['Fischer Benoit']
3087 ['Fischer Benoit'] ['CH']
['Reis Benedicte']
3088 ['Reis Benedicte'] ['LU']
['Turchi Denis']
3089 ['Turchi Denis'] ['IT']
['Lamberti Luca']
3090 ['Lamberti Luca'] ['IT']
['Bonatto Marchello Luca']
3091 ['Bonatto Marchello Luca'] ['IT']
['Bojorquez Gerardo']
3092 ['Bojorquez Gerardo'] ['SV']
['De Man Paul']
3093 ['De Man Paul'] ['BE']
['Cavulli Fabio']
3094 ['Cavulli Fabio'] ['IT']
['Zhao Huayi']
3095 ['Zhao Huayi'] ['CN']
['Asensio Ricardo']
3096 ['Asensio Ricardo'] ['ES']
['Del Giudice Angelo']
3097 ['Del Giudice Angelo'] ['IT']
['Rabaglio Daniele']
3098 ['Rabaglio Daniele'] ['IT']
['Esposito Salvatore']
3099 ['Esposito Salvatore'] ['IT']
['Ornati Cesare']
3100 ['Ornati Cesare'] ['IT']
['Menasse Guillaume']
3101 ['Menasse Guillaume'] ['FR']
['Distort Claudio']
3102 ['Distort Claudio'] ['IT']
['Tang Sauw Yuh']
3103 ['Tang Sauw Yuh'] ['NL']
['Riboli Paolo']
3104 ['Riboli Paolo'] ['IT']
['Fernandez Javier Manuel']
3105 ['Fernandez Javier Manuel'] ['ES']
['Gramajo Tobias']
3106 ['Gramajo Tobias'] ['AR']
['Tagliapietra Massimo']
3107 ['Tagliapietra Massimo'] ['IT']
['Martin Helene']
3108 ['Martin Helene'] ['FR']
['Soave Roberta']
3109 ['Soave Roberta'] ['IT']
['Herman Romain']
3110 ['Herman Romain'] ['BE']
['Marcuzzi Alain']
3111 ['Marcuzzi Alain'] ['FR']
['Tachibana Noriko']
3112 ['Tachibana Noriko'] ['JP']
['Bourcier Franck']
3113 ['Bourcier Franck'] ['FR']
['Pakula Frederic']
3114 ['Pakula Frederic'] ['FR']
['Xu Huirong']
3115 ['Xu Huirong'] ['CN']
['Boggeri Andreino']
3116 ['Boggeri Andreino'] ['IT']
['Oggioni Adriano']
3117 ['Oggioni Adriano'] ['IT']
['Cobalchini Dario']
3118 ['Cobalchini Dario'] ['IT']
['Shibata Kanta']
3119 ['Shibata Kanta'] ['JP']
['Lisa Gian Luca']
3120 ['Lisa Gian Luca'] ['IT']
['Yuan Jia Cindy']
3121 ['Yuan Jia Cindy'] ['CN']
['Landi Riccardo']
3122 ['Landi Riccardo'] ['IT']
['Aldous Jay']
3123 ['Aldous Jay'] ['US']
['Ali Michele']
3124 ['Ali Michele'] ['IT']
['Allegretti Francesco']
3125 ['Allegretti Francesco'] ['IT']
['Amadori Giulia']
3126 ['Amadori Giulia'] ['IT']
['Ambrosi Pascal']
3127 ['Ambrosi Pascal'] ['FR']
['Anania Gennaro']
3128 ['Anania Gennaro'] ['IT']
['Anciaux Mathieu']
3129 ['Anciaux Mathieu'] ['BE']
['Armenteros Ruiz Juan Carlos']
3130 ['Armenteros Ruiz Juan Carlos'] ['ES']
['Ayabe Atsushi']
3131 ['Ayabe Atsushi'] ['JP']
['Bacco Maurizio']
3132 ['Bacco Maurizio'] ['IT']
['Banfi Daniela']
3133 ['Banfi Daniela'] ['IT']
['Basso Ivano']
3134 ['Basso Ivano'] ['IT']
['Baudracco Daniele']
3135 ['Baudracco Daniele'] ['IT']
['Belfrond Marco']
3136 ['Belfrond Marco'] ['IT']
['Belin Christophe']
3137 ['Belin Christophe'] ['FR']
['Bell Tamyka']
3138 ['Bell Tamyka'] ['AU']
['Bellotto Maurizio']
3139 ['Bellotto Maurizio'] ['IT']
['Berardi Antonio']
3140 ['Berardi Antonio'] ['IT']
['Bettio Stefano']
3141 ['Bettio Stefano'] ['IT']
['Bevalot Fabien']
3142 ['Bevalot Fabien'] ['FR']
['Bigot Simon']
3143 ['Bigot Simon'] ['FR']
['Bil Marjolein']
3144 ['Bil Marjolein'] ['NL']
['Bistolfi Fabrizio']
3145 ['Bistolfi Fabrizio'] ['IT']
['Bitzer Rainer']
3146 ['Bitzer Rainer'] ['DE']
['Bjornson Mattias']
3147 ['Bjornson Mattias'] ['SE']
['Blanck Sven']
3148 ['Blanck Sven'] ['CH']
['Blondeau Thierry']
3149 ['Blondeau Thierry'] ['FR']
['Bracotto Maurizio']
3150 ['Bracotto Maurizio'] ['IT']
['Brunschweiler Josef']
3151 ['Brunschweiler Josef'] ['CH']
['Cacciatore Fabrizio']
3152 ['Cacciatore Fabrizio'] ['IT']
['Cappella Mirco']
3153 ['Cappella Mirco'] ['IT']
['Caranzano Marco']
3154 ['Caranzano Marco'] ['IT']
['Carcereri Ezio']
3155 ['Carcereri Ezio'] ['IT']
['Cariolato Roberta']
3156 ['Cariolato Roberta'] ['IT']
['Carrasco Bellmunt David']
3157 ['Carrasco Bellmunt David'] ['ES']
['Carrera Nicola']
3158 ['Carrera Nicola'] ['IT']
['Cartasso Roberto']
3159 ['Cartasso Roberto'] ['IT']
['Cassetto Bernard']
3160 ['Cassetto Bernard'] ['FR']
['Cattaneo Roberto']
3161 ['Cattaneo Roberto'] ['IT']
['Caumon Caroline']
3162 ['Caumon Caroline'] ['FR']
['Cavazini Carvallho Jane']
3163 ['Cavazini Carvallho Jane'] ['BN']
['Cernuda Aldecoa Julio']
3164 ['Cernuda Aldecoa Julio'] ['ES']
['Cervia Davide']
3165 ['Cervia Davide'] ['IT']
['Chanoine Armando']
3166 ['Chanoine Armando'] ['IT']
['Cheng Ryan']
3167 ['Cheng Ryan'] ['HK']
['Chu Edward']
3168 ['Chu Edward'] ['HK']
['Cojutti Luca']
3169 ['Cojutti Luca'] ['IT']
['Comper Denis']
3170 ['Comper Denis'] ['IT']
['Conway Terry']
3171 ['Conway Terry'] ['GB']
['Cuneaz Fabrizio']
3172 ['Cuneaz Fabrizio'] ['IT']
['Dagnes Narciso']
3173 ['Dagnes Narciso'] ['IT']
['Dahlbeck Klaus']
3174 ['Dahlbeck Klaus'] ['DE']
['Daniel Luca']
3175 ['Daniel Luca'] ['IT']
['Davico Claudio']
3176 ['Davico Claudio'] ['CL']
['Deconihout Jacky']
3177 ['Deconihout Jacky'] ['FR']
['Delfanti Roberto']
3178 ['Delfanti Roberto'] ['IT']
['Delmas Yoann']
3179 ['Delmas Yoann'] ['FR']
['Denes Jean Marc']
3180 ['Denes Jean Marc'] ['FR']
['Dery Frederic']
3181 ['Dery Frederic'] ['CA']
['Deschauwer Bruno']
3182 ['Deschauwer Bruno'] ['FR']
['Di Donato Andrea']
3183 ['Di Donato Andrea'] ['IT']
['Di Vincenzo Dominique']
3184 ['Di Vincenzo Dominique'] ['FR']
['Doff Sotta Marco']
3185 ['Doff Sotta Marco'] ['IT']
['Doherty Daniel']
3186 ['Doherty Daniel'] ['IE']
['Dowson Katherine']
3187 ['Dowson Katherine'] ['US']
['Facchini Licia']
3188 ['Facchini Licia'] ['IT']
['Farioli Alberto']
3189 ['Farioli Alberto'] ['IT']
['Ferrari Marco']
3190 ['Ferrari Marco'] ['IT']
['Fischer Marc']
3191 ['Fischer Marc'] ['CH']
['Flavio Scrivano']
3192 ['Flavio Scrivano'] ['IT']
['Fortin Jerome']
3193 ['Fortin Jerome'] ['FR']
['Forzini Michele']
3194 ['Forzini Michele'] ['IT']
['Fourrier Erwan']
3195 ['Fourrier Erwan'] ['FR']
['Freeman Don']
3196 ['Freeman Don'] ['US']
['Fuggiano Ylenia']
3197 ['Fuggiano Ylenia'] ['IT']
['Galieni Silvestro']
3198 ['Galieni Silvestro'] ['IT']
['Gallego Lopez Antonio']
3199 ['Gallego Lopez Antonio'] ['ES']
['Gandini Mauro']
3200 ['Gandini Mauro'] ['IT']
['Garcon Roland']
3201 ['Garcon Roland'] ['FR']
['Gaspar Dos Reis Paulo Miguel']
3202 ['Gaspar Dos Reis Paulo Miguel'] ['PT']
['Ghignone Edoardo']
3203 ['Ghignone Edoardo'] ['IT']
['Giacometti Alberto']
3204 ['Giacometti Alberto'] ['IT']
['Giancarlo Ruffino']
3205 ['Giancarlo Ruffino'] ['IT']

['Glattstein Guillermo']
3206 ['Glattstein Guillermo'] ['AR']
['Goggi Rosanna']
3207 ['Goggi Rosanna'] ['IT']
['Goujon Jean Paul']
3208 ['Goujon Jean Paul'] ['FR']
['Haji Abdul Rahman Haji Abu Bakar']
3209 ['Haji Abdul Rahman Haji Abu Bakar'] ['BN']
['Hauser Ruckli Cornelia']
3210 ['Hauser Ruckli Cornelia'] ['CH']
['Heissl Thomas']
3211 ['Heissl Thomas'] ['AT']
['Heraud William']
3212 ['Heraud William'] ['FR']
['Herman Stephen']
3213 ['Herman Stephen'] ['BE']
['Holden Rob Holden']
3214 ['Holden Rob Holden'] ['FR']
['Holmes William']
3215 ['Holmes William'] ['US']
['Huishichen Huishichen']
3216 ['Huishichen Huishichen'] ['HK']
['Iancu David Traian']
3217 ['Iancu David Traian'] ['RO']
['Ilaria Rossetti']
3218 ['Ilaria Rossetti'] ['IT']
['Ireland Derek']
3219 ['Ireland Derek'] ['AU']
['Izzo Andrea']
3220 ['Izzo Andrea'] ['IT']
['Jaccond Ermando Ivan']
3221 ['Jaccond Ermando Ivan'] ['IT']
['Janiec Robert']
3222 ['Janiec Robert'] ['PL']
['Jarret Patrick']
3223 ['Jarret Patrick'] ['FR']
['John Minta']
3224 ['John Minta'] ['GB']
['Junyent Capdevila Ivan']
3225 ['Junyent Capdevila Ivan'] ['ES']
['Jutzi Nicolas']
3226 ['Jutzi Nicolas'] ['CH']
['Jutzi Oliver']
3227 ['Jutzi Oliver'] ['US']
['King Aodhan Martin']
3228 ['King Aodhan Martin'] ['IE']
['Knidlberger Armin']
3229 ['Knidlberger Armin'] ['DE']
['Kongmunvattana Sanya']
3230 ['Kongmunvattana Sanya'] ['TH']
['Kusano Hiroshi']
3231 ['Kusano Hiroshi'] ['JP']
['Kvaran Agust']
3232 ['Kvaran Agust'] ['IS']
['Lee Chesic']
3233 ['Lee Chesic'] ['KR']
['Leung Lilian']
3234 ['Leung Lilian'] ['HK']
['Levente Dorogi']
3235 ['Levente Dorogi'] ['HU']
['Lim Siawhua']
3236 ['Lim Siawhua'] ['MY']
['Lopez Reyes Alejandro']
3237 ['Lopez Reyes Alejandro'] ['MX']
['Macchetto Luca']
3238 ['Macchetto Luca'] ['IT']
['Macchieraldo Marco']
3239 ['Macchieraldo Marco'] ['IT']
['Macdonald Helen']
3240 ['Macdonald Helen'] ['AU']
['Machet Erik']
3241 ['Machet Erik'] ['IT']
['Magliani Gianpietro']
3242 ['Magliani Gianpietro'] ['IT']
['Manzo Sergio']
3243 ['Manzo Sergio'] ['IT']
['Mareliati Fabio']
3244 ['Mareliati Fabio'] ['IT']
['Mareliati Ylenia']
3245 ['Mareliati Ylenia'] ['IT']
['Marin Janne']
3246 ['Marin Janne'] ['FI']
['Martinez Rufete Daniel']
3247 ['Martinez Rufete Daniel'] ['ES']
['Matifas Emmanuel']
3248 ['Matifas Emmanuel'] ['FR']
['Matsuno Keisuke']
3249 ['Matsuno Keisuke'] ['JP']
['Maverna Cinzia']
3250 ['Maverna Cinzia'] ['IT']
['Mcgrath Euan']
3251 ['Mcgrath Euan'] ['GB']
['Mcinnes Aaryn']
3252 ['Mcinnes Aaryn'] ['CA']
['Menacher Matthew']
3253 ['Menacher Matthew'] ['US']
['Menardi Giovanni']
3254 ['Menardi Giovanni'] ['IT']
['Mercurio Marco']
3255 ['Mercurio Marco'] ['IT']
['Mewes Michael']
3256 ['Mewes Michael'] ['DE']
['Meyer Bernd']
3257 ['Meyer Bernd'] ['DE']
['Monti Saverio']
3258 ['Monti Saverio'] ['IT']
['Moray Francoise']
3259 ['Moray Francoise'] ['BE']
['Moro Luca']
3260 ['Moro Luca'] ['IT']
['Mothes Jean Julien']
3261 ['Mothes Jean Julien'] ['FR']
['Musial Marcelo']
3262 ['Musial Marcelo'] ['BR']
['Navarra Gianluca']
3263 ['Navarra Gianluca'] ['IT']
['Neri Alberto']
3264 ['Neri Alberto'] ['IT']
['Nishida Katsuhiko']
3265 ['Nishida Katsuhiko'] ['JP']
['Niu Chao']
3266 ['Niu Chao'] ['CN']
['Nobili Marco']
3267 ['Nobili Marco'] ['IT']
['Novellini Paolo']
3268 ['Novellini Paolo'] ['IT']
['Oda Hayato']
3269 ['Oda Hayato'] ['JP']
['Oinuma Shiro']
3270 ['Oinuma Shiro'] ['JP']
['Oldani Cristiano']
3271 ['Oldani Cristiano'] ['IT']
['Ornati Giulio']
3272 ['Ornati Giulio'] ['IT']
['Oro Alberto']
3273 ['Oro Alberto'] ['IT']
['Paderi Antonello']
3274 ['Paderi Antonello'] ['IT']
['Palma Camilo']
3275 ['Palma Camilo'] ['FR']
['Pandolfi Andrea']
3276 ['Pandolfi Andrea'] ['IT']
['Paoletti Marco']
3277 ['Paoletti Marco'] ['IT']
['Pascotto Diego']
3278 ['Pascotto Diego'] ['IT']
['Pastore Maurizio']
3279 ['Pastore Maurizio'] ['IT']
['Pedro Conde']
3280 ['Pedro Conde'] ['PT']
['Peressin Marco']
3281 ['Peressin Marco'] ['IT']
['Perez Lopez Oscar']
3282 ['Perez Lopez Oscar'] ['ES']
['Perich Franco']
3283 ['Perich Franco'] ['IT']
['Perucco Paolo']
3284 ['Perucco Paolo'] ['IT']
['Pezzica Giuseppe']
3285 ['Pezzica Giuseppe'] ['IT']
['Piana Hernan']
3286 ['Piana Hernan'] ['AR']
['Pieiller Denis']
3287 ['Pieiller Denis'] ['IT']
['Pipolo Carole']
3288 ['Pipolo Carole'] ['CH']
['Popa Georgiana Camelia']
3289 ['Popa Georgiana Camelia'] ['RO']
['Poretti Marta']
3290 ['Poretti Marta'] ['IT']
['Poulin Stephane']
3291 ['Poulin Stephane'] ['CA']
['Punzo Stefano']
3292 ['Punzo Stefano'] ['IT']
['Qian Si']
3293 ['Qian Si'] ['CN']
['Qu Lijie']
3294 ['Qu Lijie'] ['CN']
['Quagliaroli Paolo']
3295 ['Quagliaroli Paolo'] ['IT']
['Quirk Linda']
3296 ['Quirk Linda'] ['US']
['Renuart Thomas']
3297 ['Renuart Thomas'] ['BE']
['Reynolds Thomas']
3298 ['Reynolds Thomas'] ['IE']
['Rigodanza Francesco']
3299 ['Rigodanza Francesco'] ['IT']
['Riva Alessandro']
3300 ['Riva Alessandro'] ['IT']
['Rodio Roberto']
3301 ['Rodio Roberto'] ['IT']
['Rodriguez Novo Daniel']
3302 ['Rodriguez Novo Daniel'] ['ES']
['Rosset Enrico']
3303 ['Rosset Enrico'] ['IT']
['Rossi Franz']
3304 ['Rossi Franz'] ['IT']
['Salvatori Filippo']
3305 ['Salvatori Filippo'] ['IT']
['Sanchez Rodriguez Sonia']
3306 ['Sanchez Rodriguez Sonia'] ['ES']
['Santiago Delgado Juan Carlos']
3307 ['Santiago Delgado Juan Carlos'] ['ES']
['Savoye Marco']
3308 ['Savoye Marco'] ['IT']
['Scandola Oreste']
3309 ['Scandola Oreste'] ['IT']
['Schiavi Gianandrea']
3310 ['Schiavi Gianandrea'] ['IT']
['Scogings Michael']
3311 ['Scogings Michael'] ['PE']
['Segura Romero Pablo']
3312 ['Segura Romero Pablo'] ['ES']
['Sekiya Katsuji']
3313 ['Sekiya Katsuji'] ['JP']
['Sekulic Natasha']
3314 ['Sekulic Natasha'] ['AU']
['Serventi Matteo']
3315 ['Serventi Matteo'] ['IT']
['Servetti Giuseppe']
3316 ['Servetti Giuseppe'] ['IT']
['Shen Pi Cheng']
3317 ['Shen Pi Cheng'] ['TW']
['Solari Bardi Paolo']
3318 ['Solari Bardi Paolo'] ['CL']
['Sors Michel']
3319 ['Sors Michel'] ['FR']
['Sothonboon Parinda']
3320 ['Sothonboon Parinda'] ['TH']
['Spajic Jovica']
3321 ['Spajic Jovica'] ['RS']
['Spyridopoulos Ilias']
3322 ['Spyridopoulos Ilias'] ['GR']
['Squara Donato']
3323 ['Squara Donato'] ['IT']
['Stola Stefano']
3324 ['Stola Stefano'] ['IT']
['Suckling Sandy Kay']
3325 ['Suckling Sandy Kay'] ['AU']
['Suquet Francesco']
3326 ['Suquet Francesco'] ['IT']
['Tagliapietra Andrea']
3327 ['Tagliapietra Andrea'] ['IT']
['Takahashi Junya']
3328 ['Takahashi Junya'] ['JP']
['Tam Hau Tak']
3329 ['Tam Hau Tak'] ['HK']
['Tan Wooi Keat']
3330 ['Tan Wooi Keat'] ['MY']
['Tang Lei']
3331 ['Tang Lei'] ['CN']
['Tang Yufan']
3332 ['Tang Yufan'] ['CN']
['Tassiaux Vincent']
3333 ['Tassiaux Vincent'] ['FR']
['Thevenet Philippe']
3334 ['Thevenet Philippe'] ['FR']
['Thine Claude']
3335 ['Thine Claude'] ['FR']
['Tiotto Riccardo']
3336 ['Tiotto Riccardo'] ['IT']
['Toledo Calvo Quique']
3337 ['Toledo Calvo Quique'] ['ES']
['Tolosa Damian']
3338 ['Tolosa Damian'] ['AR']
['Torrent Romero Albert']
3339 ['Torrent Romero Albert'] ['ES']
['Trovati Roberto']
3340 ['Trovati Roberto'] ['IT']
['Tsui Yuen Leung']
3341 ['Tsui Yuen Leung'] ['HK']
['Ubertino Alberto']
3342 ['Ubertino Alberto'] ['IT']
['Viltart Mickael']
3343 ['Viltart Mickael'] ['FR']
['Wei Biao']
3344 ['Wei Biao'] ['CN']
['Weimerskirch Annick']
3345 ['Weimerskirch Annick'] ['LU']
['Wey Etienne']
3346 ['Wey Etienne'] ['FR']
['White John Christopher']
3347 ['White John Christopher'] ['FR']
['Wilson Duncan']
3348 ['Wilson Duncan'] ['AF']
['Wyss Laurent']
3349 ['Wyss Laurent'] ['CH']
['Yang Henglin']
3350 ['Yang Henglin'] ['CN']
['Zaffalon Valerio']
3351 ['Zaffalon Valerio'] ['IT']
['Zammattio Roberto']
3352 ['Zammattio Roberto'] ['IT']
['Zanella Valter']
3353 ['Zanella Valter'] ['IT']
['Zdon Bill']
3354 ['Zdon Bill'] ['US']
['Zugna Davide']
3355 ['Zugna Davide'] ['IT']

Empty DataFrame
Columns: [Year, Race, Name, Sex, Nationality, Category, Status, Status1, Duration_seconds, Finish Category, Duration_hours]
Index: []

In [78]:
TOR330_dem_2018_2024_1.groupby([ 'Year', 'Status1'])['Status1'].count()

Year  Status1
2018  DNF                                       345
      Finished at Bosses or Rifugio Frassati      0
      Finished at Courmayeur                    534
2019  DNF                                       378
      Finished at Bosses or Rifugio Frassati      0
      Finished at Courmayeur                    563
2021  DNF                                       286
      Finished at Bosses or Rifugio Frassati      0
      Finished at Courmayeur                    431
2022  DNF                                       363
      Finished at Bosses or Rifugio Frassati    189
      Finished at Courmayeur                    408
2023  DNF                                       585
      Finished at Bosses or Rifugio Frassati      0
      Finished at Courmayeur                    622
2024  DNF                                       563
      Finished at Bosses or Rifugio Frassati      0
      Finished at Courmayeur                    533
Name: Status1, dtype: int64

In [77]:
TOR330_dem_2018_2024_1['Status1'] =TOR330_dem_2018_2024_1['Status1'].str.replace('Finished at Bosses','Finished at Bosses or Rifugio Frassati') 
TOR330_dem_2018_2024_1['Status1'] =TOR330_dem_2018_2024_1['Status1'].str.replace('Finished at Rifugio Frassati','Finished at Bosses or Rifugio Frassati')

In [80]:
TOR330_dem_2018_2024_1.to_excel(f'{race} Data/5. Clean Data for Data Visualisation/{race}_dem_2018_2024.xlsx', index = False)